# 90 — Nodal full-node detection, picking, and shot-gather export

This notebook replaces the earlier detection-driven `90_*` workflow.

The key difference is:

> **Detections define event times. SDS extraction defines shot-gather contents. Picks never decide which stations are saved.**

The workflow is:

1. Discover all position-coded `DP*` stations in the SDS archive. This assumes the 1000 Hz `GP*` nodes have already been downsampled to 500 Hz and rewritten as `DP*` using notebook/script `86_*`.
2. Run network coincidence detection on `DPZ` only, using all available nodes in each named time window.
3. Merge duplicate detections across chunk boundaries.
4. For each detection, extract full 3-component `DPE/DPN/DPZ` shot gathers from SDS.
5. Write full-gather MiniSEED, component SEG-Y, and wiggle/image PNGs.
6. Run first-break autopicks and write pick rows.
7. Store the processing catalog in SQLite, with optional CSV exports for inspection.

Later notebooks can use the SQLite catalog to stack repeated nodal shots, compare nodal versus Geode/streamer gathers at common source positions, and build combined super-gathers.

## 1. Imports

This expects your project library layout to include `nodal_shotgather.py` and `segy_tools` under `../lib`, as in the earlier notebooks.

In [1]:
from __future__ import annotations

from pathlib import Path
from dataclasses import dataclass, asdict
import json
import sqlite3
import uuid
import traceback
from datetime import datetime, timezone

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from obspy import Stream, UTCDateTime

# Local project library
import sys
LIB = Path("../lib").resolve()
if str(LIB) not in sys.path:
    sys.path.append(str(LIB))

from nodal_shotgather import (
    DetectionConfig,
    PickingConfig,
    read_deployment_from_sds,
    preprocess_for_detection,
    detect_network_events,
    preprocess_for_picking,
    pick_baer_aic_on_trace,
    try_ar_pick_short_station,
    consensus_pick_for_station,
)

# SEG-Y / plotting helpers. These should exist in ../lib/segy_tools.
try:
    from segy_tools.gather import gather_arrays_to_stream
    from segy_tools.io import write_segy
    from segy_tools.plotting import plot_wiggle_gather, plot_image_gather
    HAVE_SEGY_TOOLS = True
except Exception as e:
    HAVE_SEGY_TOOLS = False
    print("WARNING: could not import segy_tools helpers. SEG-Y/PNG export may be limited.")
    print(e)

WARNING: could not import segy_tools helpers. SEG-Y/PNG export may be limited.
No module named 'segy_tools'

## 2. Configuration

Update paths if needed. The SDS root should be the **position-coded SDS archive after running 86**, so all nodes appear as `DP*` at 500 Hz.

In [2]:
# -----------------------------------------------------------------------------
# Paths
# -----------------------------------------------------------------------------
PROJECT_ROOT = Path("/Volumes/tachyon/LBSSP_DATA")
SDS_ROOT = PROJECT_ROOT / "nodal_sds_position_codes"

# New output root. Use a new version when the event windows or metadata rules change.
OUT_ROOT = PROJECT_ROOT / "nodal_fullnode_shotgathers_v4"
OUT_ROOT.mkdir(parents=True, exist_ok=True)

CATALOG_DB = PROJECT_ROOT / "catalog" / "lbssp_shot_catalog.sqlite"
CSV_EXPORT_DIR = OUT_ROOT / "catalog_exports"
CSV_EXPORT_DIR.mkdir(parents=True, exist_ok=True)

# Current metadata workbook. This is used only for deriving/annotating time windows
# and for optional approximate Geode-stack metadata matching. The nodal gathers are
# still generated from SDS detections.
METADATA_WORKBOOK = PROJECT_ROOT / "jochen_field_notes_metadata_tables_with_geode_times.xlsx"
if not METADATA_WORKBOOK.exists():
    METADATA_WORKBOOK = PROJECT_ROOT / "metadata" / "jochen_field_notes_metadata_tables_with_geode_times.xlsx"
if not METADATA_WORKBOOK.exists():
    METADATA_WORKBOOK = Path("/Volumes/tachyon/LBSSP_DATA/metadata/jochen_field_notes_metadata_tables_with_geode_times.xlsx")
if not METADATA_WORKBOOK.exists():
    METADATA_WORKBOOK = None

# -----------------------------------------------------------------------------
# Survey-specific time model
# -----------------------------------------------------------------------------
# Correction convention:
#     actual UTC = recorded Geode/laptop file time + correction_s
#
# For refraction surveys, Glenn checked that the EPIC/Jochen Geode laptop was set
# to UTC but 11.5 s fast, hence correction_s = -11.5.
#
# For Daniel/GeoView streamer surveys, evidence indicates the laptop was set to
# local EDT (UTC-4) and was ~5 min 33 s fast, so correction_s is roughly
# +4 h - 5m33s = +14067 s.  T1 streamer currently has no extracted Geode times
# in the workbook, but this rule is here for later.
#
# Also important: Geode stacked-file time is treated as the FINAL trigger time
# in the stack, so nodal individual blows should occur before that corrected
# final-trigger time.
SURVEY_TIME_MODELS = {
    "T1_1m_refraction": {"correction_s": -11.5, "file_time_meaning": "final_trigger"},
    "T1_2m_refraction": {"correction_s": -11.5, "file_time_meaning": "final_trigger"},
    "T3_1m_refraction": {"correction_s": -11.5, "file_time_meaning": "final_trigger"},
    "T4_1m_refraction": {"correction_s": -11.5, "file_time_meaning": "final_trigger"},
    "T1_Streamer_MASW": {"correction_s": 4*3600 - 5*60 - 33, "file_time_meaning": "final_trigger"},
    "T1A_Streamer_MASW": {"correction_s": 4*3600 - 5*60 - 33, "file_time_meaning": "final_trigger"},
    "Streamer/MASW main transect": {"correction_s": 4*3600 - 5*60 - 33, "file_time_meaning": "final_trigger"},
    "Streamer/MASW western transect": {"correction_s": 4*3600 - 5*60 - 33, "file_time_meaning": "final_trigger"},
}

# Approximate stack windows for matching/detection-window expansion.
DEFAULT_SECONDS_PER_BLOW = 6.0
MIN_STACK_DURATION_S = 30.0
MAX_STACK_DURATION_S = 180.0
DEFAULT_STACK_DURATION_S = 120.0
FINAL_TRIGGER_MARGIN_S = 5.0
TIMEWINDOW_PAD_S = 30.0
METADATA_MATCH_TOLERANCE_S = MAX_STACK_DURATION_S

# -----------------------------------------------------------------------------
# Named processing windows.
# Fallback windows are UTC SmartSolo/SDS times from the earlier 90_* notebook.
# If the current Excel metadata workbook is available, refraction windows are
# updated from Geode file times using the fixed clock correction and final-trigger
# convention. This expands the start time earlier so the first blows in a stack
# are not missed.
# -----------------------------------------------------------------------------
FALLBACK_TIMEWINDOWS = {
    "T1_N1_Streamer": (UTCDateTime("2026-05-16T17:13:00"), UTCDateTime("2026-05-16T21:48:00")),
    "T1_N2_Nodal1": (UTCDateTime("2026-05-17T16:00:00"), UTCDateTime("2026-05-17T19:00:00")),
    "T1_N2_Refraction1m": (UTCDateTime("2026-05-18T16:03:54"), UTCDateTime("2026-05-18T18:38:33")),
    "T1_N2_Refraction2m": (UTCDateTime("2026-05-18T20:18:44"), UTCDateTime("2026-05-18T23:12:53")),
    "T1_N2_Nodal2": (UTCDateTime("2026-05-19T12:59:00"), UTCDateTime("2026-05-19T13:21:00")),
    "T1_N3_Nodal3": (UTCDateTime("2026-05-19T13:59:00"), UTCDateTime("2026-05-19T14:15:00")),
    "T3_N4_Refraction1am": (UTCDateTime("2026-05-19T16:02:00"), UTCDateTime("2026-05-19T18:25:00")),
}

SHEET_TO_TIMEWINDOW = {
    "T1_1m_Refraction": "T1_N2_Refraction1m",
    "T1_2m_Refraction": "T1_N2_Refraction2m",
    "T3_1m_Refraction": "T3_N4_Refraction1am",
}

SHEET_TO_SURVEY = {
    "T1_1m_Refraction": "T1_1m_refraction",
    "T1_2m_Refraction": "T1_2m_refraction",
    "T1_Streamer_MASW": "T1_Streamer_MASW",
    "T1A_Streamer_MASW": "T1A_Streamer_MASW",
    "T3_1m_Refraction": "T3_1m_refraction",
    "T4_1m_Refraction": "T4_1m_refraction",
}

def _pd_time_to_utcdatetime(t) -> UTCDateTime | None:
    if pd.isna(t):
        return None
    return UTCDateTime(pd.Timestamp(t).to_pydatetime())


def stack_duration_from_row(row) -> float:
    """Estimated duration before final trigger covered by a Geode stack."""
    vals = []
    for col in ["n_blows", "n_shots"]:
        if col in row.index:
            try:
                v = float(row.get(col))
                if np.isfinite(v) and v > 1:
                    vals.append(v)
            except Exception:
                pass
    if not vals:
        return DEFAULT_STACK_DURATION_S
    return float(min(MAX_STACK_DURATION_S, max(MIN_STACK_DURATION_S, max(vals) * DEFAULT_SECONDS_PER_BLOW)))


def derive_timewindows_from_metadata(workbook: Path | None, fallback: dict[str, tuple[UTCDateTime, UTCDateTime]]):
    windows = dict(fallback)
    if workbook is None or not Path(workbook).exists():
        print("No current metadata workbook found; using fallback time windows.")
        return windows

    # 1. Use Acquisition_Summary for simple known UTC windows when present.
    try:
        acq = pd.read_excel(workbook, sheet_name="Acquisition_Summary")
        for _, r in acq.iterrows():
            transect = str(r.get("transect", ""))
            activity = str(r.get("activity", "")).lower()
            start = pd.to_datetime(r.get("start_time"), errors="coerce", utc=True)
            end = pd.to_datetime(r.get("end_time"), errors="coerce", utc=True)
            if pd.isna(start) or pd.isna(end):
                continue
            label = None
            if transect == "T1" and "masw" in activity and "streamer" in activity:
                label = "T1_N1_Streamer"
            elif transect == "T1" and "dense hammer" in activity:
                label = "T1_N2_Nodal1"
            elif transect == "T1" and "nodal survey2" in activity:
                label = "T1_N2_Nodal2"
            elif transect == "T1" and "return to survey1" in activity:
                label = "T1_N3_Nodal3"
            elif transect == "T3" and "1 m refraction" in activity:
                label = "T3_N4_Refraction1am"
            if label:
                windows[label] = (UTCDateTime(start.to_pydatetime()), UTCDateTime(end.to_pydatetime()))
    except Exception as e:
        print("Could not read Acquisition_Summary for time windows:", e)

    # 2. Use Geode file times for refraction windows, expanded backwards because
    # Geode file time is the final trigger in the stack.
    for sheet, label in SHEET_TO_TIMEWINDOW.items():
        try:
            df = pd.read_excel(workbook, sheet_name=sheet)
        except Exception:
            continue
        if "geode_laptop_starttime" not in df.columns:
            continue
        t = pd.to_datetime(df["geode_laptop_starttime"], errors="coerce")
        good = df[t.notna()].copy()
        if len(good) == 0:
            continue
        survey_name = SHEET_TO_SURVEY.get(sheet, sheet)
        correction_s = SURVEY_TIME_MODELS.get(survey_name, {}).get("correction_s", 0.0)
        corrected = pd.to_datetime(good["geode_laptop_starttime"], errors="coerce", utc=True) + pd.to_timedelta(correction_s, unit="s")
        durations = good.apply(stack_duration_from_row, axis=1)
        starts = corrected - pd.to_timedelta(durations + TIMEWINDOW_PAD_S, unit="s")
        ends = corrected + pd.to_timedelta(FINAL_TRIGGER_MARGIN_S + TIMEWINDOW_PAD_S, unit="s")
        start = starts.min()
        end = ends.max()
        if pd.notna(start) and pd.notna(end):
            windows[label] = (UTCDateTime(start.to_pydatetime()), UTCDateTime(end.to_pydatetime()))

    return windows

TIMEWINDOWS = derive_timewindows_from_metadata(METADATA_WORKBOOK, FALLBACK_TIMEWINDOWS)

# Leave as None to run all windows, or set a list for testing.
RUN_LABELS = None  # e.g., ["T1_N2_Refraction1m"] for testing

# -----------------------------------------------------------------------------
# Detection and extraction settings
# -----------------------------------------------------------------------------
DETECTION_CHANNEL = "DPZ"       # Z-only detection on all downsampled/real nodes
EXTRACTION_CHANNELS = ["DPE", "DPN", "DPZ"]
DETECTION_SAMPLE_RATE_HZ = 500.0

# Exclude known moving trigger/source node if it appears in SDS.
EXCLUDE_STATIONS = {"12806", "012806", "45012806"}

# Chunked detection avoids loading many hours of data at once.
CHUNK_SECONDS = 60.0
CHUNK_OVERLAP_SECONDS = 2.0

# Event extraction windows for full shot gathers.
# These are relative to detection on_time. Increase pre_s if first breaks are clipped.
GATHER_PRE_S = 0.10
GATHER_POST_S = 0.90

# Avoid detecting/keeping duplicate events on chunk overlaps or repeated trigger branches.
MERGE_TOLERANCE_S = 0.08
MIN_EVENT_SPACING_S = 0.20

# Development limits
MAX_EVENTS_PER_WINDOW = None  # e.g. 10 for testing
WRITE_MSEED = True
WRITE_SEGY = True
WRITE_PNG = True
MAKE_PICK_DIAGNOSTICS = False
EXPORT_CSV_SNAPSHOTS = True

# Detection thresholds. Tune after looking at the event catalog.
det_cfg = DetectionConfig(
    freqmin=5.0,
    freqmax=180.0,
    corners=4,
    zerophase=True,
    sta_seconds=0.02,
    lta_seconds=0.30,
    threshold_on=4.0,
    threshold_off=1.5,
    min_channels=10,   # all 36 nodes should now be available as DPZ; tune this
    min_snr=6.0,
    pretrigger_seconds=GATHER_PRE_S,
    posttrigger_seconds=GATHER_POST_S,
)

pick_cfg = PickingConfig(
    freqmin=10.0,
    freqmax=150.0,
    corners=4,
    zerophase=False,
    pick_tolerance_s=0.02,
    min_votes=2,
    include_ar_s=False,
    mute_seconds=0.02,
)

print("SDS_ROOT:", SDS_ROOT)
print("OUT_ROOT:", OUT_ROOT)
print("CATALOG_DB:", CATALOG_DB)
print("METADATA_WORKBOOK:", METADATA_WORKBOOK)
print("RUN_LABELS:", RUN_LABELS)
print("Processing windows:")
for k, (a, b) in TIMEWINDOWS.items():
    print(f"  {k}: {a}  ->  {b}  ({b-a:.1f} s)")

# Safety and metadata matching
MIN_FREE_GB = 50.0
# Rerun policy: delete previous nodal rows and products from this output root before processing.
# Set False if you are deliberately appending a second nodal processing run to the same catalog.
REPLACE_EXISTING_NODAL_RUNS = True

SDS_ROOT: /Volumes/tachyon/LBSSP_DATA/nodal_sds_position_codes
OUT_ROOT: /Volumes/tachyon/LBSSP_DATA/nodal_fullnode_shotgathers_v4
CATALOG_DB: /Volumes/tachyon/LBSSP_DATA/catalog/lbssp_shot_catalog.sqlite
METADATA_WORKBOOK: /Volumes/tachyon/LBSSP_DATA/metadata/jochen_field_notes_metadata_tables_with_geode_times.xlsx
RUN_LABELS: None
Processing windows:
  T1_N1_Streamer: 2026-05-16T17:13:00.000000Z  ->  2026-05-16T21:48:00.000000Z  (16500.0 s)
  T1_N2_Nodal1: 2026-05-17T16:00:00.000000Z  ->  2026-05-17T19:00:00.000000Z  (10800.0 s)
  T1_N2_Refraction1m: 2026-05-18T16:02:18.500000Z  ->  2026-05-18T18:38:56.500000Z  (9398.0 s)
  T1_N2_Refraction2m: 2026-05-18T20:17:02.500000Z  ->  2026-05-18T23:13:16.500000Z  (10574.0 s)
  T1_N2_Nodal2: 2026-05-19T12:59:00.000000Z  ->  2026-05-19T13:21:00.000000Z  (1320.0 s)
  T1_N3_Nodal3: 2026-05-19T13:59:00.000000Z  ->  2026-05-19T14:15:00.000000Z  (960.0 s)
  T3_N4_Refraction1am: 2026-05-19T16:02:00.000000Z  ->  2026-05-19T18:25:00.000000Z  (8580.0 s)

## 3. SQLite catalog schema

SQLite is the source of truth. CSVs are exported only as snapshots for inspection.

In [3]:

def connect_catalog(db_path: Path) -> sqlite3.Connection:
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    conn.execute("PRAGMA foreign_keys = ON")
    conn.execute("PRAGMA journal_mode = WAL")
    conn.execute("PRAGMA busy_timeout = 30000")
    return conn


def table_columns(conn: sqlite3.Connection, table: str) -> set[str]:
    try:
        return {row[1] for row in conn.execute(f"PRAGMA table_info({table})").fetchall()}
    except Exception:
        return set()


def ensure_columns(conn: sqlite3.Connection, table: str, columns: dict[str, str]):
    """Add missing columns to an existing SQLite table.

    This lets the nodal notebook share the same SQLite catalog first populated by
    the Geode metadata notebook, whose tables have a Geode-oriented schema.
    """
    existing = table_columns(conn, table)
    for name, decl in columns.items():
        if name not in existing:
            conn.execute(f"ALTER TABLE {table} ADD COLUMN {name} {decl}")
    conn.commit()


def init_catalog(conn: sqlite3.Connection):
    # Create tables if this notebook is run before 89_*. If 89_* already created
    # the tables, we add the nodal-specific columns below.
    conn.executescript(
    """
    CREATE TABLE IF NOT EXISTS processing_runs (
        run_id TEXT PRIMARY KEY,
        notebook_name TEXT,
        run_time_utc TEXT,
        input_sds_root TEXT,
        output_root TEXT,
        parameters_json TEXT,
        notes TEXT
    );

    CREATE TABLE IF NOT EXISTS receiver_geometry (
        geometry_id TEXT,
        event_id TEXT,
        instrument_system TEXT,
        line TEXT,
        transect TEXT,
        survey TEXT,
        receiver_index INTEGER,
        receiver_x_m REAL,
        receiver_y_m REAL,
        receiver_spacing_m REAL,
        component TEXT,
        sample_rate_hz REAL,
        geometry_status TEXT,
        geometry_note TEXT,
        run_id TEXT
    );

    CREATE TABLE IF NOT EXISTS shot_events (
        event_id TEXT PRIMARY KEY,
        instrument_system TEXT,
        line TEXT,
        transect TEXT,
        survey TEXT,
        survey_type TEXT,
        shot_no INTEGER,
        file_no INTEGER,
        source_x_m REAL,
        source_type TEXT,
        n_blows INTEGER,
        n_shots INTEGER,
        operator TEXT,
        plate_type TEXT,
        shot_time_local TEXT,
        shot_time_utc TEXT,
        receiver_first_m REAL,
        receiver_last_m REAL,
        receiver_spacing_m REAL,
        nominal_shot_spacing_m REAL,
        geode_read_ok INTEGER,
        geode_read_format TEXT,
        geode_n_traces INTEGER,
        geode_sampling_rate_hz REAL,
        geode_duration_s_first_trace REAL,
        geode_file_path TEXT,
        geode_folder TEXT,
        geode_match_status TEXT,
        geode_match_note TEXT,
        source_page TEXT,
        confidence TEXT,
        review_status TEXT,
        comment TEXT,
        metadata_source_sheet TEXT,
        extra_json TEXT,
        run_id TEXT
    );

    CREATE TABLE IF NOT EXISTS shot_gather_files (
        gather_file_id TEXT PRIMARY KEY,
        event_id TEXT,
        gather_id TEXT,
        instrument_system TEXT,
        line TEXT,
        transect TEXT,
        survey TEXT,
        component TEXT,
        file_type TEXT,
        file_path TEXT,
        source_file_no INTEGER,
        n_traces INTEGER,
        n_receivers INTEGER,
        sample_rate_hz REAL,
        duration_s REAL,
        processing_level TEXT,
        geometry_id TEXT,
        run_id TEXT
    );

    CREATE TABLE IF NOT EXISTS trace_index (
        trace_index_id TEXT PRIMARY KEY,
        event_id TEXT,
        gather_id TEXT,
        instrument_system TEXT,
        line TEXT,
        transect TEXT,
        survey TEXT,
        source_x_m REAL,
        receiver_index INTEGER,
        receiver_x_m REAL,
        offset_m REAL,
        component TEXT,
        file_path TEXT,
        trace_number_in_file INTEGER,
        sample_rate_hz REAL,
        npts INTEGER,
        amplitude_scale REAL,
        run_id TEXT
    );

    CREATE TABLE IF NOT EXISTS picks (
        run_id TEXT,
        event_id TEXT,
        gather_id TEXT,
        instrument_system TEXT,
        network TEXT,
        station TEXT,
        location TEXT,
        channel TEXT,
        component TEXT,
        receiver_x_m REAL,
        source_x_m REAL,
        offset_m REAL,
        pick_time_utc TEXT,
        pick_time_relative_s REAL,
        phase TEXT,
        picker TEXT,
        pick_quality TEXT,
        snr REAL,
        details_json TEXT
    );

    CREATE TABLE IF NOT EXISTS processing_errors (
        run_id TEXT,
        context TEXT,
        label TEXT,
        event_id TEXT,
        error_text TEXT,
        traceback TEXT,
        time_utc TEXT
    );
    """
    )

    ensure_columns(conn, "processing_runs", {
        "input_sds_root": "TEXT", "output_root": "TEXT", "input_metadata_xlsx": "TEXT",
        "input_geode_file_times_csv": "TEXT", "catalog_db": "TEXT", "parameters_json": "TEXT",
        "notes": "TEXT",
    })

    ensure_columns(conn, "receiver_geometry", {
        "network": "TEXT", "location": "TEXT", "station": "TEXT", "elevation_m": "REAL",
        "channel_family": "TEXT", "active_start_utc": "TEXT", "active_end_utc": "TEXT",
        "event_id": "TEXT", "instrument_system": "TEXT", "line": "TEXT", "transect": "TEXT",
        "survey": "TEXT", "receiver_index": "INTEGER", "receiver_x_m": "REAL", "receiver_y_m": "REAL",
        "receiver_spacing_m": "REAL", "component": "TEXT", "sample_rate_hz": "REAL",
        "geometry_status": "TEXT", "geometry_note": "TEXT", "run_id": "TEXT",
    })

    ensure_columns(conn, "shot_events", {
        "instrument_system": "TEXT", "line": "TEXT", "network": "TEXT", "location": "TEXT",
        "timewindow_label": "TEXT", "geometry_id": "TEXT", "detection_time_utc": "TEXT",
        "on_time_utc": "TEXT", "off_time_utc": "TEXT", "duration_s": "REAL",
        "source_x_m": "REAL", "source_type": "TEXT", "operator": "TEXT", "plate_type": "TEXT",
        "n_blows": "INTEGER", "n_shots": "INTEGER", "matched_metadata_event_id": "TEXT",
        "metadata_match_status": "TEXT", "metadata_match_time_error_s": "REAL",
        "detection_n_seed_ids": "INTEGER", "detection_n_stations": "INTEGER",
        "detection_seed_ids": "TEXT", "detection_stations": "TEXT", "snr_rms": "REAL",
        "n_receivers_extracted": "INTEGER", "n_traces_extracted": "INTEGER", "status": "TEXT",
        "notes": "TEXT", "survey": "TEXT", "survey_type": "TEXT", "shot_no": "INTEGER", "file_no": "INTEGER",
        "shot_time_utc": "TEXT", "metadata_source_sheet": "TEXT", "run_id": "TEXT",
    })

    ensure_columns(conn, "shot_gather_files", {
        "gather_file_id": "TEXT", "event_id": "TEXT", "gather_id": "TEXT", "instrument_system": "TEXT",
        "line": "TEXT", "network": "TEXT", "location": "TEXT", "transect": "TEXT", "survey": "TEXT",
        "timewindow_label": "TEXT", "component": "TEXT", "file_type": "TEXT", "file_path": "TEXT",
        "source_file_no": "INTEGER", "n_traces": "INTEGER", "n_receivers": "INTEGER",
        "sample_rate_hz": "REAL", "duration_s": "REAL", "pre_s": "REAL", "post_s": "REAL",
        "processing_level": "TEXT", "geometry_id": "TEXT", "run_id": "TEXT",
    })

    ensure_columns(conn, "trace_index", {
        "trace_index_id": "TEXT", "event_id": "TEXT", "gather_id": "TEXT", "instrument_system": "TEXT",
        "line": "TEXT", "network": "TEXT", "station": "TEXT", "location": "TEXT", "channel": "TEXT",
        "component": "TEXT", "source_x_m": "REAL", "receiver_index": "INTEGER", "receiver_x_m": "REAL",
        "offset_m": "REAL", "starttime_utc": "TEXT", "file_path": "TEXT", "trace_number_in_file": "INTEGER",
        "trace_index": "INTEGER", "sample_rate_hz": "REAL", "sampling_rate_hz": "REAL", "npts": "INTEGER",
        "amplitude_scale": "REAL", "run_id": "TEXT",
    })

    conn.commit()


RUN_ID = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ") + "_" + uuid.uuid4().hex[:8]
conn = connect_catalog(CATALOG_DB)
init_catalog(conn)

if REPLACE_EXISTING_NODAL_RUNS:
    # Remove prior nodal catalog rows. Output files are not deleted automatically;
    # using a new OUT_ROOT version is safer for reruns.
    for sql in [
        "DELETE FROM picks WHERE instrument_system = 'nodal'",
        "DELETE FROM trace_index WHERE instrument_system = 'nodal'",
        "DELETE FROM shot_gather_files WHERE instrument_system = 'nodal'",
        "DELETE FROM receiver_geometry WHERE instrument_system = 'nodal'",
        "DELETE FROM shot_events WHERE instrument_system = 'nodal'",
    ]:
        try:
            conn.execute(sql)
        except Exception as e:
            print(f"Nodal cleanup skipped/failed for {sql}: {e}")
    conn.commit()
    print("Removed previous nodal catalog rows before this run.")

params = {
    "SDS_ROOT": str(SDS_ROOT),
    "OUT_ROOT": str(OUT_ROOT),
    "CATALOG_DB": str(CATALOG_DB),
    "TIMEWINDOWS": {k: [str(v[0]), str(v[1])] for k, v in TIMEWINDOWS.items()},
    "RUN_LABELS": RUN_LABELS,
    "DETECTION_CHANNEL": DETECTION_CHANNEL,
    "EXTRACTION_CHANNELS": EXTRACTION_CHANNELS,
    "CHUNK_SECONDS": CHUNK_SECONDS,
    "CHUNK_OVERLAP_SECONDS": CHUNK_OVERLAP_SECONDS,
    "GATHER_PRE_S": GATHER_PRE_S,
    "GATHER_POST_S": GATHER_POST_S,
    "MERGE_TOLERANCE_S": MERGE_TOLERANCE_S,
    "MIN_EVENT_SPACING_S": MIN_EVENT_SPACING_S,
    "MIN_FREE_GB": MIN_FREE_GB,
    "METADATA_MATCH_TOLERANCE_S": METADATA_MATCH_TOLERANCE_S,
    "REPLACE_EXISTING_NODAL_RUNS": REPLACE_EXISTING_NODAL_RUNS,
    "det_cfg": asdict(det_cfg),
    "pick_cfg": asdict(pick_cfg),
}

# Insert only columns that exist in processing_runs, since 89_* and 90_* may
# have slightly different run-provenance schemas.
run_row = {
    "run_id": RUN_ID,
    "notebook_name": "90_nodal_fullnode_detection_pick_and_shotgathers.ipynb",
    "run_time_utc": datetime.now(timezone.utc).isoformat(),
    "input_sds_root": str(SDS_ROOT),
    "output_root": str(OUT_ROOT),
    "catalog_db": str(CATALOG_DB),
    "parameters_json": json.dumps(params, indent=2),
    "notes": "Full-node nodal shot-gather factory; DPZ detection, DP[ENZ] extraction, metadata matching to Geode catalog.",
}
cols = list(table_columns(conn, "processing_runs") & set(run_row.keys()))
pd.DataFrame([{k: run_row[k] for k in cols}]).to_sql("processing_runs", conn, if_exists="append", index=False)
conn.commit()
print("RUN_ID:", RUN_ID)

Removed previous nodal catalog rows before this run.
RUN_ID: 20260617T230552Z_da97ed5d

## 4. Utility functions

Position-coded stations are interpreted as centimetres along the line, e.g. `08808 -> 88.08 m`.

In [4]:
def parse_label(label: str) -> tuple[str, str]:
    """Parse labels like T1_N1_Streamer into network/location."""
    parts = str(label).split("_")
    if len(parts) < 2:
        raise ValueError(f"Cannot parse network/location from label: {label}")
    return parts[0], parts[1]


def station_to_x_m(station: str) -> float:
    """Position-coded station name -> x position in metres."""
    s = str(station).strip()
    if not s.isdigit():
        return np.nan
    return int(s) / 100.0


def channel_to_component(channel: str) -> str:
    return str(channel)[-1].upper()


def stream_stations(st: Stream) -> list[str]:
    return sorted({str(tr.stats.station) for tr in st})


def stream_seed_ids(st: Stream) -> list[str]:
    return sorted({tr.id for tr in st})


def discover_sds_stations(
    sds_root: Path,
    network: str,
    location: str,
    channel_pattern: str = "DPZ",
    exclude_stations: set[str] | None = None,
) -> list[str]:
    """Discover station codes with files matching an SDS channel selector."""
    exclude_stations = exclude_stations or set()
    root = Path(sds_root)
    stations = set()
    # Pattern: YEAR/NET/STA/CHAN.D/NET.STA.LOC.CHAN.D.YEAR.JDAY
    for p in root.rglob(f"{network}.*.{location}.{channel_pattern}.D.*.*"):
        if p.name.startswith("._"):
            continue
        try:
            parts = p.name.split(".")
            if len(parts) >= 7:
                net, sta, loc, cha = parts[:4]
                if net == network and loc == location:
                    if sta not in exclude_stations:
                        stations.add(sta)
        except Exception:
            pass
    return sorted(stations, key=lambda s: (station_to_x_m(s), s))


def build_geometry_df(label: str, start: UTCDateTime, end: UTCDateTime, stations: list[str]) -> pd.DataFrame:
    network, location = parse_label(label)
    rows = []
    for sta in stations:
        rows.append({
            "run_id": RUN_ID,
            "geometry_id": f"{label}_{network}_{location}_DPall",
            "instrument_system": "nodal",
            "line": network,
            "network": network,
            "location": location,
            "station": sta,
            "receiver_x_m": station_to_x_m(sta),
            "receiver_y_m": 0.0,
            "elevation_m": 0.0,
            "channel_family": "DP",
            "sample_rate_hz": DETECTION_SAMPLE_RATE_HZ,
            "active_start_utc": str(start),
            "active_end_utc": str(end),
        })
    return pd.DataFrame(rows)


def utc_to_str(x) -> str | None:
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return None
    try:
        return str(UTCDateTime(x))
    except Exception:
        return str(x)


def log_error(conn, context, label=None, event_id=None, exc=None):
    conn.execute(
        "INSERT INTO processing_errors VALUES (?, ?, ?, ?, ?, ?, ?)",
        (
            RUN_ID,
            context,
            label,
            event_id,
            str(exc),
            traceback.format_exc(),
            datetime.now(timezone.utc).isoformat(),
        ),
    )
    conn.commit()


def check_free_space(path: Path, min_free_gb: float = MIN_FREE_GB):
    import shutil
    usage = shutil.disk_usage(Path(path))
    free_gb = usage.free / (1024**3)
    if free_gb < min_free_gb:
        raise RuntimeError(f"Only {free_gb:.1f} GiB free at {path}; stopping before writing more outputs.")
    return free_gb

## 5. Detection helpers

Detection is run on `DPZ` only, after the `86_*` downsampling step has converted `GP*` data to `DP*` channels. The resulting detection stream should include both original 500 Hz nodes and downsampled 1000 Hz nodes.

In [5]:
def iter_time_chunks(start: UTCDateTime, end: UTCDateTime, chunk_s: float, overlap_s: float):
    t = UTCDateTime(start)
    i = 0
    while t < end:
        core_start = t
        core_end = min(t + chunk_s, end)
        read_start = max(start, core_start - overlap_s)
        read_end = min(end, core_end + overlap_s)
        yield i, core_start, core_end, read_start, read_end
        t = core_end
        i += 1


def read_detection_stream(label: str, read_start: UTCDateTime, read_end: UTCDateTime, stations: list[str]) -> Stream:
    network, location = parse_label(label)
    # Read station='*' first because EnhancedSDSClient supports wildcards.
    st = read_deployment_from_sds(
        SDS_ROOT,
        network=network,
        location=location,
        station="*",
        channel=DETECTION_CHANNEL,
        starttime=read_start,
        endtime=read_end,
        merge=True,
        verbose=False,
    )
    # Keep only expected/excluded-filtered stations.
    keep = set(stations)
    st = Stream([tr for tr in st if str(tr.stats.station) in keep])
    if len(st):
        st.sort(keys=["station", "channel"])
    return st


def run_detection_for_window(label: str, start: UTCDateTime, end: UTCDateTime, stations: list[str]) -> pd.DataFrame:
    rows = []
    chunk_out = OUT_ROOT / label / "tables" / "chunk_detections"
    chunk_out.mkdir(parents=True, exist_ok=True)

    for chunk_index, core_start, core_end, read_start, read_end in iter_time_chunks(start, end, CHUNK_SECONDS, CHUNK_OVERLAP_SECONDS):
        print(f"{label} chunk {chunk_index}: {core_start} to {core_end}")
        try:
            st_raw = read_detection_stream(label, read_start, read_end, stations)
            if len(st_raw) == 0:
                print("  no traces")
                continue
            print(f"  read {len(st_raw)} traces, {len(stream_stations(st_raw))} stations")

            st_det = preprocess_for_detection(st_raw, det_cfg)
            df = detect_network_events(st_det, det_cfg, write_mseed=False, make_plots=False)
            if len(df) == 0:
                continue

            # Keep detections whose on_time lies inside the core chunk, avoiding duplicate overlap products.
            df = df.copy()
            df["on_time_dt"] = df["on_time"].apply(lambda x: UTCDateTime(x))
            df = df[(df["on_time_dt"] >= core_start) & (df["on_time_dt"] < core_end)].copy()
            if len(df) == 0:
                continue

            df["run_id"] = RUN_ID
            df["timewindow_label"] = label
            network, location = parse_label(label)
            df["network"] = network
            df["location"] = location
            df["chunk_index"] = chunk_index
            df["core_start_utc"] = str(core_start)
            df["core_end_utc"] = str(core_end)
            df["read_start_utc"] = str(read_start)
            df["read_end_utc"] = str(read_end)
            df["n_available_detection_stations"] = len(stations)
            df = df.drop(columns=["on_time_dt"])

            outcsv = chunk_out / f"{label}_{network}_{location}_{chunk_index:06d}_{core_start.strftime('%Y%m%dT%H%M%S')}_{core_end.strftime('%Y%m%dT%H%M%S')}_detections.csv"
            df.to_csv(outcsv, index=False)
            rows.append(df)
            print(f"  detections: {len(df)}")
        except Exception as e:
            print(f"  ERROR: {e}")
            log_error(conn, "detection_chunk", label=label, exc=e)

    if not rows:
        return pd.DataFrame()
    out = pd.concat(rows, ignore_index=True)
    return out


def merge_detection_catalog(df: pd.DataFrame, tolerance_s: float = 0.08, min_spacing_s: float = 0.20) -> pd.DataFrame:
    """Merge near-duplicate detections, keeping the row with largest n_seed_ids/SNR."""
    if len(df) == 0:
        return df.copy()

    d = df.copy()
    d["_on"] = d["on_time"].apply(lambda x: UTCDateTime(x).timestamp)
    d = d.sort_values("_on").reset_index(drop=True)

    groups = []
    current = [0]
    for i in range(1, len(d)):
        if d.loc[i, "_on"] - d.loc[current[-1], "_on"] <= tolerance_s:
            current.append(i)
        else:
            groups.append(current)
            current = [i]
    groups.append(current)

    keep_rows = []
    for g in groups:
        sub = d.loc[g].copy()
        # Prefer more triggering channels/stations, then higher SNR if present.
        sort_cols = []
        ascending = []
        for c in ["n_seed_ids", "n_stations", "snr_rms"]:
            if c in sub.columns:
                sort_cols.append(c)
                ascending.append(False)
        if sort_cols:
            sub = sub.sort_values(sort_cols, ascending=ascending)
        keep_rows.append(sub.iloc[0])

    merged = pd.DataFrame(keep_rows).drop(columns=["_on"], errors="ignore").reset_index(drop=True)

    # Enforce minimum spacing by keeping stronger row when detections are still too close.
    if len(merged) <= 1:
        return merged
    merged["_on"] = merged["on_time"].apply(lambda x: UTCDateTime(x).timestamp)
    final = []
    for _, row in merged.sort_values("_on").iterrows():
        if not final:
            final.append(row)
            continue
        if row["_on"] - final[-1]["_on"] < min_spacing_s:
            prev = final[-1]
            score_prev = float(prev.get("n_seed_ids", 0) or 0) + 0.01 * float(prev.get("snr_rms", 0) or 0)
            score_new = float(row.get("n_seed_ids", 0) or 0) + 0.01 * float(row.get("snr_rms", 0) or 0)
            if score_new > score_prev:
                final[-1] = row
        else:
            final.append(row)
    return pd.DataFrame(final).drop(columns=["_on"], errors="ignore").reset_index(drop=True)

## 6. Full-gather extraction, plotting, SEG-Y export, and picking

SEG-Y and plot geometry are based directly on position-coded station names, not trace index.

In [6]:
def read_full_gather_from_sds(label: str, event_time: UTCDateTime, stations: list[str]) -> Stream:
    network, location = parse_label(label)
    t1 = event_time - GATHER_PRE_S
    t2 = event_time + GATHER_POST_S
    st = read_deployment_from_sds(
        SDS_ROOT,
        network=network,
        location=location,
        station="*",
        channel="DP?",
        starttime=t1,
        endtime=t2,
        merge=True,
        verbose=False,
    )
    keep = set(stations)
    st = Stream([tr for tr in st if str(tr.stats.station) in keep and tr.stats.channel in EXTRACTION_CHANNELS])
    st.sort(keys=["station", "channel"])
    return st


def stream_to_component_arrays(st: Stream, component: str) -> tuple[np.ndarray, np.ndarray, np.ndarray, list]:
    """Return time, data(ntr,npts), receiver_x_m, ordered traces for one component."""
    component = component.upper()
    traces = [tr for tr in st if channel_to_component(tr.stats.channel) == component]
    traces = sorted(traces, key=lambda tr: (station_to_x_m(tr.stats.station), tr.stats.station))
    if not traces:
        return np.array([]), np.empty((0, 0)), np.array([]), []
    npts = min(tr.stats.npts for tr in traces)
    dt = float(traces[0].stats.delta)
    time = np.arange(npts) * dt
    data = np.vstack([np.asarray(tr.data[:npts], dtype=np.float32) for tr in traces])
    rx = np.asarray([station_to_x_m(tr.stats.station) for tr in traces], dtype=float)
    return time, data, rx, traces


def write_component_products(
    st_event: Stream,
    label: str,
    event_id: str,
    gather_id: str,
    source_x_m: float | None,
) -> tuple[list[dict], list[dict]]:
    """Write MiniSEED, component SEG-Y and PNG files. Return file rows and trace-index rows."""
    network, location = parse_label(label)
    event_dir = OUT_ROOT / label
    mseed_dir = event_dir / "gathers_mseed"
    segy_dir = event_dir / "gathers_segy"
    fig_dir = event_dir / "figures"
    for d in [mseed_dir, segy_dir, fig_dir]:
        d.mkdir(parents=True, exist_ok=True)

    file_rows = []
    trace_rows = []
    source_x_for_headers = 0.0 if source_x_m is None or not np.isfinite(source_x_m) else float(source_x_m)

    # Full 3C MiniSEED
    mseed_path = mseed_dir / f"{event_id}_DPall.mseed"
    if WRITE_MSEED:
        st_event.write(str(mseed_path), format="MSEED")
        file_rows.append({
            "gather_file_id": f"GF_{event_id}_MSEED_3C",
            "run_id": RUN_ID, "event_id": event_id, "gather_id": gather_id,
            "line": network, "network": network, "location": location, "timewindow_label": label,
            "instrument_system": "nodal", "component": "3C", "file_type": "mseed",
            "file_path": str(mseed_path), "n_traces": len(st_event),
            "n_receivers": len(stream_stations(st_event)),
            "sample_rate_hz": float(st_event[0].stats.sampling_rate) if len(st_event) else np.nan,
            "pre_s": GATHER_PRE_S, "post_s": GATHER_POST_S,
            "processing_level": "raw_fullnode",
        })

    # Trace index points to the MiniSEED bundle by default.
    for i, tr in enumerate(sorted(st_event, key=lambda tr: (station_to_x_m(tr.stats.station), tr.stats.channel))):
        rx = station_to_x_m(tr.stats.station)
        sx = np.nan if source_x_m is None else source_x_m
        trace_rows.append({
            "trace_index_id": f"TR_{event_id}_{i:05d}",
            "run_id": RUN_ID, "event_id": event_id, "gather_id": gather_id,
            "line": network,
            "instrument_system": "nodal", "network": tr.stats.network,
            "station": tr.stats.station, "location": tr.stats.location,
            "channel": tr.stats.channel, "component": channel_to_component(tr.stats.channel),
            "receiver_x_m": rx, "source_x_m": sx,
            "offset_m": np.nan if not np.isfinite(sx) else rx - sx,
            "starttime_utc": str(tr.stats.starttime),
            "sampling_rate_hz": float(tr.stats.sampling_rate), "npts": int(tr.stats.npts),
            "file_path": str(mseed_path), "trace_index": i,
            "amplitude_scale": 1.0,
        })

    # Component SEG-Y and figures
    for comp in ["Z", "N", "E"]:
        time, data, rx, traces = stream_to_component_arrays(st_event, comp)
        if len(traces) == 0:
            continue
        dt = float(traces[0].stats.delta)
        sr = float(traces[0].stats.sampling_rate)

        if WRITE_SEGY and HAVE_SEGY_TOOLS:
            segy_path = segy_dir / comp / f"{event_id}_{comp}.sgy"
            segy_path.parent.mkdir(parents=True, exist_ok=True)
            segy_st = gather_arrays_to_stream(
                data=data,
                dt_s=dt,
                starttime=traces[0].stats.starttime,
                receiver_x_m=rx,
                source_x_m=source_x_for_headers,
                shot_number=int(event_id.split("E")[-1]) if "E" in event_id else 1,
                station_prefix="R",
                network=network,
                component=comp,
            )
            write_segy(segy_st, segy_path)
            file_rows.append({
                "gather_file_id": f"GF_{event_id}_{comp}_SEGY",
                "run_id": RUN_ID, "event_id": event_id, "gather_id": f"{gather_id}_{comp}",
                "line": network, "network": network, "location": location, "timewindow_label": label,
                "instrument_system": "nodal", "component": comp, "file_type": "segy",
                "file_path": str(segy_path), "n_traces": int(data.shape[0]),
                "n_receivers": int(len(rx)), "sample_rate_hz": sr,
                "pre_s": GATHER_PRE_S, "post_s": GATHER_POST_S,
                "processing_level": "raw_fullnode_component",
            })

        if WRITE_PNG and HAVE_SEGY_TOOLS:
            wiggle_path = fig_dir / f"wiggle_{comp}" / f"{event_id}_{comp}_wiggle.png"
            image_path = fig_dir / f"image_{comp}" / f"{event_id}_{comp}_image.png"
            title = f"{event_id} {comp} — {label}"
            plot_wiggle_gather(
                time, data, rx,
                source_x_m=source_x_m,
                title=title,
                tmin=0.0, tmax=min(GATHER_PRE_S + GATHER_POST_S, 1.0),
                scale=0.8, clip_percentile=99, normalize=True,
                outfile=wiggle_path,
            )
            plot_image_gather(
                time, data, rx,
                source_x_m=source_x_m,
                title=title,
                tmin=0.0, tmax=min(GATHER_PRE_S + GATHER_POST_S, 1.0),
                clip_percentile=98,
                outfile=image_path,
            )
            for path, ftype in [(wiggle_path, "png_wiggle"), (image_path, "png_image")]:
                file_rows.append({
                    "gather_file_id": f"GF_{event_id}_{comp}_{ftype.upper()}",
                    "run_id": RUN_ID, "event_id": event_id, "gather_id": f"{gather_id}_{comp}",
                    "line": network, "network": network, "location": location, "timewindow_label": label,
                    "instrument_system": "nodal", "component": comp, "file_type": ftype,
                    "file_path": str(path), "n_traces": int(data.shape[0]),
                    "n_receivers": int(len(rx)), "sample_rate_hz": sr,
                    "pre_s": GATHER_PRE_S, "post_s": GATHER_POST_S,
                    "processing_level": "raw_fullnode_component",
                })

    return file_rows, trace_rows


def pick_event_stream(st_event: Stream, event_id: str, gather_id: str, source_x_m: float | None) -> pd.DataFrame:
    """Run GeoPark-style component pickers and station consensus on one full shot gather."""
    rows = []
    if len(st_event) == 0:
        return pd.DataFrame()

    st_pick = preprocess_for_picking(st_event.copy(), pick_cfg)
    event_start = min(tr.stats.starttime for tr in st_pick)

    for station in stream_stations(st_pick):
        st_sta = st_pick.select(station=station)
        if len(st_sta) == 0:
            continue
        picks_by_comp = {}
        tr_z = tr_n = tr_e = None
        for comp in ["Z", "N", "E"]:
            sel = [tr for tr in st_sta if channel_to_component(tr.stats.channel) == comp]
            if not sel:
                continue
            tr = sel[0]
            if comp == "Z": tr_z = tr
            if comp == "N": tr_n = tr
            if comp == "E": tr_e = tr
            try:
                picks_by_comp[comp] = pick_baer_aic_on_trace(tr)
            except Exception as e:
                picks_by_comp[comp] = {"aic_ok": False, "baer_ok": False, "aic_error": str(e), "baer_error": str(e)}

        p_ar = s_ar = None
        if pick_cfg.include_ar_s and tr_z is not None and tr_n is not None and tr_e is not None:
            try:
                p_ar, s_ar = try_ar_pick_short_station(tr_z, tr_n, tr_e, f1=pick_cfg.freqmin, f2=pick_cfg.freqmax)
            except Exception:
                pass

        if tr_z is not None and picks_by_comp:
            consensus = consensus_pick_for_station(
                picks_by_comp,
                tr_z,
                p_ar=p_ar,
                s_ar=s_ar,
                pick_tolerance_s=pick_cfg.pick_tolerance_s,
                min_votes=pick_cfg.min_votes,
                min_weight=pick_cfg.min_weight,
                include_ar_s=pick_cfg.include_ar_s,
                baer_weight=pick_cfg.baer_weight,
                mute_seconds=pick_cfg.mute_seconds,
            )
        else:
            consensus = {"ok": False, "time": None, "relative_s": np.nan, "n_votes": 0, "weight": 0, "methods": [], "components": []}

        rx = station_to_x_m(station)
        sx = np.nan if source_x_m is None else source_x_m

        # Individual picker rows
        for comp, d in picks_by_comp.items():
            tr = [tr for tr in st_sta if channel_to_component(tr.stats.channel) == comp][0]
            for method in ["aic", "baer"]:
                ok = bool(d.get(f"{method}_ok", False))
                t = d.get(f"{method}_time") if ok else None
                rows.append({
                    "run_id": RUN_ID, "event_id": event_id, "gather_id": gather_id,
                    "instrument_system": "nodal", "network": tr.stats.network,
                    "station": station, "location": tr.stats.location,
                    "channel": tr.stats.channel, "component": comp,
                    "receiver_x_m": rx, "source_x_m": sx,
                    "offset_m": np.nan if not np.isfinite(sx) else rx - sx,
                    "pick_time_utc": str(t) if t is not None else None,
                    "pick_time_relative_s": float(t - event_start) if t is not None else np.nan,
                    "phase": "P?", "picker": method,
                    "pick_quality": "candidate" if ok else "failed",
                    "snr": np.nan,
                    "details_json": json.dumps({k: str(v) for k, v in d.items()}),
                })

        # Consensus row
        if consensus.get("ok"):
            t = consensus.get("time")
            pick_time_utc = str(t)
            rel = float(t - event_start)
            quality = "consensus"
        else:
            pick_time_utc = None
            rel = np.nan
            quality = "failed"
        rows.append({
            "run_id": RUN_ID, "event_id": event_id, "gather_id": gather_id,
            "instrument_system": "nodal", "network": st_sta[0].stats.network,
            "station": station, "location": st_sta[0].stats.location,
            "channel": "DP?", "component": "3C",
            "receiver_x_m": rx, "source_x_m": sx,
            "offset_m": np.nan if not np.isfinite(sx) else rx - sx,
            "pick_time_utc": pick_time_utc,
            "pick_time_relative_s": rel,
            "phase": "P?", "picker": "consensus",
            "pick_quality": quality,
            "snr": np.nan,
            "details_json": json.dumps({
                "votes": consensus.get("n_votes"),
                "weight": consensus.get("weight"),
                "methods": consensus.get("methods"),
                "components": consensus.get("components"),
                "p_ar_s": p_ar,
                "s_ar_s": s_ar,
            }),
        })
    return pd.DataFrame(rows)

## 7. Optional metadata matching hook

This is intentionally conservative. If no reliable metadata match is found, the event is still written with `metadata_match_status='unmatched_detection'` and `source_x_m=NULL`.

You can later improve this function using Jochen's spreadsheet columns once the shot-time table is finalized.

In [7]:

# Load Geode/field metadata from the current Excel workbook when available.
# This makes the notebook robust to renamed surveys such as:
#   - "Streamer/MASW main transect" -> T1_Streamer_MASW
#   - "Streamer/MASW western transect" -> T1A_Streamer_MASW
# and to T1 streamer rows whose `transect` values are shot labels (T1, T2, T3, ...),
# not actual transect names.
#
# Matching here is only approximate annotation. The authoritative source-position
# matching and stack-building should be handled later by notebooks 95/96.

def normalize_survey_name(sheet: str | None, survey: str | None = None) -> str:
    s = str(survey).strip() if survey is not None and str(survey) != "nan" else ""
    sh = str(sheet).strip() if sheet is not None else ""
    if sh in SHEET_TO_SURVEY:
        return SHEET_TO_SURVEY[sh]
    low = s.lower()
    if "main transect" in low or ("streamer" in low and "main" in low):
        return "T1_Streamer_MASW"
    if "western" in low or "t1a" in low:
        return "T1A_Streamer_MASW"
    if "1m" in low or "1 m" in low:
        if "t3" in low:
            return "T3_1m_refraction"
        if "t4" in low:
            return "T4_1m_refraction"
        return "T1_1m_refraction"
    if "2m" in low or "2 m" in low:
        return "T1_2m_refraction"
    return s or sh


def canonical_line_from_sheet(sheet: str, row: pd.Series) -> str:
    # Important: in T1_Streamer_MASW, the spreadsheet's `transect` column contains
    # values like T1, T2, ..., T83 that are shot labels, not line names. Use the
    # sheet name as source of truth for line/transect.
    if sheet == "T1_Streamer_MASW":
        return "T1"
    if sheet == "T1A_Streamer_MASW":
        return "T1A"
    if sheet.startswith("T1_"):
        return "T1"
    if sheet.startswith("T3_"):
        return "T3"
    if sheet.startswith("T4_"):
        return "T4"
    tr = str(row.get("transect", "")).strip()
    return tr if tr and tr != "nan" else ""


def source_x_from_metadata_row(row: pd.Series):
    for col in ["source_position_m", "shot_location_m"]:
        if col in row.index:
            x = pd.to_numeric(pd.Series([row.get(col)]), errors="coerce").iloc[0]
            if np.isfinite(x):
                return float(x)
    return np.nan


def corrected_geode_final_time(row: pd.Series, survey_name: str):
    if "geode_laptop_starttime" not in row.index:
        return pd.NaT
    t = pd.to_datetime(row.get("geode_laptop_starttime"), errors="coerce", utc=True)
    if pd.isna(t):
        return pd.NaT
    correction_s = SURVEY_TIME_MODELS.get(survey_name, {}).get("correction_s", 0.0)
    return t + pd.to_timedelta(correction_s, unit="s")


def load_metadata_events_from_workbook(workbook: Path | None) -> pd.DataFrame:
    if workbook is None or not Path(workbook).exists():
        return pd.DataFrame()

    sheets = [
        "T1_1m_Refraction",
        "T1_2m_Refraction",
        "T1_Streamer_MASW",
        "T1A_Streamer_MASW",
        "T3_1m_Refraction",
        "T4_1m_Refraction",
    ]
    rows = []
    for sheet in sheets:
        try:
            df = pd.read_excel(workbook, sheet_name=sheet)
        except Exception:
            continue
        for _, r in df.iterrows():
            survey_name = normalize_survey_name(sheet, r.get("survey"))
            line = canonical_line_from_sheet(sheet, r)
            x = source_x_from_metadata_row(r)
            final_time = corrected_geode_final_time(r, survey_name)
            duration_s = stack_duration_from_row(r)
            if pd.notna(final_time):
                stack_start = final_time - pd.to_timedelta(duration_s, unit="s")
                stack_end = final_time + pd.to_timedelta(FINAL_TRIGGER_MARGIN_S, unit="s")
            else:
                stack_start = pd.NaT
                stack_end = pd.NaT

            file_no = pd.to_numeric(pd.Series([r.get("file_no")]), errors="coerce").iloc[0] if "file_no" in r.index else np.nan
            shot_no = pd.to_numeric(pd.Series([r.get("shot_no")]), errors="coerce").iloc[0] if "shot_no" in r.index else np.nan
            event_id = f"GEODE_{sheet.upper()}_F{int(file_no) if np.isfinite(file_no) else len(rows)+1}"

            rows.append({
                "event_id": event_id,
                "instrument_system": "geode",
                "line": line,
                "transect": line,
                "survey": survey_name,
                "survey_type": "geode_stack_metadata",
                "shot_no": None if not np.isfinite(shot_no) else int(shot_no),
                "file_no": None if not np.isfinite(file_no) else int(file_no),
                "source_x_m": x,
                "source_type": r.get("source_type", "hammer"),
                "n_blows": r.get("n_blows", None),
                "n_shots": r.get("n_shots", None),
                "operator": r.get("operator", None),
                "plate_type": r.get("plate_type", None),
                "geode_laptop_starttime": r.get("geode_laptop_starttime", None),
                "geode_final_trigger_utc_dt": final_time,
                "geode_stack_start_dt": stack_start,
                "geode_stack_end_dt": stack_end,
                "stack_duration_s": duration_s,
                "metadata_source_sheet": sheet,
                "comment": r.get("comment", r.get("comments", None)),
                "confidence": r.get("confidence", None),
                "review_status": r.get("review_status", None),
            })
    out = pd.DataFrame(rows)
    if len(out):
        out["line"] = out["line"].astype(str)
        out["source_x_m"] = pd.to_numeric(out["source_x_m"], errors="coerce")
    return out


def load_indexed_metadata_events(conn: sqlite3.Connection) -> pd.DataFrame:
    """Fallback: load any Geode metadata rows already stored in SQLite."""
    try:
        df = pd.read_sql(
            """
            SELECT event_id, instrument_system, line, transect, survey, survey_type,
                   shot_no, file_no, source_x_m, source_type, n_blows, n_shots,
                   operator, plate_type, shot_time_utc, metadata_source_sheet,
                   comment, confidence, review_status
            FROM shot_events
            WHERE instrument_system = 'geode'
              AND source_x_m IS NOT NULL
            """,
            conn,
        )
    except Exception as e:
        print("Could not load indexed Geode metadata:", e)
        return pd.DataFrame()

    if len(df):
        df["survey"] = [normalize_survey_name(sh, sv) for sh, sv in zip(df.get("metadata_source_sheet", ""), df.get("survey", ""))]
        df["shot_time_dt"] = pd.to_datetime(df.get("shot_time_utc"), utc=True, errors="coerce")
        df["geode_final_trigger_utc_dt"] = df["shot_time_dt"]
        df["geode_stack_start_dt"] = df["shot_time_dt"] - pd.to_timedelta(DEFAULT_STACK_DURATION_S, unit="s")
        df["geode_stack_end_dt"] = df["shot_time_dt"] + pd.to_timedelta(FINAL_TRIGGER_MARGIN_S, unit="s")
        df["line"] = df["line"].astype(str)
    return df


metadata_events = load_metadata_events_from_workbook(METADATA_WORKBOOK)
if len(metadata_events) == 0:
    metadata_events = load_indexed_metadata_events(conn)

print("metadata events available for approximate stack-window matching:", len(metadata_events))
if len(metadata_events):
    display(metadata_events.groupby(["line", "survey", "metadata_source_sheet"]).size().reset_index(name="n"))
    display(metadata_events[["event_id", "line", "survey", "file_no", "source_x_m", "geode_final_trigger_utc_dt", "geode_stack_start_dt", "geode_stack_end_dt"]].head(10))


def _empty_meta_status(status: str, dt=None):
    return {
        "source_x_m": None,
        "source_type": None,
        "operator": None,
        "plate_type": None,
        "n_blows": None,
        "n_shots": None,
        "matched_metadata_event_id": None,
        "metadata_match_status": status,
        "metadata_match_time_error_s": dt,
        "survey": None,
        "survey_type": None,
        "shot_no": None,
        "file_no": None,
        "notes": None,
    }


def match_metadata_for_detection(label: str, detection_time: UTCDateTime) -> dict:
    """Approximate annotation of a nodal detection using Geode stack windows.

    This treats Geode file time as the final trigger in a stack and applies the
    survey-specific clock correction above. It does NOT use source-position
    estimates, so later notebooks should refine these associations.
    """
    network, location = parse_label(label)
    if len(metadata_events) == 0:
        return _empty_meta_status("unmatched_no_metadata_events")

    det_dt = pd.to_datetime(str(detection_time), utc=True)
    candidates = metadata_events[metadata_events["line"].astype(str) == str(network)].copy()
    candidates = candidates[candidates["geode_stack_start_dt"].notna() & candidates["geode_stack_end_dt"].notna()].copy()

    if len(candidates) == 0:
        return _empty_meta_status("unmatched_no_same_line_timed_metadata")

    inside = candidates[(candidates["geode_stack_start_dt"] <= det_dt) & (det_dt <= candidates["geode_stack_end_dt"])].copy()
    if len(inside) == 0:
        candidates["dt_abs_s"] = (candidates["geode_final_trigger_utc_dt"] - det_dt).dt.total_seconds().abs()
        best_dt = float(candidates["dt_abs_s"].min()) if len(candidates) else None
        return _empty_meta_status(f"unmatched_no_stack_window_contains_detection_nearest_{best_dt:.3f}s", best_dt)

    # Prefer the Geode stack whose final trigger is closest after/near the nodal event.
    inside["dt_to_final_s"] = (inside["geode_final_trigger_utc_dt"] - det_dt).dt.total_seconds()
    inside["dt_abs_s"] = inside["dt_to_final_s"].abs()
    best = inside.sort_values(["dt_abs_s", "file_no"]).iloc[0]

    def _int_or_none(x):
        try:
            return None if pd.isna(x) else int(float(x))
        except Exception:
            return None

    return {
        "source_x_m": float(best["source_x_m"]) if np.isfinite(best.get("source_x_m", np.nan)) else None,
        "source_type": best.get("source_type"),
        "operator": best.get("operator"),
        "plate_type": best.get("plate_type"),
        "n_blows": _int_or_none(best.get("n_blows")),
        "n_shots": _int_or_none(best.get("n_shots")),
        "matched_metadata_event_id": best.get("event_id"),
        "metadata_match_status": "matched_geode_stack_window_time_only",
        "metadata_match_time_error_s": float(best.get("dt_to_final_s")),
        "survey": best.get("survey"),
        "survey_type": best.get("survey_type"),
        "shot_no": _int_or_none(best.get("shot_no")),
        "file_no": _int_or_none(best.get("file_no")),
        "notes": best.get("comment"),
    }

metadata events available for approximate stack-window matching: 327

  line             survey metadata_source_sheet   n
0   T1   T1_1m_refraction      T1_1m_Refraction  46
1   T1   T1_2m_refraction      T1_2m_Refraction  42
2   T1   T1_Streamer_MASW      T1_Streamer_MASW  83
3  T1A  T1A_Streamer_MASW     T1A_Streamer_MASW  87
4   T3   T3_1m_refraction      T3_1m_Refraction  39
5   T4   T4_1m_refraction      T4_1m_Refraction  30

,event_id,line,survey,file_no,source_x_m,geode_final_trigger_utc_dt,geode_stack_start_dt,geode_stack_end_dt
0,GEODE_T1_1M_REFRACTION_F3001,T1,T1_1m_refraction,3001,82.5,NaT,NaT,NaT
1,GEODE_T1_1M_REFRACTION_F3002,T1,T1_1m_refraction,3002,82.5,NaT,NaT,NaT
2,GEODE_T1_1M_REFRACTION_F3003,T1,T1_1m_refraction,3003,82.5,NaT,NaT,NaT
3,GEODE_T1_1M_REFRACTION_F3004,T1,T1_1m_refraction,3004,82.5,NaT,NaT,NaT
4,GEODE_T1_1M_REFRACTION_F3005,T1,T1_1m_refraction,3005,82.5,2026-05-18 16:03:42.500000+00:00,2026-05-18 16:02:48.500000+00:00,2026-05-18 16:03:47.500000+00:00
5,GEODE_T1_1M_REFRACTION_F3006,T1,T1_1m_refraction,3006,84.5,2026-05-18 16:08:30.500000+00:00,2026-05-18 16:07:36.500000+00:00,2026-05-18 16:08:35.500000+00:00
6,GEODE_T1_1M_REFRACTION_F3007,T1,T1_1m_refraction,3007,86.5,2026-05-18 16:13:29.500000+00:00,2026-05-18 16:12:35.500000+00:00,2026-05-18 16:13:34.500000+00:00
7,GEODE_T1_1M_REFRACTION_F3008,T1,T1_1m_refraction,3008,88.5,2026-05-18 16:18:32.500000+00:00,2026-05-18 16:17:38.500000+00:00,2026-05-18 16:18:37.500000+00:00
8,GEODE_T1_1M_REFRACTION_F3009,T1,T1_1m_refraction,3009,90.5,2026-05-18 16:20:51.500000+00:00,2026-05-18 16:19:57.500000+00:00,2026-05-18 16:20:56.500000+00:00
9,GEODE_T1_1M_REFRACTION_F3010,T1,T1_1m_refraction,3010,92.5,2026-05-18 16:26:23.500000+00:00,2026-05-18 16:25:23.500000+00:00,2026-05-18 16:26:28.500000+00:00

## 8. Main processing loop

This is the expensive cell. Start with `RUN_LABELS = ['T1_N1_Streamer']` and `MAX_EVENTS_PER_WINDOW = 5` if testing.

In [8]:
labels_to_run = list(TIMEWINDOWS.keys()) if RUN_LABELS is None else list(RUN_LABELS)
all_window_catalogs = []

for label in labels_to_run:
    check_free_space(OUT_ROOT, MIN_FREE_GB)
    print("\n" + "="*100)
    print("Processing", label)
    start, end = TIMEWINDOWS[label]
    network, location = parse_label(label)
    geometry_id = f"{label}_{network}_{location}_DPall"

    label_out = OUT_ROOT / label
    (label_out / "tables").mkdir(parents=True, exist_ok=True)

    # 1. Discover all DPZ stations for this network/location after 86_downsample.
    stations = discover_sds_stations(SDS_ROOT, network, location, DETECTION_CHANNEL, EXCLUDE_STATIONS)
    print(f"Discovered {len(stations)} {network}.{location}.{DETECTION_CHANNEL} stations")
    print(stations)
    if len(stations) == 0:
        continue

    # 2. Write receiver geometry to SQLite.
    geom_df = build_geometry_df(label, start, end, stations)
    geom_df.to_sql("receiver_geometry", conn, if_exists="append", index=False)
    geom_df.to_csv(label_out / "tables" / f"{label}_receiver_geometry.csv", index=False)

    # 3. Run chunked DPZ detection.
    raw_det = run_detection_for_window(label, start, end, stations)
    if len(raw_det) == 0:
        print("No detections")
        continue
    raw_path = label_out / "tables" / f"{label}_detected_events_raw_chunked.csv"
    raw_det.to_csv(raw_path, index=False)

    merged_det = merge_detection_catalog(raw_det, tolerance_s=MERGE_TOLERANCE_S, min_spacing_s=MIN_EVENT_SPACING_S)
    merged_path = label_out / "tables" / f"{label}_detected_events_merged.csv"
    merged_det.to_csv(merged_path, index=False)
    print(f"Raw detections: {len(raw_det)}; merged detections: {len(merged_det)}")

    if MAX_EVENTS_PER_WINDOW is not None:
        merged_det = merged_det.iloc[:MAX_EVENTS_PER_WINDOW].copy()

    # 4. For each detection, go back to SDS and extract all DP[ENZ] stations.
    for local_i, row in merged_det.reset_index(drop=True).iterrows():
        event_num = local_i + 1
        event_id = f"{label}_{network}_{location}_E{event_num:05d}"
        gather_id = f"{event_id}_nodal_DPall"
        print(f"\n{event_id}: on_time={row['on_time']}")

        try:
            event_time = UTCDateTime(row["on_time"])
            meta = match_metadata_for_detection(label, event_time)
            source_x_m = meta.get("source_x_m")

            st_event = read_full_gather_from_sds(label, event_time, stations)
            n_receivers = len(stream_stations(st_event))
            n_traces = len(st_event)
            print(f"  extracted {n_traces} traces, {n_receivers} receivers")

            # If extraction fails, still catalog the detected event.
            status = "ok" if len(st_event) else "no_traces_extracted"

            event_row = {
                "run_id": RUN_ID,
                "event_id": event_id,
                "instrument_system": "nodal",
                "line": network,
                "network": network,
                "location": location,
                "timewindow_label": label,
                "geometry_id": geometry_id,
                "detection_time_utc": utc_to_str(row.get("on_time")),
                "on_time_utc": utc_to_str(row.get("on_time")),
                "off_time_utc": utc_to_str(row.get("off_time")),
                "duration_s": float(row.get("duration_s", np.nan)) if pd.notna(row.get("duration_s", np.nan)) else np.nan,
                "source_x_m": source_x_m,
                "source_type": meta.get("source_type"),
                "operator": meta.get("operator"),
                "plate_type": meta.get("plate_type"),
                "n_blows": meta.get("n_blows"),
                "n_shots": meta.get("n_shots"),
                "survey": meta.get("survey"),
                "survey_type": meta.get("survey_type") or "nodal_detection",
                "shot_no": meta.get("shot_no"),
                "file_no": meta.get("file_no"),
                "matched_metadata_event_id": meta.get("matched_metadata_event_id"),
                "metadata_match_status": meta.get("metadata_match_status", "unmatched_detection"),
                "metadata_match_time_error_s": meta.get("metadata_match_time_error_s"),
                "detection_n_seed_ids": int(row.get("n_seed_ids", 0) or 0),
                "detection_n_stations": int(row.get("n_stations", 0) or 0) if "n_stations" in row else None,
                "detection_seed_ids": str(row.get("seed_ids", "")),
                "detection_stations": str(row.get("stations", "")),
                "snr_rms": float(row.get("snr_rms", np.nan)) if pd.notna(row.get("snr_rms", np.nan)) else np.nan,
                "n_receivers_extracted": n_receivers,
                "n_traces_extracted": n_traces,
                "status": status,
                "notes": meta.get("notes"),
            }
            pd.DataFrame([event_row]).to_sql("shot_events", conn, if_exists="append", index=False)

            if len(st_event) == 0:
                conn.commit()
                continue

            file_rows, trace_rows = write_component_products(st_event, label, event_id, gather_id, source_x_m)
            if file_rows:
                pd.DataFrame(file_rows).to_sql("shot_gather_files", conn, if_exists="append", index=False)
            if trace_rows:
                pd.DataFrame(trace_rows).to_sql("trace_index", conn, if_exists="append", index=False)

            picks_df = pick_event_stream(st_event, event_id, gather_id, source_x_m)
            if len(picks_df):
                pd.DataFrame(picks_df).to_sql("picks", conn, if_exists="append", index=False)
                picks_out = label_out / "tables" / "picks"
                picks_out.mkdir(parents=True, exist_ok=True)
                picks_df.to_csv(picks_out / f"{event_id}_picks.csv", index=False)

            conn.commit()
        except Exception as e:
            print("  FAILED:", e)
            log_error(conn, "event_processing", label=label, event_id=event_id, exc=e)
            continue

print("Done. Catalog:", CATALOG_DB)

====================================================================================================
Processing T1_N1_Streamer
Discovered 35 T1.N1.DPZ stations
['02800', '03600', '04400', '05207', '06004', '06809', '07600', '08003', '08405', '08808', '09210', '09605', '10000', '10398', '10800', '11202', '11600', '12005', '12402', '12801', '13202', '13605', '14000', '14400', '14800', '15195', '16000', '16400', '16809', '17604', '18405', '19200', '20000', '20800', '21600']
T1_N1_Streamer chunk 0: 2026-05-16T17:13:00.000000Z to 2026-05-16T17:14:00.000000Z
  read 15 traces, 15 stations
  detections: 8
T1_N1_Streamer chunk 1: 2026-05-16T17:14:00.000000Z to 2026-05-16T17:15:00.000000Z
  read 15 traces, 15 stations
  detections: 3
T1_N1_Streamer chunk 2: 2026-05-16T17:15:00.000000Z to 2026-05-16T17:16:00.000000Z
  read 15 traces, 15 stations
  detections: 2
T1_N1_Streamer chunk 3: 2026-05-16T17:16:00.000000Z to 2026-05-16T17:17:00.000000Z
  read 15 traces, 15 stations
  detections: 4
T1_N1_Streamer chunk 4: 2026-05-16T17:17:00.000000Z to 2026-05-16T17:18:00.000000Z
  read 15 traces, 15 stations
  detections: 13
T1_N1_Streamer chunk 5: 2026-05-16T17:18:00.000000Z to 2026-05-16T17:19:00.000000Z
  read 15 traces, 15 stations
  detections: 11
T1_N1_Streamer chunk 6: 2026-05-16T17:19:00.000000Z to 2026-05-16T17:20:00.000000Z
  read 16 traces, 16 stations
  detections: 18
T1_N1_Streamer chunk 7: 2026-05-16T17:20:00.000000Z to 2026-05-16T17:21:00.000000Z
  read 16 traces, 16 stations
  detections: 10
T1_N1_Streamer chunk 8: 2026-05-16T17:21:00.000000Z to 2026-05-16T17:22:00.000000Z
  read 16 traces, 16 stations
  detections: 8
T1_N1_Streamer chunk 9: 2026-05-16T17:22:00.000000Z to 2026-05-16T17:23:00.000000Z
  read 17 traces, 17 stations
  detections: 1
T1_N1_Streamer chunk 10: 2026-05-16T17:23:00.000000Z to 2026-05-16T17:24:00.000000Z
  read 17 traces, 17 stations
T1_N1_Streamer chunk 11: 2026-05-16T17:24:00.000000Z to 2026-05-16T17:25:00.000000Z
  read 17 traces, 17 stations
T1_N1_Streamer chunk 12: 2026-05-16T17:25:00.000000Z to 2026-05-16T17:26:00.000000Z
  read 17 traces, 17 stations
T1_N1_Streamer chunk 13: 2026-05-16T17:26:00.000000Z to 2026-05-16T17:27:00.000000Z
  read 17 traces, 17 stations
T1_N1_Streamer chunk 14: 2026-05-16T17:27:00.000000Z to 2026-05-16T17:28:00.000000Z
  read 17 traces, 17 stations
T1_N1_Streamer chunk 15: 2026-05-16T17:28:00.000000Z to 2026-05-16T17:29:00.000000Z
  read 18 traces, 18 stations
  detections: 11
T1_N1_Streamer chunk 16: 2026-05-16T17:29:00.000000Z to 2026-05-16T17:30:00.000000Z
  read 18 traces, 18 stations
  detections: 5
T1_N1_Streamer chunk 17: 2026-05-16T17:30:00.000000Z to 2026-05-16T17:31:00.000000Z
  read 18 traces, 18 stations
T1_N1_Streamer chunk 18: 2026-05-16T17:31:00.000000Z to 2026-05-16T17:32:00.000000Z
  read 18 traces, 18 stations
  detections: 6
T1_N1_Streamer chunk 19: 2026-05-16T17:32:00.000000Z to 2026-05-16T17:33:00.000000Z
  read 18 traces, 18 stations
T1_N1_Streamer chunk 20: 2026-05-16T17:33:00.000000Z to 2026-05-16T17:34:00.000000Z
  read 19 traces, 19 stations
  detections: 9
T1_N1_Streamer chunk 21: 2026-05-16T17:34:00.000000Z to 2026-05-16T17:35:00.000000Z
  read 19 traces, 19 stations
  detections: 10
T1_N1_Streamer chunk 22: 2026-05-16T17:35:00.000000Z to 2026-05-16T17:36:00.000000Z
  read 19 traces, 19 stations
T1_N1_Streamer chunk 23: 2026-05-16T17:36:00.000000Z to 2026-05-16T17:37:00.000000Z
  read 19 traces, 19 stations
  detections: 11
T1_N1_Streamer chunk 24: 2026-05-16T17:37:00.000000Z to 2026-05-16T17:38:00.000000Z
  read 19 traces, 19 stations
T1_N1_Streamer chunk 25: 2026-05-16T17:38:00.000000Z to 2026-05-16T17:39:00.000000Z
  read 19 traces, 19 stations
T1_N1_Streamer chunk 26: 2026-05-16T17:39:00.000000Z to 2026-05-16T17:40:00.000000Z
  read 19 traces, 19 stations
T1_N1_Streamer chunk 27: 2026-05-16T17:40:00.000000Z to 2026-05-16T17:41:00.000000Z
  read 19 traces, 19 stations
  detections: 1
T1_N1_Streamer chunk 28: 2026-05-16T17:41:00.000000Z to 2026-05-16T17:42:00.000000Z
  read 20 traces, 20 stations
T1_N1_Streamer chunk 29: 2026-05-16T17:42:00.000000Z to 2026-05-16T17:43:00.000000Z
  read 20 traces, 20 stations
  detections: 8
T1_N1_Streamer chunk 30: 2026-05-16T17:43:00.000000Z to 2026-05-16T17:44:00.000000Z
  read 20 traces, 20 stations
  detections: 5
T1_N1_Streamer chunk 31: 2026-05-16T17:44:00.000000Z to 2026-05-16T17:45:00.000000Z
  read 20 traces, 20 stations
T1_N1_Streamer chunk 32: 2026-05-16T17:45:00.000000Z to 2026-05-16T17:46:00.000000Z
  read 20 traces, 20 stations
T1_N1_Streamer chunk 33: 2026-05-16T17:46:00.000000Z to 2026-05-16T17:47:00.000000Z
  read 20 traces, 20 stations
T1_N1_Streamer chunk 34: 2026-05-16T17:47:00.000000Z to 2026-05-16T17:48:00.000000Z
  read 20 traces, 20 stations
T1_N1_Streamer chunk 35: 2026-05-16T17:48:00.000000Z to 2026-05-16T17:49:00.000000Z
  read 20 traces, 20 stations
T1_N1_Streamer chunk 36: 2026-05-16T17:49:00.000000Z to 2026-05-16T17:50:00.000000Z
  read 21 traces, 21 stations
T1_N1_Streamer chunk 37: 2026-05-16T17:50:00.000000Z to 2026-05-16T17:51:00.000000Z
  read 24 traces, 24 stations
  detections: 1
T1_N1_Streamer chunk 38: 2026-05-16T17:51:00.000000Z to 2026-05-16T17:52:00.000000Z
  read 26 traces, 26 stations
T1_N1_Streamer chunk 39: 2026-05-16T17:52:00.000000Z to 2026-05-16T17:53:00.000000Z
  read 26 traces, 26 stations
T1_N1_Streamer chunk 40: 2026-05-16T17:53:00.000000Z to 2026-05-16T17:54:00.000000Z
  read 27 traces, 27 stations
T1_N1_Streamer chunk 41: 2026-05-16T17:54:00.000000Z to 2026-05-16T17:55:00.000000Z
  read 27 traces, 27 stations
T1_N1_Streamer chunk 42: 2026-05-16T17:55:00.000000Z to 2026-05-16T17:56:00.000000Z
  read 28 traces, 28 stations
T1_N1_Streamer chunk 43: 2026-05-16T17:56:00.000000Z to 2026-05-16T17:57:00.000000Z
  read 29 traces, 29 stations
T1_N1_Streamer chunk 44: 2026-05-16T17:57:00.000000Z to 2026-05-16T17:58:00.000000Z
  read 29 traces, 29 stations
  detections: 1
T1_N1_Streamer chunk 45: 2026-05-16T17:58:00.000000Z to 2026-05-16T17:59:00.000000Z
  read 29 traces, 29 stations
  detections: 2
T1_N1_Streamer chunk 46: 2026-05-16T17:59:00.000000Z to 2026-05-16T18:00:00.000000Z
  read 29 traces, 29 stations
T1_N1_Streamer chunk 47: 2026-05-16T18:00:00.000000Z to 2026-05-16T18:01:00.000000Z
  read 29 traces, 29 stations
T1_N1_Streamer chunk 48: 2026-05-16T18:01:00.000000Z to 2026-05-16T18:02:00.000000Z
  read 30 traces, 30 stations
T1_N1_Streamer chunk 49: 2026-05-16T18:02:00.000000Z to 2026-05-16T18:03:00.000000Z
  read 30 traces, 30 stations
T1_N1_Streamer chunk 50: 2026-05-16T18:03:00.000000Z to 2026-05-16T18:04:00.000000Z
  read 34 traces, 34 stations
T1_N1_Streamer chunk 51: 2026-05-16T18:04:00.000000Z to 2026-05-16T18:05:00.000000Z
  read 34 traces, 34 stations
T1_N1_Streamer chunk 52: 2026-05-16T18:05:00.000000Z to 2026-05-16T18:06:00.000000Z
  read 34 traces, 34 stations
T1_N1_Streamer chunk 53: 2026-05-16T18:06:00.000000Z to 2026-05-16T18:07:00.000000Z
  read 34 traces, 34 stations
T1_N1_Streamer chunk 54: 2026-05-16T18:07:00.000000Z to 2026-05-16T18:08:00.000000Z
  read 34 traces, 34 stations
T1_N1_Streamer chunk 55: 2026-05-16T18:08:00.000000Z to 2026-05-16T18:09:00.000000Z
  read 34 traces, 34 stations
T1_N1_Streamer chunk 56: 2026-05-16T18:09:00.000000Z to 2026-05-16T18:10:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 57: 2026-05-16T18:10:00.000000Z to 2026-05-16T18:11:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 58: 2026-05-16T18:11:00.000000Z to 2026-05-16T18:12:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 59: 2026-05-16T18:12:00.000000Z to 2026-05-16T18:13:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 60: 2026-05-16T18:13:00.000000Z to 2026-05-16T18:14:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 61: 2026-05-16T18:14:00.000000Z to 2026-05-16T18:15:00.000000Z
  read 35 traces, 35 stations
  detections: 11
T1_N1_Streamer chunk 62: 2026-05-16T18:15:00.000000Z to 2026-05-16T18:16:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T1_N1_Streamer chunk 63: 2026-05-16T18:16:00.000000Z to 2026-05-16T18:17:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 64: 2026-05-16T18:17:00.000000Z to 2026-05-16T18:18:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 65: 2026-05-16T18:18:00.000000Z to 2026-05-16T18:19:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T1_N1_Streamer chunk 66: 2026-05-16T18:19:00.000000Z to 2026-05-16T18:20:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 67: 2026-05-16T18:20:00.000000Z to 2026-05-16T18:21:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 68: 2026-05-16T18:21:00.000000Z to 2026-05-16T18:22:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 69: 2026-05-16T18:22:00.000000Z to 2026-05-16T18:23:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 70: 2026-05-16T18:23:00.000000Z to 2026-05-16T18:24:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 71: 2026-05-16T18:24:00.000000Z to 2026-05-16T18:25:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 72: 2026-05-16T18:25:00.000000Z to 2026-05-16T18:26:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 73: 2026-05-16T18:26:00.000000Z to 2026-05-16T18:27:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 74: 2026-05-16T18:27:00.000000Z to 2026-05-16T18:28:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 75: 2026-05-16T18:28:00.000000Z to 2026-05-16T18:29:00.000000Z
  read 35 traces, 35 stations
  detections: 8
T1_N1_Streamer chunk 76: 2026-05-16T18:29:00.000000Z to 2026-05-16T18:30:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 77: 2026-05-16T18:30:00.000000Z to 2026-05-16T18:31:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 78: 2026-05-16T18:31:00.000000Z to 2026-05-16T18:32:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 79: 2026-05-16T18:32:00.000000Z to 2026-05-16T18:33:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 80: 2026-05-16T18:33:00.000000Z to 2026-05-16T18:34:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T1_N1_Streamer chunk 81: 2026-05-16T18:34:00.000000Z to 2026-05-16T18:35:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 82: 2026-05-16T18:35:00.000000Z to 2026-05-16T18:36:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 83: 2026-05-16T18:36:00.000000Z to 2026-05-16T18:37:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 84: 2026-05-16T18:37:00.000000Z to 2026-05-16T18:38:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 85: 2026-05-16T18:38:00.000000Z to 2026-05-16T18:39:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 86: 2026-05-16T18:39:00.000000Z to 2026-05-16T18:40:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 87: 2026-05-16T18:40:00.000000Z to 2026-05-16T18:41:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 88: 2026-05-16T18:41:00.000000Z to 2026-05-16T18:42:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 89: 2026-05-16T18:42:00.000000Z to 2026-05-16T18:43:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 90: 2026-05-16T18:43:00.000000Z to 2026-05-16T18:44:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 91: 2026-05-16T18:44:00.000000Z to 2026-05-16T18:45:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 92: 2026-05-16T18:45:00.000000Z to 2026-05-16T18:46:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 93: 2026-05-16T18:46:00.000000Z to 2026-05-16T18:47:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 94: 2026-05-16T18:47:00.000000Z to 2026-05-16T18:48:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T1_N1_Streamer chunk 95: 2026-05-16T18:48:00.000000Z to 2026-05-16T18:49:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 96: 2026-05-16T18:49:00.000000Z to 2026-05-16T18:50:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 97: 2026-05-16T18:50:00.000000Z to 2026-05-16T18:51:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T1_N1_Streamer chunk 98: 2026-05-16T18:51:00.000000Z to 2026-05-16T18:52:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 99: 2026-05-16T18:52:00.000000Z to 2026-05-16T18:53:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 100: 2026-05-16T18:53:00.000000Z to 2026-05-16T18:54:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 101: 2026-05-16T18:54:00.000000Z to 2026-05-16T18:55:00.000000Z
  read 35 traces, 35 stations
  detections: 11
T1_N1_Streamer chunk 102: 2026-05-16T18:55:00.000000Z to 2026-05-16T18:56:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 103: 2026-05-16T18:56:00.000000Z to 2026-05-16T18:57:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 104: 2026-05-16T18:57:00.000000Z to 2026-05-16T18:58:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T1_N1_Streamer chunk 105: 2026-05-16T18:58:00.000000Z to 2026-05-16T18:59:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 106: 2026-05-16T18:59:00.000000Z to 2026-05-16T19:00:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 107: 2026-05-16T19:00:00.000000Z to 2026-05-16T19:01:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T1_N1_Streamer chunk 108: 2026-05-16T19:01:00.000000Z to 2026-05-16T19:02:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 109: 2026-05-16T19:02:00.000000Z to 2026-05-16T19:03:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 110: 2026-05-16T19:03:00.000000Z to 2026-05-16T19:04:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 111: 2026-05-16T19:04:00.000000Z to 2026-05-16T19:05:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 112: 2026-05-16T19:05:00.000000Z to 2026-05-16T19:06:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 113: 2026-05-16T19:06:00.000000Z to 2026-05-16T19:07:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 114: 2026-05-16T19:07:00.000000Z to 2026-05-16T19:08:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 115: 2026-05-16T19:08:00.000000Z to 2026-05-16T19:09:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 116: 2026-05-16T19:09:00.000000Z to 2026-05-16T19:10:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T1_N1_Streamer chunk 117: 2026-05-16T19:10:00.000000Z to 2026-05-16T19:11:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 118: 2026-05-16T19:11:00.000000Z to 2026-05-16T19:12:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 119: 2026-05-16T19:12:00.000000Z to 2026-05-16T19:13:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 120: 2026-05-16T19:13:00.000000Z to 2026-05-16T19:14:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 121: 2026-05-16T19:14:00.000000Z to 2026-05-16T19:15:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 122: 2026-05-16T19:15:00.000000Z to 2026-05-16T19:16:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 123: 2026-05-16T19:16:00.000000Z to 2026-05-16T19:17:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 124: 2026-05-16T19:17:00.000000Z to 2026-05-16T19:18:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 125: 2026-05-16T19:18:00.000000Z to 2026-05-16T19:19:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 126: 2026-05-16T19:19:00.000000Z to 2026-05-16T19:20:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 127: 2026-05-16T19:20:00.000000Z to 2026-05-16T19:21:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 128: 2026-05-16T19:21:00.000000Z to 2026-05-16T19:22:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 129: 2026-05-16T19:22:00.000000Z to 2026-05-16T19:23:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 130: 2026-05-16T19:23:00.000000Z to 2026-05-16T19:24:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 131: 2026-05-16T19:24:00.000000Z to 2026-05-16T19:25:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 132: 2026-05-16T19:25:00.000000Z to 2026-05-16T19:26:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 133: 2026-05-16T19:26:00.000000Z to 2026-05-16T19:27:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 134: 2026-05-16T19:27:00.000000Z to 2026-05-16T19:28:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T1_N1_Streamer chunk 135: 2026-05-16T19:28:00.000000Z to 2026-05-16T19:29:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 136: 2026-05-16T19:29:00.000000Z to 2026-05-16T19:30:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 137: 2026-05-16T19:30:00.000000Z to 2026-05-16T19:31:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T1_N1_Streamer chunk 138: 2026-05-16T19:31:00.000000Z to 2026-05-16T19:32:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 139: 2026-05-16T19:32:00.000000Z to 2026-05-16T19:33:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 140: 2026-05-16T19:33:00.000000Z to 2026-05-16T19:34:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 141: 2026-05-16T19:34:00.000000Z to 2026-05-16T19:35:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 142: 2026-05-16T19:35:00.000000Z to 2026-05-16T19:36:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T1_N1_Streamer chunk 143: 2026-05-16T19:36:00.000000Z to 2026-05-16T19:37:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 144: 2026-05-16T19:37:00.000000Z to 2026-05-16T19:38:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T1_N1_Streamer chunk 145: 2026-05-16T19:38:00.000000Z to 2026-05-16T19:39:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 146: 2026-05-16T19:39:00.000000Z to 2026-05-16T19:40:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 147: 2026-05-16T19:40:00.000000Z to 2026-05-16T19:41:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 148: 2026-05-16T19:41:00.000000Z to 2026-05-16T19:42:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T1_N1_Streamer chunk 149: 2026-05-16T19:42:00.000000Z to 2026-05-16T19:43:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T1_N1_Streamer chunk 150: 2026-05-16T19:43:00.000000Z to 2026-05-16T19:44:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 151: 2026-05-16T19:44:00.000000Z to 2026-05-16T19:45:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 152: 2026-05-16T19:45:00.000000Z to 2026-05-16T19:46:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 153: 2026-05-16T19:46:00.000000Z to 2026-05-16T19:47:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 154: 2026-05-16T19:47:00.000000Z to 2026-05-16T19:48:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 155: 2026-05-16T19:48:00.000000Z to 2026-05-16T19:49:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 156: 2026-05-16T19:49:00.000000Z to 2026-05-16T19:50:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N1_Streamer chunk 157: 2026-05-16T19:50:00.000000Z to 2026-05-16T19:51:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T1_N1_Streamer chunk 158: 2026-05-16T19:51:00.000000Z to 2026-05-16T19:52:00.000000Z
  read 35 traces, 35 stations
T1_N1_Streamer chunk 159: 2026-05-16T19:52:00.000000Z to 2026-05-16T19:53:00.000000Z
  read 35 traces, 35 stations

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00003: on_time=2026-05-16 17:13:28.030000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00004: on_time=2026-05-16 17:13:30.858000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00005: on_time=2026-05-16 17:13:33.392000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00006: on_time=2026-05-16 17:13:39.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00007: on_time=2026-05-16 17:13:40.966000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00008: on_time=2026-05-16 17:13:41.596000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00009: on_time=2026-05-16 17:14:12.590000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00010: on_time=2026-05-16 17:14:44.884000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00011: on_time=2026-05-16 17:14:48.444000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00012: on_time=2026-05-16 17:15:25.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00013: on_time=2026-05-16 17:15:25.994000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00014: on_time=2026-05-16 17:16:38.030000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00015: on_time=2026-05-16 17:16:41.188000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00016: on_time=2026-05-16 17:16:55.810000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00017: on_time=2026-05-16 17:16:58.984000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00018: on_time=2026-05-16 17:17:02.278000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00019: on_time=2026-05-16 17:17:03.758000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00020: on_time=2026-05-16 17:17:12.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00021: on_time=2026-05-16 17:17:15.548000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00022: on_time=2026-05-16 17:17:23.862000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00023: on_time=2026-05-16 17:17:31.922000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00024: on_time=2026-05-16 17:17:35.388000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00025: on_time=2026-05-16 17:17:38.908000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00026: on_time=2026-05-16 17:17:42.164000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00027: on_time=2026-05-16 17:17:47.328000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00028: on_time=2026-05-16 17:17:49.942000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00029: on_time=2026-05-16 17:17:51.498000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00030: on_time=2026-05-16 17:18:00.372000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00031: on_time=2026-05-16 17:18:01.814000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00032: on_time=2026-05-16 17:18:13.404000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00033: on_time=2026-05-16 17:18:48.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00034: on_time=2026-05-16 17:18:49.594000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00035: on_time=2026-05-16 17:18:50.210000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00036: on_time=2026-05-16 17:18:51.002000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00037: on_time=2026-05-16 17:18:52.312000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00038: on_time=2026-05-16 17:18:53.040000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00039: on_time=2026-05-16 17:18:54.366000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00040: on_time=2026-05-16 17:19:01.634000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00041: on_time=2026-05-16 17:19:04.796000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00042: on_time=2026-05-16 17:19:08.708000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00043: on_time=2026-05-16 17:19:10.802000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 45 traces, 15 receivers

T1_N1_Streamer_T1_N1_E00044: on_time=2026-05-16 17:19:12.292000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00045: on_time=2026-05-16 17:19:40.278000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00046: on_time=2026-05-16 17:19:41.498000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00047: on_time=2026-05-16 17:19:42.084000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00048: on_time=2026-05-16 17:19:42.662000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00049: on_time=2026-05-16 17:19:43.260000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00050: on_time=2026-05-16 17:19:43.904000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00051: on_time=2026-05-16 17:19:46.432000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00052: on_time=2026-05-16 17:19:47.040000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00053: on_time=2026-05-16 17:19:50.166000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00054: on_time=2026-05-16 17:19:50.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00055: on_time=2026-05-16 17:19:52.070000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00056: on_time=2026-05-16 17:19:52.694000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00057: on_time=2026-05-16 17:19:59.906000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00058: on_time=2026-05-16 17:20:02.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00059: on_time=2026-05-16 17:20:03.604000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00060: on_time=2026-05-16 17:20:21.042000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00061: on_time=2026-05-16 17:20:23.532000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00062: on_time=2026-05-16 17:20:26.376000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00063: on_time=2026-05-16 17:20:36.346000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00064: on_time=2026-05-16 17:20:47.716000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00065: on_time=2026-05-16 17:20:51.436000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00066: on_time=2026-05-16 17:20:54.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00067: on_time=2026-05-16 17:20:58.026000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00068: on_time=2026-05-16 17:21:05.606000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00069: on_time=2026-05-16 17:21:08.588000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00070: on_time=2026-05-16 17:21:12.138000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00071: on_time=2026-05-16 17:21:14.688000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00072: on_time=2026-05-16 17:21:18.636000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00073: on_time=2026-05-16 17:21:22.420000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00074: on_time=2026-05-16 17:21:26.482000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00075: on_time=2026-05-16 17:21:29.248000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00076: on_time=2026-05-16 17:22:19.400000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 48 traces, 16 receivers

T1_N1_Streamer_T1_N1_E00077: on_time=2026-05-16 17:28:40.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00078: on_time=2026-05-16 17:28:42.998000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00079: on_time=2026-05-16 17:28:43.660000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00080: on_time=2026-05-16 17:28:44.336000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00081: on_time=2026-05-16 17:28:45.684000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00082: on_time=2026-05-16 17:28:46.338000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00083: on_time=2026-05-16 17:28:47.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00084: on_time=2026-05-16 17:28:49.758000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00085: on_time=2026-05-16 17:28:50.362000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00086: on_time=2026-05-16 17:28:55.266000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00087: on_time=2026-05-16 17:28:59.330000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00088: on_time=2026-05-16 17:29:03.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00089: on_time=2026-05-16 17:29:05.120000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00090: on_time=2026-05-16 17:29:08.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00091: on_time=2026-05-16 17:29:09.586000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00092: on_time=2026-05-16 17:29:23.938000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00093: on_time=2026-05-16 17:31:34.950000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00094: on_time=2026-05-16 17:31:36.858000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00095: on_time=2026-05-16 17:31:39.374000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00096: on_time=2026-05-16 17:31:39.962000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00097: on_time=2026-05-16 17:31:42.186000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00098: on_time=2026-05-16 17:31:48.946000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00099: on_time=2026-05-16 17:33:35.980000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00100: on_time=2026-05-16 17:33:38.180000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00101: on_time=2026-05-16 17:33:38.896000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00102: on_time=2026-05-16 17:33:39.552000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00103: on_time=2026-05-16 17:33:48.638000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00104: on_time=2026-05-16 17:33:52.294000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00105: on_time=2026-05-16 17:33:54.914000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00106: on_time=2026-05-16 17:33:58.196000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 54 traces, 18 receivers

T1_N1_Streamer_T1_N1_E00107: on_time=2026-05-16 17:33:59.434000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00108: on_time=2026-05-16 17:34:03.862000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00109: on_time=2026-05-16 17:34:07.744000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00110: on_time=2026-05-16 17:34:08.900000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00111: on_time=2026-05-16 17:34:13.926000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00112: on_time=2026-05-16 17:34:16.856000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00113: on_time=2026-05-16 17:34:17.510000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00114: on_time=2026-05-16 17:34:26.432000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00115: on_time=2026-05-16 17:34:35.802000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00116: on_time=2026-05-16 17:34:48.592000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00117: on_time=2026-05-16 17:34:52.180000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00118: on_time=2026-05-16 17:36:00.034000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00119: on_time=2026-05-16 17:36:04.582000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00120: on_time=2026-05-16 17:36:08.974000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00121: on_time=2026-05-16 17:36:12.720000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00122: on_time=2026-05-16 17:36:26.298000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00123: on_time=2026-05-16 17:36:29.510000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00124: on_time=2026-05-16 17:36:39.348000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00125: on_time=2026-05-16 17:40:45.180000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 57 traces, 19 receivers

T1_N1_Streamer_T1_N1_E00126: on_time=2026-05-16 17:42:34.082000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00127: on_time=2026-05-16 17:42:36.070000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00128: on_time=2026-05-16 17:42:38.148000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00129: on_time=2026-05-16 17:42:40.054000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00130: on_time=2026-05-16 17:42:41.914000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00131: on_time=2026-05-16 17:42:43.968000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00132: on_time=2026-05-16 17:43:25.404000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00133: on_time=2026-05-16 17:43:31.994000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00134: on_time=2026-05-16 17:43:33.224000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00135: on_time=2026-05-16 17:43:38.262000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00136: on_time=2026-05-16 17:43:46.876000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 60 traces, 20 receivers

T1_N1_Streamer_T1_N1_E00137: on_time=2026-05-16 17:50:55.854000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 69 traces, 23 receivers

T1_N1_Streamer_T1_N1_E00138: on_time=2026-05-16 17:57:38.262000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N1_Streamer_T1_N1_E00139: on_time=2026-05-16 17:58:18.200000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N1_Streamer_T1_N1_E00140: on_time=2026-05-16 17:58:49.356000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N1_Streamer_T1_N1_E00141: on_time=2026-05-16 18:14:01.456000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00142: on_time=2026-05-16 18:14:01.840000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00143: on_time=2026-05-16 18:14:16.318000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00144: on_time=2026-05-16 18:14:16.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00145: on_time=2026-05-16 18:14:24.680000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00146: on_time=2026-05-16 18:15:20.264000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00147: on_time=2026-05-16 18:18:39.182000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00148: on_time=2026-05-16 18:18:48.742000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00149: on_time=2026-05-16 18:18:57.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00150: on_time=2026-05-16 18:19:11.090000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00151: on_time=2026-05-16 18:21:49.272000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00152: on_time=2026-05-16 18:22:06.672000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00153: on_time=2026-05-16 18:22:28.262000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00154: on_time=2026-05-16 18:22:45.630000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00155: on_time=2026-05-16 18:26:11.748000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00156: on_time=2026-05-16 18:26:20.846000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00157: on_time=2026-05-16 18:26:28.944000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00158: on_time=2026-05-16 18:28:40.456000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00159: on_time=2026-05-16 18:28:40.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00160: on_time=2026-05-16 18:28:49.526000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00161: on_time=2026-05-16 18:28:49.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00162: on_time=2026-05-16 18:28:56.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00163: on_time=2026-05-16 18:33:09.986000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00164: on_time=2026-05-16 18:33:13.872000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00165: on_time=2026-05-16 18:33:24.154000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00166: on_time=2026-05-16 18:33:36.056000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00167: on_time=2026-05-16 18:33:49.514000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00168: on_time=2026-05-16 18:37:42.688000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00169: on_time=2026-05-16 18:37:57.094000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00170: on_time=2026-05-16 18:38:07.922000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00171: on_time=2026-05-16 18:40:38.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00172: on_time=2026-05-16 18:40:45.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00173: on_time=2026-05-16 18:40:53.316000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00174: on_time=2026-05-16 18:43:55.382000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00175: on_time=2026-05-16 18:44:03.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00176: on_time=2026-05-16 18:44:10.302000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00177: on_time=2026-05-16 18:47:20.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00178: on_time=2026-05-16 18:47:20.936000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00179: on_time=2026-05-16 18:47:30.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00180: on_time=2026-05-16 18:47:31.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00181: on_time=2026-05-16 18:47:40.998000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00182: on_time=2026-05-16 18:47:41.294000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00183: on_time=2026-05-16 18:50:18.830000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00184: on_time=2026-05-16 18:50:19.112000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00185: on_time=2026-05-16 18:50:30.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00186: on_time=2026-05-16 18:50:41.570000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00187: on_time=2026-05-16 18:50:50.772000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00188: on_time=2026-05-16 18:54:19.328000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00189: on_time=2026-05-16 18:54:19.602000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00190: on_time=2026-05-16 18:54:30.850000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00191: on_time=2026-05-16 18:54:31.050000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00192: on_time=2026-05-16 18:54:39.854000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00193: on_time=2026-05-16 18:57:15.426000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00194: on_time=2026-05-16 18:57:26.072000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00195: on_time=2026-05-16 18:57:35.740000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00196: on_time=2026-05-16 19:00:23.396000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00197: on_time=2026-05-16 19:00:32.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00198: on_time=2026-05-16 19:00:39.134000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00199: on_time=2026-05-16 19:02:44.304000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00200: on_time=2026-05-16 19:02:52.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00201: on_time=2026-05-16 19:02:59.784000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00202: on_time=2026-05-16 19:03:13.176000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00203: on_time=2026-05-16 19:04:49.226000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00204: on_time=2026-05-16 19:04:59.866000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00205: on_time=2026-05-16 19:05:55.692000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00206: on_time=2026-05-16 19:06:04.932000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00207: on_time=2026-05-16 19:07:59.740000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00208: on_time=2026-05-16 19:08:54.636000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00209: on_time=2026-05-16 19:08:57.698000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00210: on_time=2026-05-16 19:09:10.786000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00211: on_time=2026-05-16 19:09:25.290000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00212: on_time=2026-05-16 19:09:40.592000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00213: on_time=2026-05-16 19:09:52.706000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00214: on_time=2026-05-16 19:11:30.398000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00215: on_time=2026-05-16 19:11:40.718000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00216: on_time=2026-05-16 19:11:51.400000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00217: on_time=2026-05-16 19:12:01.314000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00218: on_time=2026-05-16 19:13:51.066000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00219: on_time=2026-05-16 19:15:09.718000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00220: on_time=2026-05-16 19:15:19.934000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00221: on_time=2026-05-16 19:15:29.450000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00222: on_time=2026-05-16 19:18:26.492000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00223: on_time=2026-05-16 19:18:40.946000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00224: on_time=2026-05-16 19:18:51.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00225: on_time=2026-05-16 19:19:11.480000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00226: on_time=2026-05-16 19:20:55.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00227: on_time=2026-05-16 19:27:14.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00228: on_time=2026-05-16 19:27:27.162000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00229: on_time=2026-05-16 19:27:38.162000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00230: on_time=2026-05-16 19:29:36.072000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00231: on_time=2026-05-16 19:29:36.416000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00232: on_time=2026-05-16 19:30:36.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00233: on_time=2026-05-16 19:30:47.130000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00234: on_time=2026-05-16 19:30:54.730000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00235: on_time=2026-05-16 19:31:48.854000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00236: on_time=2026-05-16 19:32:03.562000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00237: on_time=2026-05-16 19:32:03.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00238: on_time=2026-05-16 19:32:57.394000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00239: on_time=2026-05-16 19:33:27.396000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00240: on_time=2026-05-16 19:33:39.312000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00241: on_time=2026-05-16 19:33:49.870000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00242: on_time=2026-05-16 19:35:15.062000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00243: on_time=2026-05-16 19:35:28.922000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00244: on_time=2026-05-16 19:35:36.946000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00245: on_time=2026-05-16 19:35:37.148000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00246: on_time=2026-05-16 19:37:19.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00247: on_time=2026-05-16 19:37:28.700000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00248: on_time=2026-05-16 19:37:37.374000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00249: on_time=2026-05-16 19:37:37.606000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00250: on_time=2026-05-16 19:37:45.832000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00251: on_time=2026-05-16 19:40:10.334000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00252: on_time=2026-05-16 19:41:39.758000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00253: on_time=2026-05-16 19:42:10.028000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00254: on_time=2026-05-16 19:42:20.186000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00255: on_time=2026-05-16 19:42:34.628000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00256: on_time=2026-05-16 19:44:54.504000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00257: on_time=2026-05-16 19:44:54.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00258: on_time=2026-05-16 19:45:08.470000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00259: on_time=2026-05-16 19:45:25.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00260: on_time=2026-05-16 19:46:48.962000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00261: on_time=2026-05-16 19:46:57.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00262: on_time=2026-05-16 19:47:06.356000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00263: on_time=2026-05-16 19:47:15.432000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00264: on_time=2026-05-16 19:48:27.104000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00265: on_time=2026-05-16 19:48:46.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00266: on_time=2026-05-16 19:48:59.960000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00267: on_time=2026-05-16 19:49:10.292000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00268: on_time=2026-05-16 19:49:23.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00269: on_time=2026-05-16 19:50:36.552000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00270: on_time=2026-05-16 19:50:46.736000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00271: on_time=2026-05-16 19:50:53.668000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00272: on_time=2026-05-16 19:53:10.842000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00273: on_time=2026-05-16 19:53:29.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00274: on_time=2026-05-16 19:53:40.656000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00275: on_time=2026-05-16 19:53:51.496000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00276: on_time=2026-05-16 19:55:53.478000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00277: on_time=2026-05-16 19:55:53.968000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00278: on_time=2026-05-16 19:56:03.328000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00279: on_time=2026-05-16 19:56:12.240000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00280: on_time=2026-05-16 19:56:24.742000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00281: on_time=2026-05-16 19:58:23.416000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00282: on_time=2026-05-16 19:58:23.858000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00283: on_time=2026-05-16 19:59:00.158000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00284: on_time=2026-05-16 19:59:14.736000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00285: on_time=2026-05-16 19:59:27.666000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00286: on_time=2026-05-16 20:01:19.876000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00287: on_time=2026-05-16 20:01:31.832000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00288: on_time=2026-05-16 20:01:49.694000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00289: on_time=2026-05-16 20:02:09.632000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00290: on_time=2026-05-16 20:03:53.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00291: on_time=2026-05-16 20:04:09.544000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00292: on_time=2026-05-16 20:04:49.676000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00293: on_time=2026-05-16 20:04:49.926000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00294: on_time=2026-05-16 20:05:02.342000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00295: on_time=2026-05-16 20:07:40.264000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00296: on_time=2026-05-16 20:08:17.630000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00297: on_time=2026-05-16 20:08:29.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00298: on_time=2026-05-16 20:08:38.710000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00299: on_time=2026-05-16 20:08:48.148000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00300: on_time=2026-05-16 20:10:34.910000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00301: on_time=2026-05-16 20:10:58.086000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00302: on_time=2026-05-16 20:11:09.762000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00303: on_time=2026-05-16 20:11:18.568000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00304: on_time=2026-05-16 20:13:51.674000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00305: on_time=2026-05-16 20:14:01.868000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00306: on_time=2026-05-16 20:14:13.614000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00307: on_time=2026-05-16 20:14:25.240000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00308: on_time=2026-05-16 20:16:51.668000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00309: on_time=2026-05-16 20:16:51.942000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00310: on_time=2026-05-16 20:17:04.276000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00311: on_time=2026-05-16 20:17:17.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00312: on_time=2026-05-16 20:17:17.444000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00313: on_time=2026-05-16 20:18:32.180000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00314: on_time=2026-05-16 20:19:49.746000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00315: on_time=2026-05-16 20:20:01.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00316: on_time=2026-05-16 20:20:13.712000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00317: on_time=2026-05-16 20:20:22.942000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00318: on_time=2026-05-16 20:21:53.492000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00319: on_time=2026-05-16 20:21:53.978000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00320: on_time=2026-05-16 20:22:03.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00321: on_time=2026-05-16 20:22:13.582000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00322: on_time=2026-05-16 20:22:22.854000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00323: on_time=2026-05-16 20:23:45.236000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00324: on_time=2026-05-16 20:23:45.486000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00325: on_time=2026-05-16 20:23:59.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00326: on_time=2026-05-16 20:24:07.978000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00327: on_time=2026-05-16 20:24:17.368000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00328: on_time=2026-05-16 20:28:15.266000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00329: on_time=2026-05-16 20:28:28.998000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00330: on_time=2026-05-16 20:28:40.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00331: on_time=2026-05-16 20:28:51.266000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00332: on_time=2026-05-16 20:31:51.210000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00333: on_time=2026-05-16 20:32:24.288000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00334: on_time=2026-05-16 20:32:39.348000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00335: on_time=2026-05-16 20:32:55.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00336: on_time=2026-05-16 20:33:25.804000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00337: on_time=2026-05-16 20:33:27.100000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00338: on_time=2026-05-16 20:34:27.626000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00339: on_time=2026-05-16 20:34:53.630000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00340: on_time=2026-05-16 20:35:05.856000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00341: on_time=2026-05-16 20:35:17.824000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00342: on_time=2026-05-16 20:35:29.366000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00343: on_time=2026-05-16 20:36:59.144000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00344: on_time=2026-05-16 20:38:40.526000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00345: on_time=2026-05-16 20:38:40.932000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00346: on_time=2026-05-16 20:38:41.158000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00347: on_time=2026-05-16 20:38:51.350000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00348: on_time=2026-05-16 20:39:02.872000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00349: on_time=2026-05-16 20:39:12.128000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00350: on_time=2026-05-16 20:42:20.086000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00351: on_time=2026-05-16 20:42:40.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00352: on_time=2026-05-16 20:42:48.540000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00353: on_time=2026-05-16 20:42:57.190000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00354: on_time=2026-05-16 20:46:12.698000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00355: on_time=2026-05-16 20:46:25.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00356: on_time=2026-05-16 20:46:33.870000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00357: on_time=2026-05-16 20:46:42.692000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00358: on_time=2026-05-16 20:48:40.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00359: on_time=2026-05-16 20:48:51.602000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00360: on_time=2026-05-16 20:49:03.192000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00361: on_time=2026-05-16 20:49:03.398000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00362: on_time=2026-05-16 20:51:16.362000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00363: on_time=2026-05-16 20:51:24.728000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00364: on_time=2026-05-16 20:51:33.092000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00365: on_time=2026-05-16 20:51:42.198000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00366: on_time=2026-05-16 20:51:46.728000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00367: on_time=2026-05-16 20:52:57.828000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00368: on_time=2026-05-16 20:53:13.064000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00369: on_time=2026-05-16 20:53:23.302000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00370: on_time=2026-05-16 20:53:32.604000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00371: on_time=2026-05-16 20:53:44.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00372: on_time=2026-05-16 20:55:07.614000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00373: on_time=2026-05-16 20:55:15.848000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00374: on_time=2026-05-16 20:55:24.178000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00375: on_time=2026-05-16 20:55:32.528000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00376: on_time=2026-05-16 20:56:48.434000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00377: on_time=2026-05-16 20:56:56.762000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00378: on_time=2026-05-16 20:57:05.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00379: on_time=2026-05-16 20:57:14.454000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00380: on_time=2026-05-16 20:58:30.426000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00381: on_time=2026-05-16 20:58:39.144000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00382: on_time=2026-05-16 20:58:49.072000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00383: on_time=2026-05-16 20:58:56.988000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00384: on_time=2026-05-16 21:00:07.898000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00385: on_time=2026-05-16 21:00:17.404000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00386: on_time=2026-05-16 21:00:26.674000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00387: on_time=2026-05-16 21:00:35.916000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00388: on_time=2026-05-16 21:00:42.148000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00389: on_time=2026-05-16 21:00:53.552000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00390: on_time=2026-05-16 21:01:34.030000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00391: on_time=2026-05-16 21:01:43.268000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00392: on_time=2026-05-16 21:01:52.838000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00393: on_time=2026-05-16 21:02:00.340000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00394: on_time=2026-05-16 21:03:46.570000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00395: on_time=2026-05-16 21:03:59.836000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00396: on_time=2026-05-16 21:04:00.084000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00397: on_time=2026-05-16 21:04:14.674000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00398: on_time=2026-05-16 21:04:26.948000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00399: on_time=2026-05-16 21:05:36.114000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00400: on_time=2026-05-16 21:05:45.706000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00401: on_time=2026-05-16 21:05:52.818000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00402: on_time=2026-05-16 21:05:59.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00403: on_time=2026-05-16 21:06:48.544000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00404: on_time=2026-05-16 21:06:56.926000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00405: on_time=2026-05-16 21:07:04.436000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00406: on_time=2026-05-16 21:07:11.448000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00407: on_time=2026-05-16 21:08:49.162000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00408: on_time=2026-05-16 21:09:27.890000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00409: on_time=2026-05-16 21:09:28.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00410: on_time=2026-05-16 21:09:38.052000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00411: on_time=2026-05-16 21:09:46.746000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00412: on_time=2026-05-16 21:09:47.086000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00413: on_time=2026-05-16 21:10:50.414000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00414: on_time=2026-05-16 21:10:50.654000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00415: on_time=2026-05-16 21:11:06.466000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00416: on_time=2026-05-16 21:11:14.090000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00417: on_time=2026-05-16 21:11:14.582000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00418: on_time=2026-05-16 21:11:22.834000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00419: on_time=2026-05-16 21:12:31.084000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00420: on_time=2026-05-16 21:12:39.270000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00421: on_time=2026-05-16 21:12:49.466000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00422: on_time=2026-05-16 21:12:58.720000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00423: on_time=2026-05-16 21:12:59.184000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00424: on_time=2026-05-16 21:13:59.212000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00425: on_time=2026-05-16 21:14:06.598000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00426: on_time=2026-05-16 21:14:14.208000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00427: on_time=2026-05-16 21:14:21.934000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00428: on_time=2026-05-16 21:16:23.390000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00429: on_time=2026-05-16 21:16:33.390000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00430: on_time=2026-05-16 21:17:04.128000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00431: on_time=2026-05-16 21:17:13.148000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00432: on_time=2026-05-16 21:17:20.534000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00433: on_time=2026-05-16 21:17:27.118000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00434: on_time=2026-05-16 21:18:26.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00435: on_time=2026-05-16 21:18:34.172000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00436: on_time=2026-05-16 21:18:40.678000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00437: on_time=2026-05-16 21:18:46.188000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00438: on_time=2026-05-16 21:19:50.470000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00439: on_time=2026-05-16 21:19:50.674000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00440: on_time=2026-05-16 21:19:58.688000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00441: on_time=2026-05-16 21:20:06.042000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00442: on_time=2026-05-16 21:20:13.182000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00443: on_time=2026-05-16 21:21:34.242000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00444: on_time=2026-05-16 21:21:34.538000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00445: on_time=2026-05-16 21:21:44.696000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00446: on_time=2026-05-16 21:21:56.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00447: on_time=2026-05-16 21:21:56.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00448: on_time=2026-05-16 21:22:09.560000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00449: on_time=2026-05-16 21:23:15.170000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00450: on_time=2026-05-16 21:23:26.442000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00451: on_time=2026-05-16 21:23:40.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00452: on_time=2026-05-16 21:23:47.734000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00453: on_time=2026-05-16 21:23:52.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00454: on_time=2026-05-16 21:23:54.152000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00455: on_time=2026-05-16 21:24:53.898000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00456: on_time=2026-05-16 21:25:01.204000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00457: on_time=2026-05-16 21:25:06.844000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00458: on_time=2026-05-16 21:25:13.448000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00459: on_time=2026-05-16 21:26:10.656000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00460: on_time=2026-05-16 21:26:10.858000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00461: on_time=2026-05-16 21:26:18.640000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00462: on_time=2026-05-16 21:26:26.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00463: on_time=2026-05-16 21:26:27.272000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00464: on_time=2026-05-16 21:26:36.592000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00465: on_time=2026-05-16 21:27:32.636000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00466: on_time=2026-05-16 21:27:46.048000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00467: on_time=2026-05-16 21:27:46.320000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00468: on_time=2026-05-16 21:27:53.200000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00469: on_time=2026-05-16 21:27:59.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00470: on_time=2026-05-16 21:29:06.828000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00471: on_time=2026-05-16 21:29:07.248000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00472: on_time=2026-05-16 21:29:16.258000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00473: on_time=2026-05-16 21:29:24.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00474: on_time=2026-05-16 21:29:35.418000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00475: on_time=2026-05-16 21:30:54.750000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00476: on_time=2026-05-16 21:31:04.826000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00477: on_time=2026-05-16 21:31:10.794000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00478: on_time=2026-05-16 21:31:16.178000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00479: on_time=2026-05-16 21:31:16.404000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00480: on_time=2026-05-16 21:31:58.592000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00481: on_time=2026-05-16 21:31:58.818000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00482: on_time=2026-05-16 21:32:04.302000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00483: on_time=2026-05-16 21:32:04.510000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00484: on_time=2026-05-16 21:32:09.426000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00485: on_time=2026-05-16 21:32:09.832000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00486: on_time=2026-05-16 21:32:14.878000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00487: on_time=2026-05-16 21:32:15.096000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00488: on_time=2026-05-16 21:33:02.300000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00489: on_time=2026-05-16 21:33:07.092000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00490: on_time=2026-05-16 21:33:07.388000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00491: on_time=2026-05-16 21:33:12.170000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00492: on_time=2026-05-16 21:33:12.476000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00493: on_time=2026-05-16 21:33:17.718000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00494: on_time=2026-05-16 21:33:18.020000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00495: on_time=2026-05-16 21:34:13.110000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00496: on_time=2026-05-16 21:34:17.656000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00497: on_time=2026-05-16 21:34:22.008000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00498: on_time=2026-05-16 21:34:28.106000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00499: on_time=2026-05-16 21:34:35.976000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00500: on_time=2026-05-16 21:34:36.304000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00501: on_time=2026-05-16 21:35:30.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00502: on_time=2026-05-16 21:35:35.274000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00503: on_time=2026-05-16 21:35:35.474000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00504: on_time=2026-05-16 21:35:39.948000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00505: on_time=2026-05-16 21:35:40.212000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00506: on_time=2026-05-16 21:35:45.616000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00507: on_time=2026-05-16 21:36:36.652000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00508: on_time=2026-05-16 21:36:42.544000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00509: on_time=2026-05-16 21:36:47.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00510: on_time=2026-05-16 21:36:53.272000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00511: on_time=2026-05-16 21:36:56.984000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

T1_N1_Streamer_T1_N1_E00512: on_time=2026-05-16 21:37:56.332000
  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00513: on_time=2026-05-16 21:38:01.412000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00514: on_time=2026-05-16 21:38:07.324000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

T1_N1_Streamer_T1_N1_E00515: on_time=2026-05-16 21:38:13.368000
  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00516: on_time=2026-05-16 21:39:13.460000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00517: on_time=2026-05-16 21:39:18.898000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00518: on_time=2026-05-16 21:39:24.322000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00519: on_time=2026-05-16 21:39:30.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00520: on_time=2026-05-16 21:40:18.792000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00521: on_time=2026-05-16 21:40:23.846000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00522: on_time=2026-05-16 21:40:24.192000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00523: on_time=2026-05-16 21:40:29.418000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00524: on_time=2026-05-16 21:40:35.858000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00525: on_time=2026-05-16 21:40:36.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00526: on_time=2026-05-16 21:41:23.542000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00527: on_time=2026-05-16 21:41:31.694000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00528: on_time=2026-05-16 21:41:37.810000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00529: on_time=2026-05-16 21:41:43.424000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00530: on_time=2026-05-16 21:42:22.854000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00531: on_time=2026-05-16 21:43:25.066000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N1_Streamer_T1_N1_E00532: on_time=2026-05-16 21:44:03.302000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

====================================================================================================
Processing T1_N2_Nodal1

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

Discovered 35 T1.N2.DPZ stations
['06809', '07600', '08003', '08405', '08808', '09210', '09605', '10000', '10408', '10603', '10814', '11005', '11215', '11400', '11611', '11797', '12018', '12204', '12413', '12638', '12815', '12996', '13216', '13402', '13620', '13782', '14000', '14400', '14800', '15195', '16000', '16400', '16809', '17604', '18405']
T1_N2_Nodal1 chunk 0: 2026-05-17T16:00:00.000000Z to 2026-05-17T16:01:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 1: 2026-05-17T16:01:00.000000Z to 2026-05-17T16:02:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 2: 2026-05-17T16:02:00.000000Z to 2026-05-17T16:03:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 3: 2026-05-17T16:03:00.000000Z to 2026-05-17T16:04:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 4: 2026-05-17T16:04:00.000000Z to 2026-05-17T16:05:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 5: 2026-05-17T16:05:00.000000Z to 2026-05-17T16:06:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 6: 2026-05-17T16:06:00.000000Z to 2026-05-17T16:07:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 7: 2026-05-17T16:07:00.000000Z to 2026-05-17T16:08:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 8: 2026-05-17T16:08:00.000000Z to 2026-05-17T16:09:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 9: 2026-05-17T16:09:00.000000Z to 2026-05-17T16:10:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 10: 2026-05-17T16:10:00.000000Z to 2026-05-17T16:11:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 11: 2026-05-17T16:11:00.000000Z to 2026-05-17T16:12:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 12: 2026-05-17T16:12:00.000000Z to 2026-05-17T16:13:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 13: 2026-05-17T16:13:00.000000Z to 2026-05-17T16:14:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 14: 2026-05-17T16:14:00.000000Z to 2026-05-17T16:15:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 15: 2026-05-17T16:15:00.000000Z to 2026-05-17T16:16:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 16: 2026-05-17T16:16:00.000000Z to 2026-05-17T16:17:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 17: 2026-05-17T16:17:00.000000Z to 2026-05-17T16:18:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 18: 2026-05-17T16:18:00.000000Z to 2026-05-17T16:19:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 19: 2026-05-17T16:19:00.000000Z to 2026-05-17T16:20:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T1_N2_Nodal1 chunk 20: 2026-05-17T16:20:00.000000Z to 2026-05-17T16:21:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 21: 2026-05-17T16:21:00.000000Z to 2026-05-17T16:22:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 22: 2026-05-17T16:22:00.000000Z to 2026-05-17T16:23:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 23: 2026-05-17T16:23:00.000000Z to 2026-05-17T16:24:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 24: 2026-05-17T16:24:00.000000Z to 2026-05-17T16:25:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 25: 2026-05-17T16:25:00.000000Z to 2026-05-17T16:26:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 26: 2026-05-17T16:26:00.000000Z to 2026-05-17T16:27:00.000000Z
  read 35 traces, 35 stations
T1_N2_Nodal1 chunk 27: 2026-05-17T16:27:00.000000Z to 2026-05-17T16:28:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 28: 2026-05-17T16:28:00.000000Z to 2026-05-17T16:29:00.000000Z
  read 33 traces, 33 stations
T1_N2_Nodal1 chunk 29: 2026-05-17T16:29:00.000000Z to 2026-05-17T16:30:00.000000Z
  read 32 traces, 32 stations
T1_N2_Nodal1 chunk 30: 2026-05-17T16:30:00.000000Z to 2026-05-17T16:31:00.000000Z
  read 32 traces, 32 stations
  detections: 1
T1_N2_Nodal1 chunk 31: 2026-05-17T16:31:00.000000Z to 2026-05-17T16:32:00.000000Z
  read 32 traces, 32 stations
  detections: 3
T1_N2_Nodal1 chunk 32: 2026-05-17T16:32:00.000000Z to 2026-05-17T16:33:00.000000Z
  read 32 traces, 32 stations
  detections: 11
T1_N2_Nodal1 chunk 33: 2026-05-17T16:33:00.000000Z to 2026-05-17T16:34:00.000000Z
  read 32 traces, 32 stations
  detections: 8
T1_N2_Nodal1 chunk 34: 2026-05-17T16:34:00.000000Z to 2026-05-17T16:35:00.000000Z
  read 32 traces, 32 stations
  detections: 1
T1_N2_Nodal1 chunk 35: 2026-05-17T16:35:00.000000Z to 2026-05-17T16:36:00.000000Z
  read 32 traces, 32 stations
  detections: 8
T1_N2_Nodal1 chunk 36: 2026-05-17T16:36:00.000000Z to 2026-05-17T16:37:00.000000Z
  read 32 traces, 32 stations
T1_N2_Nodal1 chunk 37: 2026-05-17T16:37:00.000000Z to 2026-05-17T16:38:00.000000Z
  read 31 traces, 31 stations
  detections: 18
T1_N2_Nodal1 chunk 38: 2026-05-17T16:38:00.000000Z to 2026-05-17T16:39:00.000000Z
  read 29 traces, 29 stations
  detections: 7
T1_N2_Nodal1 chunk 39: 2026-05-17T16:39:00.000000Z to 2026-05-17T16:40:00.000000Z
  read 29 traces, 29 stations
  detections: 2
T1_N2_Nodal1 chunk 40: 2026-05-17T16:40:00.000000Z to 2026-05-17T16:41:00.000000Z
  read 29 traces, 29 stations
  detections: 6
T1_N2_Nodal1 chunk 41: 2026-05-17T16:41:00.000000Z to 2026-05-17T16:42:00.000000Z
  read 29 traces, 29 stations
  detections: 1
T1_N2_Nodal1 chunk 42: 2026-05-17T16:42:00.000000Z to 2026-05-17T16:43:00.000000Z
  read 28 traces, 28 stations
  detections: 1
T1_N2_Nodal1 chunk 43: 2026-05-17T16:43:00.000000Z to 2026-05-17T16:44:00.000000Z
  read 28 traces, 28 stations
  detections: 7
T1_N2_Nodal1 chunk 44: 2026-05-17T16:44:00.000000Z to 2026-05-17T16:45:00.000000Z
  read 28 traces, 28 stations
  detections: 12
T1_N2_Nodal1 chunk 45: 2026-05-17T16:45:00.000000Z to 2026-05-17T16:46:00.000000Z
  read 28 traces, 28 stations
  detections: 12
T1_N2_Nodal1 chunk 46: 2026-05-17T16:46:00.000000Z to 2026-05-17T16:47:00.000000Z
  read 28 traces, 28 stations
  detections: 26
T1_N2_Nodal1 chunk 47: 2026-05-17T16:47:00.000000Z to 2026-05-17T16:48:00.000000Z
  read 28 traces, 28 stations
  detections: 5
T1_N2_Nodal1 chunk 48: 2026-05-17T16:48:00.000000Z to 2026-05-17T16:49:00.000000Z
  read 26 traces, 26 stations
  detections: 38
T1_N2_Nodal1 chunk 49: 2026-05-17T16:49:00.000000Z to 2026-05-17T16:50:00.000000Z
  read 26 traces, 26 stations
  detections: 13
T1_N2_Nodal1 chunk 50: 2026-05-17T16:50:00.000000Z to 2026-05-17T16:51:00.000000Z
  read 26 traces, 26 stations
  detections: 18
T1_N2_Nodal1 chunk 51: 2026-05-17T16:51:00.000000Z to 2026-05-17T16:52:00.000000Z
  read 26 traces, 26 stations
  detections: 5
T1_N2_Nodal1 chunk 52: 2026-05-17T16:52:00.000000Z to 2026-05-17T16:53:00.000000Z
  read 26 traces, 26 stations
  detections: 41
T1_N2_Nodal1 chunk 53: 2026-05-17T16:53:00.000000Z to 2026-05-17T16:54:00.000000Z
  read 26 traces, 26 stations
  detections: 21
T1_N2_Nodal1 chunk 54: 2026-05-17T16:54:00.000000Z to 2026-05-17T16:55:00.000000Z
  read 26 traces, 26 stations
  detections: 8
T1_N2_Nodal1 chunk 55: 2026-05-17T16:55:00.000000Z to 2026-05-17T16:56:00.000000Z
  read 26 traces, 26 stations
  detections: 41
T1_N2_Nodal1 chunk 56: 2026-05-17T16:56:00.000000Z to 2026-05-17T16:57:00.000000Z
  read 29 traces, 29 stations
  detections: 7
T1_N2_Nodal1 chunk 57: 2026-05-17T16:57:00.000000Z to 2026-05-17T16:58:00.000000Z
  read 32 traces, 32 stations
  detections: 8
T1_N2_Nodal1 chunk 58: 2026-05-17T16:58:00.000000Z to 2026-05-17T16:59:00.000000Z
  read 32 traces, 32 stations
  detections: 14
T1_N2_Nodal1 chunk 59: 2026-05-17T16:59:00.000000Z to 2026-05-17T17:00:00.000000Z
  read 32 traces, 32 stations
  detections: 7
T1_N2_Nodal1 chunk 60: 2026-05-17T17:00:00.000000Z to 2026-05-17T17:01:00.000000Z
  read 32 traces, 32 stations
  detections: 20
T1_N2_Nodal1 chunk 61: 2026-05-17T17:01:00.000000Z to 2026-05-17T17:02:00.000000Z
  read 32 traces, 32 stations
  detections: 17
T1_N2_Nodal1 chunk 62: 2026-05-17T17:02:00.000000Z to 2026-05-17T17:03:00.000000Z
  read 32 traces, 32 stations
  detections: 17
T1_N2_Nodal1 chunk 63: 2026-05-17T17:03:00.000000Z to 2026-05-17T17:04:00.000000Z
  read 33 traces, 33 stations
  detections: 2
T1_N2_Nodal1 chunk 64: 2026-05-17T17:04:00.000000Z to 2026-05-17T17:05:00.000000Z
  read 33 traces, 33 stations
  detections: 56
T1_N2_Nodal1 chunk 65: 2026-05-17T17:05:00.000000Z to 2026-05-17T17:06:00.000000Z
  read 33 traces, 33 stations
  detections: 52
T1_N2_Nodal1 chunk 66: 2026-05-17T17:06:00.000000Z to 2026-05-17T17:07:00.000000Z
  read 33 traces, 33 stations
  detections: 27
T1_N2_Nodal1 chunk 67: 2026-05-17T17:07:00.000000Z to 2026-05-17T17:08:00.000000Z
  read 33 traces, 33 stations
  detections: 38
T1_N2_Nodal1 chunk 68: 2026-05-17T17:08:00.000000Z to 2026-05-17T17:09:00.000000Z
  read 33 traces, 33 stations
  detections: 13
T1_N2_Nodal1 chunk 69: 2026-05-17T17:09:00.000000Z to 2026-05-17T17:10:00.000000Z
  read 33 traces, 33 stations
  detections: 5
T1_N2_Nodal1 chunk 70: 2026-05-17T17:10:00.000000Z to 2026-05-17T17:11:00.000000Z
  read 33 traces, 33 stations
  detections: 16
T1_N2_Nodal1 chunk 71: 2026-05-17T17:11:00.000000Z to 2026-05-17T17:12:00.000000Z
  read 33 traces, 33 stations
  detections: 16
T1_N2_Nodal1 chunk 72: 2026-05-17T17:12:00.000000Z to 2026-05-17T17:13:00.000000Z
  read 33 traces, 33 stations
  detections: 23
T1_N2_Nodal1 chunk 73: 2026-05-17T17:13:00.000000Z to 2026-05-17T17:14:00.000000Z
  read 33 traces, 33 stations
  detections: 15
T1_N2_Nodal1 chunk 74: 2026-05-17T17:14:00.000000Z to 2026-05-17T17:15:00.000000Z
  read 33 traces, 33 stations
  detections: 14
T1_N2_Nodal1 chunk 75: 2026-05-17T17:15:00.000000Z to 2026-05-17T17:16:00.000000Z
  read 33 traces, 33 stations
  detections: 18
T1_N2_Nodal1 chunk 76: 2026-05-17T17:16:00.000000Z to 2026-05-17T17:17:00.000000Z
  read 33 traces, 33 stations
  detections: 13
T1_N2_Nodal1 chunk 77: 2026-05-17T17:17:00.000000Z to 2026-05-17T17:18:00.000000Z
  read 33 traces, 33 stations
  detections: 12
T1_N2_Nodal1 chunk 78: 2026-05-17T17:18:00.000000Z to 2026-05-17T17:19:00.000000Z
  read 33 traces, 33 stations
  detections: 8
T1_N2_Nodal1 chunk 79: 2026-05-17T17:19:00.000000Z to 2026-05-17T17:20:00.000000Z
  read 33 traces, 33 stations
  detections: 16
T1_N2_Nodal1 chunk 80: 2026-05-17T17:20:00.000000Z to 2026-05-17T17:21:00.000000Z
  read 33 traces, 33 stations
  detections: 9
T1_N2_Nodal1 chunk 81: 2026-05-17T17:21:00.000000Z to 2026-05-17T17:22:00.000000Z
  read 33 traces, 33 stations
  detections: 15
T1_N2_Nodal1 chunk 82: 2026-05-17T17:22:00.000000Z to 2026-05-17T17:23:00.000000Z
  read 33 traces, 33 stations
  detections: 13
T1_N2_Nodal1 chunk 83: 2026-05-17T17:23:00.000000Z to 2026-05-17T17:24:00.000000Z
  read 33 traces, 33 stations
  detections: 5
T1_N2_Nodal1 chunk 84: 2026-05-17T17:24:00.000000Z to 2026-05-17T17:25:00.000000Z
  read 33 traces, 33 stations
T1_N2_Nodal1 chunk 85: 2026-05-17T17:25:00.000000Z to 2026-05-17T17:26:00.000000Z
  read 34 traces, 34 stations
  detections: 12
T1_N2_Nodal1 chunk 86: 2026-05-17T17:26:00.000000Z to 2026-05-17T17:27:00.000000Z
  read 34 traces, 34 stations
  detections: 12
T1_N2_Nodal1 chunk 87: 2026-05-17T17:27:00.000000Z to 2026-05-17T17:28:00.000000Z
  read 34 traces, 34 stations
  detections: 16
T1_N2_Nodal1 chunk 88: 2026-05-17T17:28:00.000000Z to 2026-05-17T17:29:00.000000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Nodal1 chunk 89: 2026-05-17T17:29:00.000000Z to 2026-05-17T17:30:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 90: 2026-05-17T17:30:00.000000Z to 2026-05-17T17:31:00.000000Z
  read 34 traces, 34 stations
  detections: 33
T1_N2_Nodal1 chunk 91: 2026-05-17T17:31:00.000000Z to 2026-05-17T17:32:00.000000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Nodal1 chunk 92: 2026-05-17T17:32:00.000000Z to 2026-05-17T17:33:00.000000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Nodal1 chunk 93: 2026-05-17T17:33:00.000000Z to 2026-05-17T17:34:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 94: 2026-05-17T17:34:00.000000Z to 2026-05-17T17:35:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 95: 2026-05-17T17:35:00.000000Z to 2026-05-17T17:36:00.000000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Nodal1 chunk 96: 2026-05-17T17:36:00.000000Z to 2026-05-17T17:37:00.000000Z
  read 34 traces, 34 stations
  detections: 18
T1_N2_Nodal1 chunk 97: 2026-05-17T17:37:00.000000Z to 2026-05-17T17:38:00.000000Z
  read 34 traces, 34 stations
  detections: 17
T1_N2_Nodal1 chunk 98: 2026-05-17T17:38:00.000000Z to 2026-05-17T17:39:00.000000Z
  read 34 traces, 34 stations
  detections: 14
T1_N2_Nodal1 chunk 99: 2026-05-17T17:39:00.000000Z to 2026-05-17T17:40:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 100: 2026-05-17T17:40:00.000000Z to 2026-05-17T17:41:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 101: 2026-05-17T17:41:00.000000Z to 2026-05-17T17:42:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 102: 2026-05-17T17:42:00.000000Z to 2026-05-17T17:43:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 103: 2026-05-17T17:43:00.000000Z to 2026-05-17T17:44:00.000000Z
  read 34 traces, 34 stations
  detections: 14
T1_N2_Nodal1 chunk 104: 2026-05-17T17:44:00.000000Z to 2026-05-17T17:45:00.000000Z
  read 34 traces, 34 stations
  detections: 15
T1_N2_Nodal1 chunk 105: 2026-05-17T17:45:00.000000Z to 2026-05-17T17:46:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 106: 2026-05-17T17:46:00.000000Z to 2026-05-17T17:47:00.000000Z
  read 34 traces, 34 stations
  detections: 16
T1_N2_Nodal1 chunk 107: 2026-05-17T17:47:00.000000Z to 2026-05-17T17:48:00.000000Z
  read 34 traces, 34 stations
  detections: 11
T1_N2_Nodal1 chunk 108: 2026-05-17T17:48:00.000000Z to 2026-05-17T17:49:00.000000Z
  read 34 traces, 34 stations
  detections: 17
T1_N2_Nodal1 chunk 109: 2026-05-17T17:49:00.000000Z to 2026-05-17T17:50:00.000000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Nodal1 chunk 110: 2026-05-17T17:50:00.000000Z to 2026-05-17T17:51:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 111: 2026-05-17T17:51:00.000000Z to 2026-05-17T17:52:00.000000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Nodal1 chunk 112: 2026-05-17T17:52:00.000000Z to 2026-05-17T17:53:00.000000Z
  read 34 traces, 34 stations
  detections: 11
T1_N2_Nodal1 chunk 113: 2026-05-17T17:53:00.000000Z to 2026-05-17T17:54:00.000000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Nodal1 chunk 114: 2026-05-17T17:54:00.000000Z to 2026-05-17T17:55:00.000000Z
  read 34 traces, 34 stations
  detections: 10
T1_N2_Nodal1 chunk 115: 2026-05-17T17:55:00.000000Z to 2026-05-17T17:56:00.000000Z
  read 34 traces, 34 stations
  detections: 14
T1_N2_Nodal1 chunk 116: 2026-05-17T17:56:00.000000Z to 2026-05-17T17:57:00.000000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Nodal1 chunk 117: 2026-05-17T17:57:00.000000Z to 2026-05-17T17:58:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 118: 2026-05-17T17:58:00.000000Z to 2026-05-17T17:59:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 119: 2026-05-17T17:59:00.000000Z to 2026-05-17T18:00:00.000000Z
  read 34 traces, 34 stations
  detections: 11
T1_N2_Nodal1 chunk 120: 2026-05-17T18:00:00.000000Z to 2026-05-17T18:01:00.000000Z
  read 34 traces, 34 stations
  detections: 14
T1_N2_Nodal1 chunk 121: 2026-05-17T18:01:00.000000Z to 2026-05-17T18:02:00.000000Z
  read 34 traces, 34 stations
  detections: 17
T1_N2_Nodal1 chunk 122: 2026-05-17T18:02:00.000000Z to 2026-05-17T18:03:00.000000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Nodal1 chunk 123: 2026-05-17T18:03:00.000000Z to 2026-05-17T18:04:00.000000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Nodal1 chunk 124: 2026-05-17T18:04:00.000000Z to 2026-05-17T18:05:00.000000Z
  read 34 traces, 34 stations
  detections: 10
T1_N2_Nodal1 chunk 125: 2026-05-17T18:05:00.000000Z to 2026-05-17T18:06:00.000000Z
  read 34 traces, 34 stations
  detections: 17
T1_N2_Nodal1 chunk 126: 2026-05-17T18:06:00.000000Z to 2026-05-17T18:07:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 127: 2026-05-17T18:07:00.000000Z to 2026-05-17T18:08:00.000000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Nodal1 chunk 128: 2026-05-17T18:08:00.000000Z to 2026-05-17T18:09:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 129: 2026-05-17T18:09:00.000000Z to 2026-05-17T18:10:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 130: 2026-05-17T18:10:00.000000Z to 2026-05-17T18:11:00.000000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Nodal1 chunk 131: 2026-05-17T18:11:00.000000Z to 2026-05-17T18:12:00.000000Z
  read 34 traces, 34 stations
  detections: 9
T1_N2_Nodal1 chunk 132: 2026-05-17T18:12:00.000000Z to 2026-05-17T18:13:00.000000Z
  read 34 traces, 34 stations
  detections: 14
T1_N2_Nodal1 chunk 133: 2026-05-17T18:13:00.000000Z to 2026-05-17T18:14:00.000000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Nodal1 chunk 134: 2026-05-17T18:14:00.000000Z to 2026-05-17T18:15:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 135: 2026-05-17T18:15:00.000000Z to 2026-05-17T18:16:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 136: 2026-05-17T18:16:00.000000Z to 2026-05-17T18:17:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 137: 2026-05-17T18:17:00.000000Z to 2026-05-17T18:18:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 138: 2026-05-17T18:18:00.000000Z to 2026-05-17T18:19:00.000000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Nodal1 chunk 139: 2026-05-17T18:19:00.000000Z to 2026-05-17T18:20:00.000000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Nodal1 chunk 140: 2026-05-17T18:20:00.000000Z to 2026-05-17T18:21:00.000000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Nodal1 chunk 141: 2026-05-17T18:21:00.000000Z to 2026-05-17T18:22:00.000000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Nodal1 chunk 142: 2026-05-17T18:22:00.000000Z to 2026-05-17T18:23:00.000000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Nodal1 chunk 143: 2026-05-17T18:23:00.000000Z to 2026-05-17T18:24:00.000000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Nodal1 chunk 144: 2026-05-17T18:24:00.000000Z to 2026-05-17T18:25:00.000000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Nodal1 chunk 145: 2026-05-17T18:25:00.000000Z to 2026-05-17T18:26:00.000000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Nodal1 chunk 146: 2026-05-17T18:26:00.000000Z to 2026-05-17T18:27:00.000000Z
  read 34 traces, 34 stations
  detections: 11
T1_N2_Nodal1 chunk 147: 2026-05-17T18:27:00.000000Z to 2026-05-17T18:28:00.000000Z
  read 34 traces, 34 stations
  detections: 16
T1_N2_Nodal1 chunk 148: 2026-05-17T18:28:00.000000Z to 2026-05-17T18:29:00.000000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Nodal1 chunk 149: 2026-05-17T18:29:00.000000Z to 2026-05-17T18:30:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 150: 2026-05-17T18:30:00.000000Z to 2026-05-17T18:31:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal1 chunk 151: 2026-05-17T18:31:00.000000Z to 2026-05-17T18:32:00.000000Z
  read 34 traces, 34 stations
  detections: 12
T1_N2_Nodal1 chunk 152: 2026-05-17T18:32:00.000000Z to 2026-05-17T18:33:00.000000Z
  read 34 traces, 34 stations
  detections: 11
T1_N2_Nodal1 chunk 153: 2026-05-17T18:33:00.000000Z to 2026-05-17T18:34:00.000000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Nodal1 chunk 154: 2026-05-17T18:34:00.000000Z to 2026-05-17T18:35:00.000000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Nodal1 chunk 155: 2026-05-17T18:35:00.000000Z to 2026-05-17T18:36:00.000000Z
  read 34 traces, 34 stations
  detections: 16
T1_N2_Nodal1 chunk 156: 2026-05-17T18:36:00.000000Z to 2026-05-17T18:37:00.000000Z
  read 34 traces, 34 stations
  detections: 17
T1_N2_Nodal1 chunk 157: 2026-05-17T18:37:00.000000Z to 2026-05-17T18:38:00.000000Z

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T1_N2_Nodal1_T1_N2_E00003: on_time=2026-05-17 16:30:21.802000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00004: on_time=2026-05-17 16:31:43.332000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00005: on_time=2026-05-17 16:31:52.616000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00006: on_time=2026-05-17 16:31:56.062000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00007: on_time=2026-05-17 16:32:20.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00008: on_time=2026-05-17 16:32:40.806000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00009: on_time=2026-05-17 16:32:41.720000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00010: on_time=2026-05-17 16:32:42.508000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00011: on_time=2026-05-17 16:32:43.270000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00012: on_time=2026-05-17 16:32:43.958000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00013: on_time=2026-05-17 16:32:44.668000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00014: on_time=2026-05-17 16:32:45.380000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00015: on_time=2026-05-17 16:32:46.088000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00016: on_time=2026-05-17 16:32:46.844000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00017: on_time=2026-05-17 16:32:47.496000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00018: on_time=2026-05-17 16:33:16.368000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00019: on_time=2026-05-17 16:33:25.394000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00020: on_time=2026-05-17 16:33:33.626000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00021: on_time=2026-05-17 16:33:35.108000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00022: on_time=2026-05-17 16:33:36.826000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00023: on_time=2026-05-17 16:33:39.848000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00024: on_time=2026-05-17 16:33:44.512000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00025: on_time=2026-05-17 16:33:49.586000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00026: on_time=2026-05-17 16:34:25.446000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00027: on_time=2026-05-17 16:35:08.710000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00028: on_time=2026-05-17 16:35:12.738000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00029: on_time=2026-05-17 16:35:14.666000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00030: on_time=2026-05-17 16:35:18.164000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00031: on_time=2026-05-17 16:35:29.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00032: on_time=2026-05-17 16:35:44.202000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00033: on_time=2026-05-17 16:35:53.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00034: on_time=2026-05-17 16:37:11.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 90 traces, 30 receivers

T1_N2_Nodal1_T1_N2_E00035: on_time=2026-05-17 16:37:13.882000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 90 traces, 30 receivers

T1_N2_Nodal1_T1_N2_E00036: on_time=2026-05-17 16:37:15.858000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 90 traces, 30 receivers

T1_N2_Nodal1_T1_N2_E00037: on_time=2026-05-17 16:37:17.746000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 90 traces, 30 receivers

T1_N2_Nodal1_T1_N2_E00038: on_time=2026-05-17 16:37:19.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 90 traces, 30 receivers

T1_N2_Nodal1_T1_N2_E00039: on_time=2026-05-17 16:37:22.638000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 90 traces, 30 receivers

T1_N2_Nodal1_T1_N2_E00040: on_time=2026-05-17 16:37:24.614000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 90 traces, 30 receivers

T1_N2_Nodal1_T1_N2_E00041: on_time=2026-05-17 16:37:27.048000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 90 traces, 30 receivers

T1_N2_Nodal1_T1_N2_E00042: on_time=2026-05-17 16:37:29.266000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 90 traces, 30 receivers

T1_N2_Nodal1_T1_N2_E00043: on_time=2026-05-17 16:37:31.988000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 90 traces, 30 receivers

T1_N2_Nodal1_T1_N2_E00044: on_time=2026-05-17 16:37:35.690000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00045: on_time=2026-05-17 16:37:39.108000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00046: on_time=2026-05-17 16:37:43.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00047: on_time=2026-05-17 16:37:50.474000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00048: on_time=2026-05-17 16:37:55.818000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00049: on_time=2026-05-17 16:38:00.970000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00050: on_time=2026-05-17 16:38:01.818000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00051: on_time=2026-05-17 16:38:06.634000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00052: on_time=2026-05-17 16:38:13.008000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00053: on_time=2026-05-17 16:38:53.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00054: on_time=2026-05-17 16:38:59.798000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00055: on_time=2026-05-17 16:39:03.502000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00056: on_time=2026-05-17 16:39:05.512000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00057: on_time=2026-05-17 16:40:27.686000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00058: on_time=2026-05-17 16:40:28.224000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00059: on_time=2026-05-17 16:40:28.770000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00060: on_time=2026-05-17 16:40:29.338000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00061: on_time=2026-05-17 16:40:31.136000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00062: on_time=2026-05-17 16:40:33.002000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00063: on_time=2026-05-17 16:41:13.012000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00064: on_time=2026-05-17 16:42:50.506000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00065: on_time=2026-05-17 16:43:23.494000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00066: on_time=2026-05-17 16:43:53.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00067: on_time=2026-05-17 16:43:55.344000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00068: on_time=2026-05-17 16:43:57.112000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00069: on_time=2026-05-17 16:43:58.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00070: on_time=2026-05-17 16:44:00.798000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00071: on_time=2026-05-17 16:44:02.720000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00072: on_time=2026-05-17 16:44:04.674000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00073: on_time=2026-05-17 16:44:07.230000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00074: on_time=2026-05-17 16:44:16.014000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00075: on_time=2026-05-17 16:44:20.910000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00076: on_time=2026-05-17 16:44:24.800000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00077: on_time=2026-05-17 16:44:29.428000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00078: on_time=2026-05-17 16:44:38.112000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00079: on_time=2026-05-17 16:44:42.182000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00080: on_time=2026-05-17 16:44:45.760000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00081: on_time=2026-05-17 16:45:43.560000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00082: on_time=2026-05-17 16:45:51.128000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00083: on_time=2026-05-17 16:45:52.362000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00084: on_time=2026-05-17 16:45:53.056000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00085: on_time=2026-05-17 16:45:54.424000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00086: on_time=2026-05-17 16:45:55.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00087: on_time=2026-05-17 16:45:56.120000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00088: on_time=2026-05-17 16:45:56.746000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00089: on_time=2026-05-17 16:45:57.362000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00090: on_time=2026-05-17 16:45:57.982000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00091: on_time=2026-05-17 16:45:58.928000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00092: on_time=2026-05-17 16:45:59.660000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00093: on_time=2026-05-17 16:46:01.326000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00094: on_time=2026-05-17 16:46:01.964000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00095: on_time=2026-05-17 16:46:02.598000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00096: on_time=2026-05-17 16:46:03.176000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00097: on_time=2026-05-17 16:46:04.796000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00098: on_time=2026-05-17 16:46:05.378000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00099: on_time=2026-05-17 16:46:06.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00100: on_time=2026-05-17 16:46:06.980000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00101: on_time=2026-05-17 16:46:23.330000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00102: on_time=2026-05-17 16:46:32.614000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00103: on_time=2026-05-17 16:46:35.024000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00104: on_time=2026-05-17 16:46:35.902000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00105: on_time=2026-05-17 16:46:36.788000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00106: on_time=2026-05-17 16:46:37.606000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00107: on_time=2026-05-17 16:46:38.490000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00108: on_time=2026-05-17 16:46:40.314000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00109: on_time=2026-05-17 16:46:41.206000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00110: on_time=2026-05-17 16:46:42.098000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00111: on_time=2026-05-17 16:46:43.100000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00112: on_time=2026-05-17 16:46:45.820000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00113: on_time=2026-05-17 16:46:49.824000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00114: on_time=2026-05-17 16:46:50.822000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00115: on_time=2026-05-17 16:46:57.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00116: on_time=2026-05-17 16:47:01.874000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00117: on_time=2026-05-17 16:47:08.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00118: on_time=2026-05-17 16:47:19.814000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00119: on_time=2026-05-17 16:47:25.042000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00120: on_time=2026-05-17 16:47:27.452000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00121: on_time=2026-05-17 16:48:21.382000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00122: on_time=2026-05-17 16:48:21.604000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00123: on_time=2026-05-17 16:48:24.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00124: on_time=2026-05-17 16:48:29.336000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00125: on_time=2026-05-17 16:48:29.960000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00126: on_time=2026-05-17 16:48:31.436000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00127: on_time=2026-05-17 16:48:32.020000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00128: on_time=2026-05-17 16:48:32.590000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00129: on_time=2026-05-17 16:48:33.128000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00130: on_time=2026-05-17 16:48:33.660000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00131: on_time=2026-05-17 16:48:34.204000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00132: on_time=2026-05-17 16:48:35.002000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00133: on_time=2026-05-17 16:48:36.154000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00134: on_time=2026-05-17 16:48:39.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00135: on_time=2026-05-17 16:48:41.982000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00136: on_time=2026-05-17 16:48:42.574000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00137: on_time=2026-05-17 16:48:43.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00138: on_time=2026-05-17 16:48:43.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00139: on_time=2026-05-17 16:48:44.102000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00140: on_time=2026-05-17 16:48:44.596000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00141: on_time=2026-05-17 16:48:45.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00142: on_time=2026-05-17 16:48:49.330000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00143: on_time=2026-05-17 16:48:49.904000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00144: on_time=2026-05-17 16:48:50.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00145: on_time=2026-05-17 16:48:50.968000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00146: on_time=2026-05-17 16:48:51.506000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00147: on_time=2026-05-17 16:48:52.596000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00148: on_time=2026-05-17 16:48:53.124000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00149: on_time=2026-05-17 16:48:53.646000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00150: on_time=2026-05-17 16:48:54.240000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00151: on_time=2026-05-17 16:48:54.746000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00152: on_time=2026-05-17 16:48:55.378000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00153: on_time=2026-05-17 16:48:55.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00154: on_time=2026-05-17 16:48:56.340000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00155: on_time=2026-05-17 16:48:56.792000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00156: on_time=2026-05-17 16:48:58.212000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00157: on_time=2026-05-17 16:48:58.706000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00158: on_time=2026-05-17 16:48:59.206000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00159: on_time=2026-05-17 16:49:00.616000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00160: on_time=2026-05-17 16:49:01.068000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00161: on_time=2026-05-17 16:49:03.030000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00162: on_time=2026-05-17 16:49:03.984000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00163: on_time=2026-05-17 16:49:05.910000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00164: on_time=2026-05-17 16:49:29.432000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00165: on_time=2026-05-17 16:49:47.432000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00166: on_time=2026-05-17 16:49:49.340000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00167: on_time=2026-05-17 16:49:51.338000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00168: on_time=2026-05-17 16:49:53.364000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00169: on_time=2026-05-17 16:49:55.360000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00170: on_time=2026-05-17 16:49:57.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00171: on_time=2026-05-17 16:49:59.622000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00172: on_time=2026-05-17 16:50:01.892000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00173: on_time=2026-05-17 16:50:04.834000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00174: on_time=2026-05-17 16:50:07.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00175: on_time=2026-05-17 16:50:13.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00176: on_time=2026-05-17 16:50:16.948000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00177: on_time=2026-05-17 16:50:25.018000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00178: on_time=2026-05-17 16:50:25.640000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00179: on_time=2026-05-17 16:50:27.914000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00180: on_time=2026-05-17 16:50:29.060000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00181: on_time=2026-05-17 16:50:31.878000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00182: on_time=2026-05-17 16:50:35.148000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00183: on_time=2026-05-17 16:50:36.070000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00184: on_time=2026-05-17 16:50:38.910000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00185: on_time=2026-05-17 16:50:40.696000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00186: on_time=2026-05-17 16:50:45.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00187: on_time=2026-05-17 16:50:52.172000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00188: on_time=2026-05-17 16:50:55.870000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00189: on_time=2026-05-17 16:50:56.930000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00190: on_time=2026-05-17 16:51:02.034000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00191: on_time=2026-05-17 16:51:05.038000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00192: on_time=2026-05-17 16:51:09.378000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00193: on_time=2026-05-17 16:51:15.680000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00194: on_time=2026-05-17 16:51:39.392000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00195: on_time=2026-05-17 16:52:13.610000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00196: on_time=2026-05-17 16:52:14.544000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00197: on_time=2026-05-17 16:52:15.290000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00198: on_time=2026-05-17 16:52:15.982000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00199: on_time=2026-05-17 16:52:16.608000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00200: on_time=2026-05-17 16:52:17.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00201: on_time=2026-05-17 16:52:17.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00202: on_time=2026-05-17 16:52:18.324000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00203: on_time=2026-05-17 16:52:18.846000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00204: on_time=2026-05-17 16:52:19.320000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00205: on_time=2026-05-17 16:52:19.868000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00206: on_time=2026-05-17 16:52:20.716000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00207: on_time=2026-05-17 16:52:21.302000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00208: on_time=2026-05-17 16:52:21.824000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00209: on_time=2026-05-17 16:52:23.966000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00210: on_time=2026-05-17 16:52:24.478000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00211: on_time=2026-05-17 16:52:26.054000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00212: on_time=2026-05-17 16:52:26.532000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00213: on_time=2026-05-17 16:52:27.500000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00214: on_time=2026-05-17 16:52:28.224000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00215: on_time=2026-05-17 16:52:29.104000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00216: on_time=2026-05-17 16:52:34.320000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00217: on_time=2026-05-17 16:52:39.388000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00218: on_time=2026-05-17 16:52:40.710000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00219: on_time=2026-05-17 16:52:41.484000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00220: on_time=2026-05-17 16:52:42.236000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00221: on_time=2026-05-17 16:52:43.006000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00222: on_time=2026-05-17 16:52:43.734000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00223: on_time=2026-05-17 16:52:44.536000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00224: on_time=2026-05-17 16:52:45.382000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00225: on_time=2026-05-17 16:52:54.784000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00226: on_time=2026-05-17 16:52:55.506000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00227: on_time=2026-05-17 16:52:56.098000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00228: on_time=2026-05-17 16:52:56.666000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00229: on_time=2026-05-17 16:52:57.238000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00230: on_time=2026-05-17 16:52:57.882000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00231: on_time=2026-05-17 16:52:58.572000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00232: on_time=2026-05-17 16:52:59.246000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00233: on_time=2026-05-17 16:52:59.870000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00234: on_time=2026-05-17 16:53:00.590000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00235: on_time=2026-05-17 16:53:01.294000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00236: on_time=2026-05-17 16:53:01.942000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00237: on_time=2026-05-17 16:53:02.506000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00238: on_time=2026-05-17 16:53:03.322000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00239: on_time=2026-05-17 16:53:09.952000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00240: on_time=2026-05-17 16:53:24.060000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00241: on_time=2026-05-17 16:53:26.246000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00242: on_time=2026-05-17 16:53:28.334000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00243: on_time=2026-05-17 16:53:30.490000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00244: on_time=2026-05-17 16:53:34.120000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00245: on_time=2026-05-17 16:53:35.878000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00246: on_time=2026-05-17 16:53:39.474000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00247: on_time=2026-05-17 16:53:41.486000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00248: on_time=2026-05-17 16:53:43.318000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

T1_N2_Nodal1_T1_N2_E00249: on_time=2026-05-17 16:53:45.284000
  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00250: on_time=2026-05-17 16:53:49.486000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00251: on_time=2026-05-17 16:53:54.432000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00252: on_time=2026-05-17 16:53:57.762000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00253: on_time=2026-05-17 16:54:03.350000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00254: on_time=2026-05-17 16:54:07.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00255: on_time=2026-05-17 16:54:11.142000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00256: on_time=2026-05-17 16:54:15.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00257: on_time=2026-05-17 16:54:19.296000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00258: on_time=2026-05-17 16:54:20.544000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00259: on_time=2026-05-17 16:54:23.988000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00260: on_time=2026-05-17 16:54:39.410000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00261: on_time=2026-05-17 16:55:31.364000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00262: on_time=2026-05-17 16:55:32.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00263: on_time=2026-05-17 16:55:32.676000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00264: on_time=2026-05-17 16:55:33.554000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00265: on_time=2026-05-17 16:55:34.264000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00266: on_time=2026-05-17 16:55:34.860000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00267: on_time=2026-05-17 16:55:35.972000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00268: on_time=2026-05-17 16:55:36.670000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00269: on_time=2026-05-17 16:55:37.314000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00270: on_time=2026-05-17 16:55:37.952000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00271: on_time=2026-05-17 16:55:39.174000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00272: on_time=2026-05-17 16:55:39.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00273: on_time=2026-05-17 16:55:41.004000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00274: on_time=2026-05-17 16:55:41.568000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00275: on_time=2026-05-17 16:55:42.138000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00276: on_time=2026-05-17 16:55:42.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00277: on_time=2026-05-17 16:55:43.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00278: on_time=2026-05-17 16:55:43.872000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00279: on_time=2026-05-17 16:55:44.890000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00280: on_time=2026-05-17 16:55:46.176000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00281: on_time=2026-05-17 16:55:46.698000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00282: on_time=2026-05-17 16:55:47.252000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00283: on_time=2026-05-17 16:55:47.802000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00284: on_time=2026-05-17 16:55:48.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00285: on_time=2026-05-17 16:55:48.766000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00286: on_time=2026-05-17 16:55:50.160000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00287: on_time=2026-05-17 16:55:50.830000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00288: on_time=2026-05-17 16:55:51.316000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00289: on_time=2026-05-17 16:55:52.290000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00290: on_time=2026-05-17 16:55:52.878000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00291: on_time=2026-05-17 16:55:54.086000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00292: on_time=2026-05-17 16:55:54.636000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00293: on_time=2026-05-17 16:55:55.702000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00294: on_time=2026-05-17 16:55:56.278000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00295: on_time=2026-05-17 16:55:56.876000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00296: on_time=2026-05-17 16:55:57.462000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00297: on_time=2026-05-17 16:55:58.122000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00298: on_time=2026-05-17 16:55:58.756000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00299: on_time=2026-05-17 16:55:59.354000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00300: on_time=2026-05-17 16:56:00.766000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00301: on_time=2026-05-17 16:56:01.288000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00302: on_time=2026-05-17 16:56:01.750000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00303: on_time=2026-05-17 16:56:02.856000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 78 traces, 26 receivers

T1_N2_Nodal1_T1_N2_E00304: on_time=2026-05-17 16:56:53.728000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00305: on_time=2026-05-17 16:56:54.742000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 84 traces, 28 receivers

T1_N2_Nodal1_T1_N2_E00306: on_time=2026-05-17 16:57:07.590000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 87 traces, 29 receivers

T1_N2_Nodal1_T1_N2_E00307: on_time=2026-05-17 16:57:40.804000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00308: on_time=2026-05-17 16:57:45.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00309: on_time=2026-05-17 16:57:47.710000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00310: on_time=2026-05-17 16:57:50.466000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00311: on_time=2026-05-17 16:57:53.308000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00312: on_time=2026-05-17 16:57:56.724000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00313: on_time=2026-05-17 16:57:58.296000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00314: on_time=2026-05-17 16:58:02.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00315: on_time=2026-05-17 16:58:06.900000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00316: on_time=2026-05-17 16:58:10.452000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00317: on_time=2026-05-17 16:58:12.542000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00318: on_time=2026-05-17 16:58:16.764000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00319: on_time=2026-05-17 16:58:22.128000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00320: on_time=2026-05-17 16:58:25.226000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00321: on_time=2026-05-17 16:58:34.068000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00322: on_time=2026-05-17 16:58:37.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00323: on_time=2026-05-17 16:58:44.872000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00324: on_time=2026-05-17 16:58:47.836000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00325: on_time=2026-05-17 16:58:51.742000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00326: on_time=2026-05-17 16:58:55.290000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00327: on_time=2026-05-17 16:58:58.586000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00328: on_time=2026-05-17 16:59:01.342000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00329: on_time=2026-05-17 16:59:07.390000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00330: on_time=2026-05-17 16:59:10.484000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00331: on_time=2026-05-17 16:59:11.328000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00332: on_time=2026-05-17 16:59:16.508000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00333: on_time=2026-05-17 16:59:20.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00334: on_time=2026-05-17 16:59:23.760000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00335: on_time=2026-05-17 17:00:01.932000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00336: on_time=2026-05-17 17:00:06.624000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00337: on_time=2026-05-17 17:00:07.252000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00338: on_time=2026-05-17 17:00:08.178000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00339: on_time=2026-05-17 17:00:09.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00340: on_time=2026-05-17 17:00:13.548000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00341: on_time=2026-05-17 17:00:19.908000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00342: on_time=2026-05-17 17:00:23.236000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00343: on_time=2026-05-17 17:00:26.006000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00344: on_time=2026-05-17 17:00:26.746000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00345: on_time=2026-05-17 17:00:41.096000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00346: on_time=2026-05-17 17:00:48.986000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00347: on_time=2026-05-17 17:00:58.482000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00348: on_time=2026-05-17 17:01:07.410000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00349: on_time=2026-05-17 17:01:22.496000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00350: on_time=2026-05-17 17:01:29.046000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00351: on_time=2026-05-17 17:01:39.350000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00352: on_time=2026-05-17 17:01:40.210000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00353: on_time=2026-05-17 17:01:42.156000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00354: on_time=2026-05-17 17:01:44.510000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00355: on_time=2026-05-17 17:01:46.066000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00356: on_time=2026-05-17 17:01:48.612000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00357: on_time=2026-05-17 17:01:49.896000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00358: on_time=2026-05-17 17:01:51.122000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00359: on_time=2026-05-17 17:01:52.676000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00360: on_time=2026-05-17 17:01:54.610000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00361: on_time=2026-05-17 17:01:56.216000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00362: on_time=2026-05-17 17:01:56.846000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00363: on_time=2026-05-17 17:01:57.400000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00364: on_time=2026-05-17 17:01:57.922000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00365: on_time=2026-05-17 17:02:00.348000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00366: on_time=2026-05-17 17:02:07.388000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00367: on_time=2026-05-17 17:02:07.980000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00368: on_time=2026-05-17 17:02:08.452000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00369: on_time=2026-05-17 17:02:08.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00370: on_time=2026-05-17 17:02:09.382000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00371: on_time=2026-05-17 17:02:09.998000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00372: on_time=2026-05-17 17:02:10.426000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00373: on_time=2026-05-17 17:02:11.690000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00374: on_time=2026-05-17 17:02:12.326000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00375: on_time=2026-05-17 17:02:12.858000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00376: on_time=2026-05-17 17:02:14.602000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00377: on_time=2026-05-17 17:02:15.124000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00378: on_time=2026-05-17 17:02:15.906000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00379: on_time=2026-05-17 17:02:17.600000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00380: on_time=2026-05-17 17:02:32.332000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 96 traces, 32 receivers

T1_N2_Nodal1_T1_N2_E00381: on_time=2026-05-17 17:03:52.602000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00382: on_time=2026-05-17 17:03:58.650000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00383: on_time=2026-05-17 17:04:05.714000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00384: on_time=2026-05-17 17:04:07.640000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00385: on_time=2026-05-17 17:04:08.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00386: on_time=2026-05-17 17:04:08.596000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00387: on_time=2026-05-17 17:04:08.998000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00388: on_time=2026-05-17 17:04:09.376000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00389: on_time=2026-05-17 17:04:09.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00390: on_time=2026-05-17 17:04:13.890000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00391: on_time=2026-05-17 17:04:14.334000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00392: on_time=2026-05-17 17:04:14.770000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00393: on_time=2026-05-17 17:04:15.190000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00394: on_time=2026-05-17 17:04:20.468000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00395: on_time=2026-05-17 17:04:21.440000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00396: on_time=2026-05-17 17:04:22.478000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00397: on_time=2026-05-17 17:04:24.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00398: on_time=2026-05-17 17:04:26.632000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00399: on_time=2026-05-17 17:04:27.510000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00400: on_time=2026-05-17 17:04:28.942000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00401: on_time=2026-05-17 17:04:30.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00402: on_time=2026-05-17 17:04:30.878000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00403: on_time=2026-05-17 17:04:31.270000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00404: on_time=2026-05-17 17:04:32.174000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00405: on_time=2026-05-17 17:04:33.018000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00406: on_time=2026-05-17 17:04:35.022000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00407: on_time=2026-05-17 17:04:36.706000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00408: on_time=2026-05-17 17:04:37.248000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00409: on_time=2026-05-17 17:04:38.248000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00410: on_time=2026-05-17 17:04:38.726000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00411: on_time=2026-05-17 17:04:39.194000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00412: on_time=2026-05-17 17:04:39.688000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00413: on_time=2026-05-17 17:04:41.378000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00414: on_time=2026-05-17 17:04:42.428000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00415: on_time=2026-05-17 17:04:43.466000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00416: on_time=2026-05-17 17:04:44.060000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00417: on_time=2026-05-17 17:04:44.652000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00418: on_time=2026-05-17 17:04:45.170000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00419: on_time=2026-05-17 17:04:45.770000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00420: on_time=2026-05-17 17:04:46.834000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00421: on_time=2026-05-17 17:04:48.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00422: on_time=2026-05-17 17:04:49.050000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00423: on_time=2026-05-17 17:04:50.058000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00424: on_time=2026-05-17 17:04:50.866000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00425: on_time=2026-05-17 17:04:52.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00426: on_time=2026-05-17 17:04:54.230000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00427: on_time=2026-05-17 17:04:54.464000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00428: on_time=2026-05-17 17:04:55.358000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00429: on_time=2026-05-17 17:04:56.084000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00430: on_time=2026-05-17 17:04:57.594000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00431: on_time=2026-05-17 17:04:58.650000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00432: on_time=2026-05-17 17:04:59.640000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00433: on_time=2026-05-17 17:05:00.936000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00434: on_time=2026-05-17 17:05:01.530000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00435: on_time=2026-05-17 17:05:03.894000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00436: on_time=2026-05-17 17:05:04.820000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00437: on_time=2026-05-17 17:05:05.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00438: on_time=2026-05-17 17:05:06.458000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00439: on_time=2026-05-17 17:05:07.406000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00440: on_time=2026-05-17 17:05:07.812000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00441: on_time=2026-05-17 17:05:08.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00442: on_time=2026-05-17 17:05:08.716000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00443: on_time=2026-05-17 17:05:09.160000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00444: on_time=2026-05-17 17:05:10.646000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00445: on_time=2026-05-17 17:05:12.036000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00446: on_time=2026-05-17 17:05:12.424000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00447: on_time=2026-05-17 17:05:13.512000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00448: on_time=2026-05-17 17:05:13.920000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00449: on_time=2026-05-17 17:05:14.318000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00450: on_time=2026-05-17 17:05:17.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00451: on_time=2026-05-17 17:05:19.260000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00452: on_time=2026-05-17 17:05:19.854000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00453: on_time=2026-05-17 17:05:20.366000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

T1_N2_Nodal1_T1_N2_E00454: on_time=2026-05-17 17:05:20.850000
  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00455: on_time=2026-05-17 17:05:21.338000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00456: on_time=2026-05-17 17:05:25.312000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00457: on_time=2026-05-17 17:05:25.878000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00458: on_time=2026-05-17 17:05:26.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00459: on_time=2026-05-17 17:05:29.346000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00460: on_time=2026-05-17 17:05:30.126000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00461: on_time=2026-05-17 17:05:30.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00462: on_time=2026-05-17 17:05:31.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00463: on_time=2026-05-17 17:05:31.792000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00464: on_time=2026-05-17 17:05:33.298000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00465: on_time=2026-05-17 17:05:34.556000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00466: on_time=2026-05-17 17:05:36.282000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00467: on_time=2026-05-17 17:05:37.312000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00468: on_time=2026-05-17 17:05:38.268000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00469: on_time=2026-05-17 17:05:39.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00470: on_time=2026-05-17 17:05:40.618000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00471: on_time=2026-05-17 17:05:41.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00472: on_time=2026-05-17 17:05:43.040000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00473: on_time=2026-05-17 17:05:44.466000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00474: on_time=2026-05-17 17:05:45.760000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00475: on_time=2026-05-17 17:05:47.574000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00476: on_time=2026-05-17 17:05:48.548000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00477: on_time=2026-05-17 17:05:55.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00478: on_time=2026-05-17 17:05:59.426000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00479: on_time=2026-05-17 17:06:00.402000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00480: on_time=2026-05-17 17:06:02.120000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00481: on_time=2026-05-17 17:06:03.048000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00482: on_time=2026-05-17 17:06:04.048000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00483: on_time=2026-05-17 17:06:06.520000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00484: on_time=2026-05-17 17:06:07.184000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00485: on_time=2026-05-17 17:06:07.832000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00486: on_time=2026-05-17 17:06:08.502000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00487: on_time=2026-05-17 17:06:09.248000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00488: on_time=2026-05-17 17:06:10.392000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00489: on_time=2026-05-17 17:06:19.444000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00490: on_time=2026-05-17 17:06:20.840000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00491: on_time=2026-05-17 17:06:22.268000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00492: on_time=2026-05-17 17:06:23.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00493: on_time=2026-05-17 17:06:25.430000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00494: on_time=2026-05-17 17:06:27.036000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00495: on_time=2026-05-17 17:06:37.080000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00496: on_time=2026-05-17 17:06:39.386000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00497: on_time=2026-05-17 17:06:54.394000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00498: on_time=2026-05-17 17:06:54.952000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00499: on_time=2026-05-17 17:06:55.870000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00500: on_time=2026-05-17 17:06:56.548000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00501: on_time=2026-05-17 17:06:57.180000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00502: on_time=2026-05-17 17:06:57.832000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00503: on_time=2026-05-17 17:06:59.096000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00504: on_time=2026-05-17 17:06:59.800000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00505: on_time=2026-05-17 17:07:00.480000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00506: on_time=2026-05-17 17:07:01.148000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00507: on_time=2026-05-17 17:07:02.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00508: on_time=2026-05-17 17:07:02.728000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00509: on_time=2026-05-17 17:07:03.442000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00510: on_time=2026-05-17 17:07:04.952000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00511: on_time=2026-05-17 17:07:05.592000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00512: on_time=2026-05-17 17:07:06.470000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00513: on_time=2026-05-17 17:07:07.106000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00514: on_time=2026-05-17 17:07:07.676000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00515: on_time=2026-05-17 17:07:08.274000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00516: on_time=2026-05-17 17:07:08.822000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00517: on_time=2026-05-17 17:07:09.694000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00518: on_time=2026-05-17 17:07:10.354000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00519: on_time=2026-05-17 17:07:20.370000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00520: on_time=2026-05-17 17:07:27.324000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00521: on_time=2026-05-17 17:07:29.414000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00522: on_time=2026-05-17 17:07:32.430000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00523: on_time=2026-05-17 17:07:35.620000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00524: on_time=2026-05-17 17:07:35.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00525: on_time=2026-05-17 17:07:37.850000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00526: on_time=2026-05-17 17:08:01.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00527: on_time=2026-05-17 17:08:05.398000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00528: on_time=2026-05-17 17:08:12.770000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00529: on_time=2026-05-17 17:08:20.466000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00530: on_time=2026-05-17 17:08:23.572000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00531: on_time=2026-05-17 17:08:29.556000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00532: on_time=2026-05-17 17:08:30.120000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00533: on_time=2026-05-17 17:08:39.824000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00534: on_time=2026-05-17 17:08:41.272000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00535: on_time=2026-05-17 17:08:43.894000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00536: on_time=2026-05-17 17:08:46.366000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00537: on_time=2026-05-17 17:08:47.524000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00538: on_time=2026-05-17 17:09:22.372000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00539: on_time=2026-05-17 17:09:31.316000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00540: on_time=2026-05-17 17:09:35.288000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00541: on_time=2026-05-17 17:09:41.748000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00542: on_time=2026-05-17 17:09:46.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00543: on_time=2026-05-17 17:10:01.848000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00544: on_time=2026-05-17 17:10:05.076000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00545: on_time=2026-05-17 17:10:07.998000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00546: on_time=2026-05-17 17:10:10.674000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00547: on_time=2026-05-17 17:10:13.574000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00548: on_time=2026-05-17 17:10:16.260000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00549: on_time=2026-05-17 17:10:29.164000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00550: on_time=2026-05-17 17:10:44.236000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00551: on_time=2026-05-17 17:10:47.132000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00552: on_time=2026-05-17 17:10:49.700000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00553: on_time=2026-05-17 17:10:52.204000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00554: on_time=2026-05-17 17:10:54.738000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00555: on_time=2026-05-17 17:10:57.350000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00556: on_time=2026-05-17 17:10:59.996000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00557: on_time=2026-05-17 17:11:02.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00558: on_time=2026-05-17 17:11:05.370000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00559: on_time=2026-05-17 17:11:08.102000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00560: on_time=2026-05-17 17:11:11.730000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00561: on_time=2026-05-17 17:11:13.682000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00562: on_time=2026-05-17 17:11:33.378000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00563: on_time=2026-05-17 17:11:40.118000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00564: on_time=2026-05-17 17:11:44.162000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00565: on_time=2026-05-17 17:11:46.688000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00566: on_time=2026-05-17 17:11:49.068000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00567: on_time=2026-05-17 17:11:51.564000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00568: on_time=2026-05-17 17:11:53.876000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00569: on_time=2026-05-17 17:11:56.268000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00570: on_time=2026-05-17 17:12:04.570000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00571: on_time=2026-05-17 17:12:06.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00572: on_time=2026-05-17 17:12:11.100000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00573: on_time=2026-05-17 17:12:11.690000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00574: on_time=2026-05-17 17:12:13.654000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00575: on_time=2026-05-17 17:12:19.794000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00576: on_time=2026-05-17 17:12:21.642000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00577: on_time=2026-05-17 17:12:26.842000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00578: on_time=2026-05-17 17:12:28.898000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00579: on_time=2026-05-17 17:12:31.682000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00580: on_time=2026-05-17 17:12:34.806000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00581: on_time=2026-05-17 17:12:37.596000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00582: on_time=2026-05-17 17:12:40.522000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00583: on_time=2026-05-17 17:12:42.210000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00584: on_time=2026-05-17 17:12:43.650000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00585: on_time=2026-05-17 17:12:48.130000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00586: on_time=2026-05-17 17:12:51.948000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00587: on_time=2026-05-17 17:12:53.502000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00588: on_time=2026-05-17 17:12:58.850000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00589: on_time=2026-05-17 17:13:12.706000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00590: on_time=2026-05-17 17:13:15.872000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00591: on_time=2026-05-17 17:13:21.204000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00592: on_time=2026-05-17 17:13:26.174000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00593: on_time=2026-05-17 17:13:28.906000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00594: on_time=2026-05-17 17:13:31.300000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00595: on_time=2026-05-17 17:13:34.144000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00596: on_time=2026-05-17 17:13:36.930000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00597: on_time=2026-05-17 17:13:39.696000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00598: on_time=2026-05-17 17:13:42.506000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00599: on_time=2026-05-17 17:13:45.318000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00600: on_time=2026-05-17 17:13:48.140000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00601: on_time=2026-05-17 17:13:51.048000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00602: on_time=2026-05-17 17:13:54.058000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00603: on_time=2026-05-17 17:13:58.608000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00604: on_time=2026-05-17 17:14:10.420000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00605: on_time=2026-05-17 17:14:14.690000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00606: on_time=2026-05-17 17:14:17.776000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00607: on_time=2026-05-17 17:14:20.844000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00608: on_time=2026-05-17 17:14:23.770000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00609: on_time=2026-05-17 17:14:26.500000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00610: on_time=2026-05-17 17:14:29.484000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00611: on_time=2026-05-17 17:14:32.466000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00612: on_time=2026-05-17 17:14:35.666000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00613: on_time=2026-05-17 17:14:36.780000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00614: on_time=2026-05-17 17:14:41.326000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00615: on_time=2026-05-17 17:14:47.344000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00616: on_time=2026-05-17 17:14:48.152000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00617: on_time=2026-05-17 17:14:49.918000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00618: on_time=2026-05-17 17:15:08.524000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00619: on_time=2026-05-17 17:15:11.938000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00620: on_time=2026-05-17 17:15:15.596000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00621: on_time=2026-05-17 17:15:18.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00622: on_time=2026-05-17 17:15:20.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00623: on_time=2026-05-17 17:15:23.236000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00624: on_time=2026-05-17 17:15:25.746000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00625: on_time=2026-05-17 17:15:28.340000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00626: on_time=2026-05-17 17:15:30.756000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00627: on_time=2026-05-17 17:15:33.250000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00628: on_time=2026-05-17 17:15:35.842000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00629: on_time=2026-05-17 17:15:38.528000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00630: on_time=2026-05-17 17:15:40.014000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00631: on_time=2026-05-17 17:15:41.476000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00632: on_time=2026-05-17 17:15:44.600000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00633: on_time=2026-05-17 17:15:45.974000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00634: on_time=2026-05-17 17:15:52.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00635: on_time=2026-05-17 17:15:55.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00636: on_time=2026-05-17 17:16:01.894000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00637: on_time=2026-05-17 17:16:17.954000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00638: on_time=2026-05-17 17:16:24.362000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00639: on_time=2026-05-17 17:16:27.226000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00640: on_time=2026-05-17 17:16:29.970000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00641: on_time=2026-05-17 17:16:32.684000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00642: on_time=2026-05-17 17:16:35.520000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00643: on_time=2026-05-17 17:16:38.334000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00644: on_time=2026-05-17 17:16:41.224000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00645: on_time=2026-05-17 17:16:44.142000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00646: on_time=2026-05-17 17:16:47.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00647: on_time=2026-05-17 17:16:50.064000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00648: on_time=2026-05-17 17:16:58.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00649: on_time=2026-05-17 17:17:13.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00650: on_time=2026-05-17 17:17:16.368000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00651: on_time=2026-05-17 17:17:19.126000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00652: on_time=2026-05-17 17:17:21.788000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00653: on_time=2026-05-17 17:17:24.338000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00654: on_time=2026-05-17 17:17:27.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00655: on_time=2026-05-17 17:17:31.192000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00656: on_time=2026-05-17 17:17:39.366000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00657: on_time=2026-05-17 17:17:42.588000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00658: on_time=2026-05-17 17:17:45.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00659: on_time=2026-05-17 17:17:48.194000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00660: on_time=2026-05-17 17:17:57.794000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00661: on_time=2026-05-17 17:18:09.092000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00662: on_time=2026-05-17 17:18:22.680000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00663: on_time=2026-05-17 17:18:31.060000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00664: on_time=2026-05-17 17:18:43.558000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00665: on_time=2026-05-17 17:18:45.992000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00666: on_time=2026-05-17 17:18:53.114000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00667: on_time=2026-05-17 17:18:55.736000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00668: on_time=2026-05-17 17:18:58.330000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00669: on_time=2026-05-17 17:19:00.866000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00670: on_time=2026-05-17 17:19:03.418000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00671: on_time=2026-05-17 17:19:05.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00672: on_time=2026-05-17 17:19:23.580000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00673: on_time=2026-05-17 17:19:25.976000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00674: on_time=2026-05-17 17:19:28.374000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00675: on_time=2026-05-17 17:19:30.872000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00676: on_time=2026-05-17 17:19:33.430000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00677: on_time=2026-05-17 17:19:35.842000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00678: on_time=2026-05-17 17:19:38.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00679: on_time=2026-05-17 17:19:40.650000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00680: on_time=2026-05-17 17:19:43.068000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00681: on_time=2026-05-17 17:19:45.518000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00682: on_time=2026-05-17 17:19:48.320000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00683: on_time=2026-05-17 17:19:54.530000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00684: on_time=2026-05-17 17:19:57.550000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00685: on_time=2026-05-17 17:20:00.292000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00686: on_time=2026-05-17 17:20:03.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00687: on_time=2026-05-17 17:20:06.082000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00688: on_time=2026-05-17 17:20:13.624000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00689: on_time=2026-05-17 17:20:30.184000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00690: on_time=2026-05-17 17:20:44.138000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00691: on_time=2026-05-17 17:20:46.662000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00692: on_time=2026-05-17 17:20:55.516000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00693: on_time=2026-05-17 17:20:58.854000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00694: on_time=2026-05-17 17:21:01.724000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00695: on_time=2026-05-17 17:21:04.392000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00696: on_time=2026-05-17 17:21:07.102000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00697: on_time=2026-05-17 17:21:09.620000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00698: on_time=2026-05-17 17:21:12.162000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00699: on_time=2026-05-17 17:21:14.920000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00700: on_time=2026-05-17 17:21:18.978000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00701: on_time=2026-05-17 17:21:21.676000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00702: on_time=2026-05-17 17:21:45.394000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00703: on_time=2026-05-17 17:21:47.948000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00704: on_time=2026-05-17 17:21:50.288000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00705: on_time=2026-05-17 17:21:52.680000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00706: on_time=2026-05-17 17:21:55.140000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00707: on_time=2026-05-17 17:21:57.594000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00708: on_time=2026-05-17 17:21:59.888000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00709: on_time=2026-05-17 17:22:02.314000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00710: on_time=2026-05-17 17:22:04.884000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00711: on_time=2026-05-17 17:22:07.456000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00712: on_time=2026-05-17 17:22:14.606000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00713: on_time=2026-05-17 17:22:17.046000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00714: on_time=2026-05-17 17:22:24.412000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00715: on_time=2026-05-17 17:22:40.560000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00716: on_time=2026-05-17 17:22:47.054000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00717: on_time=2026-05-17 17:22:49.678000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00718: on_time=2026-05-17 17:22:52.008000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00719: on_time=2026-05-17 17:22:54.256000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00720: on_time=2026-05-17 17:22:56.650000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00721: on_time=2026-05-17 17:22:59.080000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00722: on_time=2026-05-17 17:23:01.432000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00723: on_time=2026-05-17 17:23:03.780000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00724: on_time=2026-05-17 17:23:06.220000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00725: on_time=2026-05-17 17:23:08.546000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00726: on_time=2026-05-17 17:23:15.382000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00727: on_time=2026-05-17 17:25:17.368000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00728: on_time=2026-05-17 17:25:20.320000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00729: on_time=2026-05-17 17:25:22.970000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00730: on_time=2026-05-17 17:25:25.556000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00731: on_time=2026-05-17 17:25:29.192000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00732: on_time=2026-05-17 17:25:34.824000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 99 traces, 33 receivers

T1_N2_Nodal1_T1_N2_E00733: on_time=2026-05-17 17:25:45.938000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00734: on_time=2026-05-17 17:25:55.704000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00735: on_time=2026-05-17 17:26:00.506000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00736: on_time=2026-05-17 17:26:04.856000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00737: on_time=2026-05-17 17:26:08.636000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00738: on_time=2026-05-17 17:26:12.410000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00739: on_time=2026-05-17 17:26:16.868000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00740: on_time=2026-05-17 17:26:21.064000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00741: on_time=2026-05-17 17:26:25.484000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00742: on_time=2026-05-17 17:26:29.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00743: on_time=2026-05-17 17:26:33.838000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00744: on_time=2026-05-17 17:26:44.496000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00745: on_time=2026-05-17 17:26:49.252000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00746: on_time=2026-05-17 17:26:51.512000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00747: on_time=2026-05-17 17:27:02.678000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00748: on_time=2026-05-17 17:27:05.262000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00749: on_time=2026-05-17 17:27:07.602000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00750: on_time=2026-05-17 17:27:09.950000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00751: on_time=2026-05-17 17:27:12.484000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00752: on_time=2026-05-17 17:27:16.052000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00753: on_time=2026-05-17 17:27:18.428000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00754: on_time=2026-05-17 17:27:26.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00755: on_time=2026-05-17 17:27:29.998000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00756: on_time=2026-05-17 17:27:33.520000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00757: on_time=2026-05-17 17:27:38.596000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00758: on_time=2026-05-17 17:28:08.014000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00759: on_time=2026-05-17 17:28:11.096000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00760: on_time=2026-05-17 17:28:23.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00761: on_time=2026-05-17 17:28:29.336000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00762: on_time=2026-05-17 17:28:31.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00763: on_time=2026-05-17 17:28:41.882000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00764: on_time=2026-05-17 17:28:57.740000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00765: on_time=2026-05-17 17:29:05.768000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00766: on_time=2026-05-17 17:30:00.080000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00767: on_time=2026-05-17 17:30:03.216000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00768: on_time=2026-05-17 17:30:05.610000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00769: on_time=2026-05-17 17:30:08.110000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00770: on_time=2026-05-17 17:30:10.600000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00771: on_time=2026-05-17 17:30:12.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00772: on_time=2026-05-17 17:30:15.382000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00773: on_time=2026-05-17 17:30:17.642000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00774: on_time=2026-05-17 17:30:20.260000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00775: on_time=2026-05-17 17:30:24.806000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00776: on_time=2026-05-17 17:30:28.586000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00777: on_time=2026-05-17 17:30:35.076000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00778: on_time=2026-05-17 17:30:44.040000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00779: on_time=2026-05-17 17:30:54.114000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00780: on_time=2026-05-17 17:30:57.548000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00781: on_time=2026-05-17 17:31:02.290000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00782: on_time=2026-05-17 17:31:42.898000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00783: on_time=2026-05-17 17:31:55.256000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00784: on_time=2026-05-17 17:32:28.378000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00785: on_time=2026-05-17 17:32:31.690000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00786: on_time=2026-05-17 17:32:33.374000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00787: on_time=2026-05-17 17:32:35.108000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00788: on_time=2026-05-17 17:32:38.022000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00789: on_time=2026-05-17 17:32:50.884000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00790: on_time=2026-05-17 17:32:59.454000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00791: on_time=2026-05-17 17:33:28.904000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00792: on_time=2026-05-17 17:35:57.036000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00793: on_time=2026-05-17 17:35:59.922000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00794: on_time=2026-05-17 17:36:02.464000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00795: on_time=2026-05-17 17:36:04.602000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00796: on_time=2026-05-17 17:36:06.398000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00797: on_time=2026-05-17 17:36:13.334000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00798: on_time=2026-05-17 17:36:21.846000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00799: on_time=2026-05-17 17:36:24.446000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00800: on_time=2026-05-17 17:36:26.888000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00801: on_time=2026-05-17 17:36:29.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00802: on_time=2026-05-17 17:36:30.114000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00803: on_time=2026-05-17 17:36:32.806000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00804: on_time=2026-05-17 17:36:35.836000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00805: on_time=2026-05-17 17:36:38.840000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00806: on_time=2026-05-17 17:36:43.192000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00807: on_time=2026-05-17 17:36:44.512000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00808: on_time=2026-05-17 17:36:57.788000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00809: on_time=2026-05-17 17:37:00.112000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00810: on_time=2026-05-17 17:37:02.568000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00811: on_time=2026-05-17 17:37:04.938000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00812: on_time=2026-05-17 17:37:07.310000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00813: on_time=2026-05-17 17:37:21.950000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00814: on_time=2026-05-17 17:37:24.176000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00815: on_time=2026-05-17 17:37:26.506000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00816: on_time=2026-05-17 17:37:28.836000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00817: on_time=2026-05-17 17:37:31.132000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00818: on_time=2026-05-17 17:37:32.380000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00819: on_time=2026-05-17 17:37:34.406000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00820: on_time=2026-05-17 17:37:36.324000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00821: on_time=2026-05-17 17:37:55.382000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00822: on_time=2026-05-17 17:38:01.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00823: on_time=2026-05-17 17:38:05.240000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00824: on_time=2026-05-17 17:38:08.922000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00825: on_time=2026-05-17 17:38:12.256000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00826: on_time=2026-05-17 17:38:15.062000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00827: on_time=2026-05-17 17:38:15.662000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00828: on_time=2026-05-17 17:38:19.710000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00829: on_time=2026-05-17 17:38:21.726000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00830: on_time=2026-05-17 17:38:31.208000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00831: on_time=2026-05-17 17:38:34.068000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00832: on_time=2026-05-17 17:38:36.588000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00833: on_time=2026-05-17 17:38:39.108000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00834: on_time=2026-05-17 17:38:41.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00835: on_time=2026-05-17 17:38:54.920000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00836: on_time=2026-05-17 17:41:59.536000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00837: on_time=2026-05-17 17:42:59.038000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00838: on_time=2026-05-17 17:43:02.090000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00839: on_time=2026-05-17 17:43:04.770000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00840: on_time=2026-05-17 17:43:07.860000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00841: on_time=2026-05-17 17:43:11.004000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00842: on_time=2026-05-17 17:43:13.882000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00843: on_time=2026-05-17 17:43:16.594000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00844: on_time=2026-05-17 17:43:19.202000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00845: on_time=2026-05-17 17:43:21.900000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00846: on_time=2026-05-17 17:43:24.524000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00847: on_time=2026-05-17 17:43:30.798000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00848: on_time=2026-05-17 17:43:51.266000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00849: on_time=2026-05-17 17:43:54.104000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00850: on_time=2026-05-17 17:43:56.952000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00851: on_time=2026-05-17 17:43:59.560000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00852: on_time=2026-05-17 17:44:02.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00853: on_time=2026-05-17 17:44:04.746000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00854: on_time=2026-05-17 17:44:07.308000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00855: on_time=2026-05-17 17:44:09.922000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00856: on_time=2026-05-17 17:44:12.574000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00857: on_time=2026-05-17 17:44:15.098000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00858: on_time=2026-05-17 17:44:20.212000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00859: on_time=2026-05-17 17:44:23.834000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00860: on_time=2026-05-17 17:44:25.096000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00861: on_time=2026-05-17 17:44:27.784000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00862: on_time=2026-05-17 17:44:29.568000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00863: on_time=2026-05-17 17:44:31.638000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00864: on_time=2026-05-17 17:44:44.020000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00865: on_time=2026-05-17 17:44:45.442000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00866: on_time=2026-05-17 17:44:56.020000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00867: on_time=2026-05-17 17:45:40.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00868: on_time=2026-05-17 17:46:01.274000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00869: on_time=2026-05-17 17:46:29.270000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00870: on_time=2026-05-17 17:46:32.504000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00871: on_time=2026-05-17 17:46:35.144000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00872: on_time=2026-05-17 17:46:35.850000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00873: on_time=2026-05-17 17:46:39.936000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00874: on_time=2026-05-17 17:46:45.664000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00875: on_time=2026-05-17 17:46:48.260000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00876: on_time=2026-05-17 17:46:50.536000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00877: on_time=2026-05-17 17:46:53.404000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00878: on_time=2026-05-17 17:46:55.612000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00879: on_time=2026-05-17 17:46:56.244000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00880: on_time=2026-05-17 17:46:56.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00881: on_time=2026-05-17 17:46:58.662000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00882: on_time=2026-05-17 17:46:59.212000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00883: on_time=2026-05-17 17:47:00.334000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00884: on_time=2026-05-17 17:47:02.590000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00885: on_time=2026-05-17 17:47:03.638000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00886: on_time=2026-05-17 17:47:11.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00887: on_time=2026-05-17 17:47:12.810000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00888: on_time=2026-05-17 17:47:13.930000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00889: on_time=2026-05-17 17:47:15.418000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00890: on_time=2026-05-17 17:47:16.676000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00891: on_time=2026-05-17 17:47:17.778000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00892: on_time=2026-05-17 17:47:21.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00893: on_time=2026-05-17 17:47:24.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00894: on_time=2026-05-17 17:48:25.234000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00895: on_time=2026-05-17 17:48:26.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00896: on_time=2026-05-17 17:48:27.002000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00897: on_time=2026-05-17 17:48:27.576000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00898: on_time=2026-05-17 17:48:28.736000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00899: on_time=2026-05-17 17:48:29.318000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00900: on_time=2026-05-17 17:48:44.238000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00901: on_time=2026-05-17 17:48:50.954000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00902: on_time=2026-05-17 17:48:52.122000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00903: on_time=2026-05-17 17:48:53.284000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00904: on_time=2026-05-17 17:48:54.452000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00905: on_time=2026-05-17 17:48:55.682000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00906: on_time=2026-05-17 17:48:56.910000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00907: on_time=2026-05-17 17:48:57.518000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00908: on_time=2026-05-17 17:48:58.142000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00909: on_time=2026-05-17 17:48:59.352000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00910: on_time=2026-05-17 17:49:00.532000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00911: on_time=2026-05-17 17:49:01.738000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00912: on_time=2026-05-17 17:49:02.348000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00913: on_time=2026-05-17 17:49:02.926000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00914: on_time=2026-05-17 17:49:09.024000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00915: on_time=2026-05-17 17:51:39.448000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00916: on_time=2026-05-17 17:51:43.328000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00917: on_time=2026-05-17 17:51:46.450000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00918: on_time=2026-05-17 17:51:49.256000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00919: on_time=2026-05-17 17:51:52.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00920: on_time=2026-05-17 17:51:55.102000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00921: on_time=2026-05-17 17:52:05.476000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00922: on_time=2026-05-17 17:52:08.264000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00923: on_time=2026-05-17 17:52:11.756000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00924: on_time=2026-05-17 17:52:16.016000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00925: on_time=2026-05-17 17:52:23.434000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00926: on_time=2026-05-17 17:52:26.028000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00927: on_time=2026-05-17 17:52:31.828000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00928: on_time=2026-05-17 17:52:38.022000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00929: on_time=2026-05-17 17:52:40.956000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00930: on_time=2026-05-17 17:52:43.480000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00931: on_time=2026-05-17 17:52:46.436000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00932: on_time=2026-05-17 17:53:07.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00933: on_time=2026-05-17 17:53:10.830000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00934: on_time=2026-05-17 17:53:52.522000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00935: on_time=2026-05-17 17:53:55.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00936: on_time=2026-05-17 17:53:57.396000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00937: on_time=2026-05-17 17:53:59.620000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00938: on_time=2026-05-17 17:54:02.048000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00939: on_time=2026-05-17 17:54:04.252000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00940: on_time=2026-05-17 17:54:06.450000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00941: on_time=2026-05-17 17:54:08.622000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00942: on_time=2026-05-17 17:54:12.124000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00943: on_time=2026-05-17 17:54:26.256000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00944: on_time=2026-05-17 17:54:31.122000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00945: on_time=2026-05-17 17:54:36.734000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00946: on_time=2026-05-17 17:54:38.312000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00947: on_time=2026-05-17 17:54:46.396000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00948: on_time=2026-05-17 17:55:06.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00949: on_time=2026-05-17 17:55:06.896000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00950: on_time=2026-05-17 17:55:07.440000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00951: on_time=2026-05-17 17:55:08.006000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00952: on_time=2026-05-17 17:55:08.546000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00953: on_time=2026-05-17 17:55:23.034000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00954: on_time=2026-05-17 17:55:27.164000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00955: on_time=2026-05-17 17:55:31.842000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00956: on_time=2026-05-17 17:55:33.484000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00957: on_time=2026-05-17 17:55:35

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00958: on_time=2026-05-17 17:55:37.450000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00959: on_time=2026-05-17 17:56:04.556000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00960: on_time=2026-05-17 17:56:23.142000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00961: on_time=2026-05-17 17:56:51.946000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00962: on_time=2026-05-17 17:58:02.510000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00963: on_time=2026-05-17 17:59:37.510000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00964: on_time=2026-05-17 17:59:42.732000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00965: on_time=2026-05-17 17:59:45.508000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00966: on_time=2026-05-17 17:59:48.082000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00967: on_time=2026-05-17 17:59:50.726000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00968: on_time=2026-05-17 17:59:53.538000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00969: on_time=2026-05-17 17:59:56.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00970: on_time=2026-05-17 17:59:59.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00971: on_time=2026-05-17 18:00:02.254000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00972: on_time=2026-05-17 18:00:05.252000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00973: on_time=2026-05-17 18:00:08.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00974: on_time=2026-05-17 18:00:14.916000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00975: on_time=2026-05-17 18:00:22.646000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00976: on_time=2026-05-17 18:00:48.174000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00977: on_time=2026-05-17 18:00:51.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00978: on_time=2026-05-17 18:00:53.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00979: on_time=2026-05-17 18:00:55.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00980: on_time=2026-05-17 18:00:57.922000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00981: on_time=2026-05-17 18:00:59.882000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00982: on_time=2026-05-17 18:01:01.938000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00983: on_time=2026-05-17 18:01:04.270000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00984: on_time=2026-05-17 18:01:06.394000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00985: on_time=2026-05-17 18:01:08.436000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00986: on_time=2026-05-17 18:01:16.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00987: on_time=2026-05-17 18:01:18.868000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00988: on_time=2026-05-17 18:01:24.072000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00989: on_time=2026-05-17 18:01:26.598000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00990: on_time=2026-05-17 18:01:28.956000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00991: on_time=2026-05-17 18:01:31.172000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00992: on_time=2026-05-17 18:01:32.984000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00993: on_time=2026-05-17 18:01:37.200000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00994: on_time=2026-05-17 18:01:47.254000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00995: on_time=2026-05-17 18:01:49.814000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00996: on_time=2026-05-17 18:01:52.094000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00997: on_time=2026-05-17 18:01:54.458000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00998: on_time=2026-05-17 18:01:58.508000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E00999: on_time=2026-05-17 18:02:10.826000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01000: on_time=2026-05-17 18:02:13.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01001: on_time=2026-05-17 18:02:14.548000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01002: on_time=2026-05-17 18:02:16.172000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01003: on_time=2026-05-17 18:02:30.554000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01004: on_time=2026-05-17 18:03:46.710000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01005: on_time=2026-05-17 18:03:49.028000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01006: on_time=2026-05-17 18:03:49.264000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01007: on_time=2026-05-17 18:03:51.594000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01008: on_time=2026-05-17 18:03:53.882000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01009: on_time=2026-05-17 18:03:56.008000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01010: on_time=2026-05-17 18:03:58.122000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01011: on_time=2026-05-17 18:04:00.650000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01012: on_time=2026-05-17 18:04:03.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01013: on_time=2026-05-17 18:04:05.428000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01014: on_time=2026-05-17 18:04:09.330000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01015: on_time=2026-05-17 18:04:39.884000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01016: on_time=2026-05-17 18:04:42.186000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01017: on_time=2026-05-17 18:04:55.390000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01018: on_time=2026-05-17 18:04:56.124000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01019: on_time=2026-05-17 18:04:58.130000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01020: on_time=2026-05-17 18:04:59.450000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01021: on_time=2026-05-17 18:05:02.430000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01022: on_time=2026-05-17 18:05:05.240000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01023: on_time=2026-05-17 18:05:07.508000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01024: on_time=2026-05-17 18:05:09.666000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01025: on_time=2026-05-17 18:05:11.782000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01026: on_time=2026-05-17 18:05:13.928000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01027: on_time=2026-05-17 18:05:16.156000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01028: on_time=2026-05-17 18:05:18.308000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01029: on_time=2026-05-17 18:05:20.406000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01030: on_time=2026-05-17 18:05:22.626000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01031: on_time=2026-05-17 18:05:25.646000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01032: on_time=2026-05-17 18:05:30.782000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01033: on_time=2026-05-17 18:05:41.996000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01034: on_time=2026-05-17 18:05:55.964000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01035: on_time=2026-05-17 18:06:57.986000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01036: on_time=2026-05-17 18:07:09.330000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01037: on_time=2026-05-17 18:07:19.040000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01038: on_time=2026-05-17 18:07:20.114000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01039: on_time=2026-05-17 18:08:54.032000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01040: on_time=2026-05-17 18:10:03.522000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01041: on_time=2026-05-17 18:10:15.994000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01042: on_time=2026-05-17 18:10:21.496000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01043: on_time=2026-05-17 18:10:24.740000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01044: on_time=2026-05-17 18:10:27.428000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01045: on_time=2026-05-17 18:10:36.966000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01046: on_time=2026-05-17 18:11:06.736000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01047: on_time=2026-05-17 18:11:11.552000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01048: on_time=2026-05-17 18:11:15.196000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01049: on_time=2026-05-17 18:11:18.540000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01050: on_time=2026-05-17 18:11:26.358000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01051: on_time=2026-05-17 18:11:30.778000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01052: on_time=2026-05-17 18:11:37.942000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01053: on_time=2026-05-17 18:11:45.518000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01054: on_time=2026-05-17 18:12:24.972000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01055: on_time=2026-05-17 18:12:27.718000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01056: on_time=2026-05-17 18:12:29.814000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01057: on_time=2026-05-17 18:12:31.796000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01058: on_time=2026-05-17 18:12:33.824000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01059: on_time=2026-05-17 18:12:36.012000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01060: on_time=2026-05-17 18:12:38.042000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01061: on_time=2026-05-17 18:12:40.134000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01062: on_time=2026-05-17 18:12:42.106000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01063: on_time=2026-05-17 18:12:44.114000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01064: on_time=2026-05-17 18:12:46.504000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01065: on_time=2026-05-17 18:12:48.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01066: on_time=2026-05-17 18:13:09.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01067: on_time=2026-05-17 18:13:14.898000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01068: on_time=2026-05-17 18:13:19.262000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01069: on_time=2026-05-17 18:13:43.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01070: on_time=2026-05-17 18:14:41.216000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01071: on_time=2026-05-17 18:15:32.890000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01072: on_time=2026-05-17 18:18:57.054000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01073: on_time=2026-05-17 18:18:59.580000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01074: on_time=2026-05-17 18:19:07.286000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01075: on_time=2026-05-17 18:19:09.244000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01076: on_time=2026-05-17 18:19:11.202000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01077: on_time=2026-05-17 18:19:17.748000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01078: on_time=2026-05-17 18:19:52.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01079: on_time=2026-05-17 18:20:15.296000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01080: on_time=2026-05-17 18:20:42.710000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01081: on_time=2026-05-17 18:20:56

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01082: on_time=2026-05-17 18:21:22.728000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01083: on_time=2026-05-17 18:21:45.892000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01084: on_time=2026-05-17 18:22:09.400000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01085: on_time=2026-05-17 18:22:38.488000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01086: on_time=2026-05-17 18:23:37.102000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01087: on_time=2026-05-17 18:23:47.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01088: on_time=2026-05-17 18:23:53.318000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01089: on_time=2026-05-17 18:23:58.542000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01090: on_time=2026-05-17 18:24:40.016000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01091: on_time=2026-05-17 18:24:43.786000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01092: on_time=2026-05-17 18:24:46.958000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01093: on_time=2026-05-17 18:24:50.418000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01094: on_time=2026-05-17 18:24:53.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01095: on_time=2026-05-17 18:24:56.916000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01096: on_time=2026-05-17 18:25:00.112000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01097: on_time=2026-05-17 18:25:03.532000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01098: on_time=2026-05-17 18:25:06.302000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01099: on_time=2026-05-17 18:25:08.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01100: on_time=2026-05-17 18:26:15.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01101: on_time=2026-05-17 18:26:17.996000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01102: on_time=2026-05-17 18:26:20.434000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01103: on_time=2026-05-17 18:26:22.402000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01104: on_time=2026-05-17 18:26:24.726000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01105: on_time=2026-05-17 18:26:26.896000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01106: on_time=2026-05-17 18:26:29.122000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01107: on_time=2026-05-17 18:26:31.330000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01108: on_time=2026-05-17 18:26:33.342000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01109: on_time=2026-05-17 18:26:35.494000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01110: on_time=2026-05-17 18:26:44.512000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01111: on_time=2026-05-17 18:27:01.154000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01112: on_time=2026-05-17 18:27:03.798000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01113: on_time=2026-05-17 18:27:10.604000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01114: on_time=2026-05-17 18:27:12.746000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01115: on_time=2026-05-17 18:27:14.720000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01116: on_time=2026-05-17 18:27:16.744000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01117: on_time=2026-05-17 18:27:18.686000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01118: on_time=2026-05-17 18:27:20.642000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01119: on_time=2026-05-17 18:27:22.598000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01120: on_time=2026-05-17 18:27:24.546000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01121: on_time=2026-05-17 18:27:26.702000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01122: on_time=2026-05-17 18:27:28.726000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01123: on_time=2026-05-17 18:27:33.228000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01124: on_time=2026-05-17 18:27:33.710000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01125: on_time=2026-05-17 18:27:38.568000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01126: on_time=2026-05-17 18:27:41.442000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01127: on_time=2026-05-17 18:28:02.832000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01128: on_time=2026-05-17 18:31:20.056000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01129: on_time=2026-05-17 18:31:36.080000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01130: on_time=2026-05-17 18:31:39.110000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01131: on_time=2026-05-17 18:31:41.668000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01132: on_time=2026-05-17 18:31:44.134000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01133: on_time=2026-05-17 18:31:46.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01134: on_time=2026-05-17 18:31:48.876000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01135: on_time=2026-05-17 18:31:51.196000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01136: on_time=2026-05-17 18:31:53.458000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01137: on_time=2026-05-17 18:31:55.794000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01138: on_time=2026-05-17 18:32:00.476000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01139: on_time=2026-05-17 18:32:12.898000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01140: on_time=2026-05-17 18:32:40.260000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01141: on_time=2026-05-17 18:32:42.390000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01142: on_time=2026-05-17 18:32:44.608000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01143: on_time=2026-05-17 18:32:46.746000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01144: on_time=2026-05-17 18:32:48.822000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01145: on_time=2026-05-17 18:32:50.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01146: on_time=2026-05-17 18:32:53.114000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01147: on_time=2026-05-17 18:32:55.448000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01148: on_time=2026-05-17 18:32:59.396000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01149: on_time=2026-05-17 18:33:13.158000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01150: on_time=2026-05-17 18:33:15.664000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01151: on_time=2026-05-17 18:33:18.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01152: on_time=2026-05-17 18:33:20.694000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01153: on_time=2026-05-17 18:33:41.766000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01154: on_time=2026-05-17 18:33:48.696000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01155: on_time=2026-05-17 18:33:50.230000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01156: on_time=2026-05-17 18:33:51.476000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01157: on_time=2026-05-17 18:34:14.720000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01158: on_time=2026-05-17 18:34:18.888000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01159: on_time=2026-05-17 18:34:59.040000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01160: on_time=2026-05-17 18:35:02.386000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01161: on_time=2026-05-17 18:35:05.514000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01162: on_time=2026-05-17 18:35:08.898000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01163: on_time=2026-05-17 18:35:12.136000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01164: on_time=2026-05-17 18:35:15.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01165: on_time=2026-05-17 18:35:18.762000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01166: on_time=2026-05-17 18:35:21.998000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01167: on_time=2026-05-17 18:35:24.942000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01168: on_time=2026-05-17 18:35:28.004000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01169: on_time=2026-05-17 18:35:33.590000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01170: on_time=2026-05-17 18:35:39.850000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01171: on_time=2026-05-17 18:35:59.590000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01172: on_time=2026-05-17 18:35:59.836000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01173: on_time=2026-05-17 18:36:02.014000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01174: on_time=2026-05-17 18:36:04.380000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01175: on_time=2026-05-17 18:36:06.952000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01176: on_time=2026-05-17 18:36:09.314000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01177: on_time=2026-05-17 18:36:11.766000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01178: on_time=2026-05-17 18:36:14.152000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01179: on_time=2026-05-17 18:36:16.556000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01180: on_time=2026-05-17 18:36:18.858000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01181: on_time=2026-05-17 18:36:21.120000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01182: on_time=2026-05-17 18:36:28.212000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01183: on_time=2026-05-17 18:36:31.696000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01184: on_time=2026-05-17 18:36:48.240000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01185: on_time=2026-05-17 18:36:51.260000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01186: on_time=2026-05-17 18:36:53.772000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01187: on_time=2026-05-17 18:36:56.248000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01188: on_time=2026-05-17 18:36:58.736000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01189: on_time=2026-05-17 18:37:01.352000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01190: on_time=2026-05-17 18:37:03.878000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01191: on_time=2026-05-17 18:37:06.402000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01192: on_time=2026-05-17 18:37:08.796000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01193: on_time=2026-05-17 18:37:21.454000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01194: on_time=2026-05-17 18:37:25.942000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01195: on_time=2026-05-17 18:37:29.038000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01196: on_time=2026-05-17 18:37:32.092000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01197: on_time=2026-05-17 18:37:42.558000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01198: on_time=2026-05-17 18:37:45.804000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01199: on_time=2026-05-17 18:38:26.392000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01200: on_time=2026-05-17 18:38:28.974000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01201: on_time=2026-05-17 18:38:31.298000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01202: on_time=2026-05-17 18:38:33.932000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01203: on_time=2026-05-17 18:38:36.366000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01204: on_time=2026-05-17 18:38:38.582000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01205: on_time=2026-05-17 18:38:40.876000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01206: on_time=2026-05-17 18:38:43.130000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01207: on_time=2026-05-17 18:38:45.292000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01208: on_time=2026-05-17 18:38:47.466000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01209: on_time=2026-05-17 18:38:49.592000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01210: on_time=2026-05-17 18:38:51.656000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01211: on_time=2026-05-17 18:39:07.024000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01212: on_time=2026-05-17 18:39:36.310000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01213: on_time=2026-05-17 18:39:36.626000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01214: on_time=2026-05-17 18:39:38.684000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01215: on_time=2026-05-17 18:39:40.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01216: on_time=2026-05-17 18:39:42.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01217: on_time=2026-05-17 18:39:44.604000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01218: on_time=2026-05-17 18:39:46.510000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01219: on_time=2026-05-17 18:39:48.446000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01220: on_time=2026-05-17 18:39:50.420000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01221: on_time=2026-05-17 18:39:52.392000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01222: on_time=2026-05-17 18:39:54.382000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01223: on_time=2026-05-17 18:40:04.304000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01224: on_time=2026-05-17 18:40:06.202000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01225: on_time=2026-05-17 18:40:08.188000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01226: on_time=2026-05-17 18:40:21.284000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01227: on_time=2026-05-17 18:40:25.344000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01228: on_time=2026-05-17 18:40:27.540000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01229: on_time=2026-05-17 18:40:31.772000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01230: on_time=2026-05-17 18:40:43.598000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01231: on_time=2026-05-17 18:40:45.814000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01232: on_time=2026-05-17 18:40:47.944000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01233: on_time=2026-05-17 18:40:54.936000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01234: on_time=2026-05-17 18:40:57.132000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01235: on_time=2026-05-17 18:40:59.188000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01236: on_time=2026-05-17 18:41:01.208000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01237: on_time=2026-05-17 18:41:03.208000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01238: on_time=2026-05-17 18:41:06.956000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01239: on_time=2026-05-17 18:41:28.056000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01240: on_time=2026-05-17 18:41:46.422000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01241: on_time=2026-05-17 18:42:04.356000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01242: on_time=2026-05-17 18:42:06.698000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01243: on_time=2026-05-17 18:42:08.626000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01244: on_time=2026-05-17 18:42:10.550000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01245: on_time=2026-05-17 18:42:12.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01246: on_time=2026-05-17 18:42:14.328000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01247: on_time=2026-05-17 18:42:16.324000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01248: on_time=2026-05-17 18:42:18.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01249: on_time=2026-05-17 18:42:20.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01250: on_time=2026-05-17 18:42:21.978000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01251: on_time=2026-05-17 18:42:23.652000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01252: on_time=2026-05-17 18:42:28.836000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01253: on_time=2026-05-17 18:42:33.934000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01254: on_time=2026-05-17 18:42:40.194000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01255: on_time=2026-05-17 18:42:42.132000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01256: on_time=2026-05-17 18:42:45.308000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01257: on_time=2026-05-17 18:42:46.108000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01258: on_time=2026-05-17 18:42:50.544000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01259: on_time=2026-05-17 18:43:09.954000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01260: on_time=2026-05-17 18:44:50.172000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01261: on_time=2026-05-17 18:44:51.330000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01262: on_time=2026-05-17 18:44:51.944000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01263: on_time=2026-05-17 18:45:13.332000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01264: on_time=2026-05-17 18:45:13.680000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01265: on_time=2026-05-17 18:45:16.336000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01266: on_time=2026-05-17 18:45:18.738000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01267: on_time=2026-05-17 18:45:21.036000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01268: on_time=2026-05-17 18:45:23.198000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01269: on_time=2026-05-17 18:45:25.290000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01270: on_time=2026-05-17 18:45:27.326000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01271: on_time=2026-05-17 18:45:29.170000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01272: on_time=2026-05-17 18:45:31.364000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01273: on_time=2026-05-17 18:45:33.400000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01274: on_time=2026-05-17 18:45:38.326000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01275: on_time=2026-05-17 18:46:31.268000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01276: on_time=2026-05-17 18:46:34.240000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01277: on_time=2026-05-17 18:46:37.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01278: on_time=2026-05-17 18:46:39.842000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01279: on_time=2026-05-17 18:46:42.426000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01280: on_time=2026-05-17 18:46:45.234000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01281: on_time=2026-05-17 18:46:47.928000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01282: on_time=2026-05-17 18:46:50.736000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01283: on_time=2026-05-17 18:46:53.414000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01284: on_time=2026-05-17 18:46:56.296000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01285: on_time=2026-05-17 18:47:02.898000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01286: on_time=2026-05-17 18:47:15.620000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01287: on_time=2026-05-17 18:47:23.366000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01288: on_time=2026-05-17 18:47:26.146000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01289: on_time=2026-05-17 18:47:28.786000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01290: on_time=2026-05-17 18:47:36.652000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01291: on_time=2026-05-17 18:47:39.950000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01292: on_time=2026-05-17 18:47:43.338000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01293: on_time=2026-05-17 18:47:46.764000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01294: on_time=2026-05-17 18:47:49.802000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01295: on_time=2026-05-17 18:48:14.562000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01296: on_time=2026-05-17 18:48:18.176000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01297: on_time=2026-05-17 18:48:21.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01298: on_time=2026-05-17 18:48:32.992000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01299: on_time=2026-05-17 18:48:42.826000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01300: on_time=2026-05-17 18:49:21.188000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01301: on_time=2026-05-17 18:49:52.344000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01302: on_time=2026-05-17 18:50:05.930000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01303: on_time=2026-05-17 18:50:14.124000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01304: on_time=2026-05-17 18:50:35.818000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01305: on_time=2026-05-17 18:50:37.114000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01306: on_time=2026-05-17 18:54:55.398000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01307: on_time=2026-05-17 18:54:59.254000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01308: on_time=2026-05-17 18:54:59.612000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01309: on_time=2026-05-17 18:55:02.568000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01310: on_time=2026-05-17 18:55:05.602000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01311: on_time=2026-05-17 18:55:08.452000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01312: on_time=2026-05-17 18:55:11.208000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01313: on_time=2026-05-17 18:55:14.546000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01314: on_time=2026-05-17 18:55:17.576000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01315: on_time=2026-05-17 18:55:20.396000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01316: on_time=2026-05-17 18:55:23.070000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01317: on_time=2026-05-17 18:55:25.678000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01318: on_time=2026-05-17 18:55:32.850000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01319: on_time=2026-05-17 18:55:41.646000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01320: on_time=2026-05-17 18:55:56.848000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01321: on_time=2026-05-17 18:56:01.936000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01322: on_time=2026-05-17 18:56:04.606000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01323: on_time=2026-05-17 18:56:06.992000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01324: on_time=2026-05-17 18:56:09.316000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01325: on_time=2026-05-17 18:56:11.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01326: on_time=2026-05-17 18:56:14.132000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01327: on_time=2026-05-17 18:56:16.582000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01328: on_time=2026-05-17 18:56:19.108000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01329: on_time=2026-05-17 18:56:21.628000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01330: on_time=2026-05-17 18:56:46.892000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01331: on_time=2026-05-17 18:56:49.874000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01332: on_time=2026-05-17 18:57:02.562000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01333: on_time=2026-05-17 18:57:07.390000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01334: on_time=2026-05-17 18:57:17.818000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01335: on_time=2026-05-17 18:57:19.292000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01336: on_time=2026-05-17 18:57:23.260000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01337: on_time=2026-05-17 18:57:25.932000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01338: on_time=2026-05-17 18:57:28.232000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01339: on_time=2026-05-17 18:57:30.642000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01340: on_time=2026-05-17 18:57:32.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01341: on_time=2026-05-17 18:57:35.042000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01342: on_time=2026-05-17 18:57:37.208000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01343: on_time=2026-05-17 18:57:39.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01344: on_time=2026-05-17 18:57:41.598000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01345: on_time=2026-05-17 18:57:43.800000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01346: on_time=2026-05-17 18:57:46.374000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01347: on_time=2026-05-17 18:57:49.298000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01348: on_time=2026-05-17 18:57:52.360000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01349: on_time=2026-05-17 18:57:58.006000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01350: on_time=2026-05-17 18:58:03.482000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01351: on_time=2026-05-17 18:58:09.408000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01352: on_time=2026-05-17 18:58:10.110000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01353: on_time=2026-05-17 18:58:10.886000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01354: on_time=2026-05-17 18:58:13.398000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01355: on_time=2026-05-17 18:58:20.810000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01356: on_time=2026-05-17 18:58:33.938000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01357: on_time=2026-05-17 18:58:36.480000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01358: on_time=2026-05-17 18:58:38.594000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01359: on_time=2026-05-17 18:58:40.684000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01360: on_time=2026-05-17 18:58:42.820000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01361: on_time=2026-05-17 18:58:44.860000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01362: on_time=2026-05-17 18:58:59.930000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01363: on_time=2026-05-17 18:59:00.208000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01364: on_time=2026-05-17 18:59:02.254000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01365: on_time=2026-05-17 18:59:04.692000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01366: on_time=2026-05-17 18:59:16.372000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01367: on_time=2026-05-17 18:59:17.844000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01368: on_time=2026-05-17 18:59:23.592000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01369: on_time=2026-05-17 18:59:25.854000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01370: on_time=2026-05-17 18:59:28.282000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01371: on_time=2026-05-17 18:59:39.546000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01372: on_time=2026-05-17 18:59:47.492000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01373: on_time=2026-05-17 18:59:52.264000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01374: on_time=2026-05-17 18:59:54.890000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01375: on_time=2026-05-17 18:59:57.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal1_T1_N2_E01376: on_time=2026-05-17 18:59:59.388000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

====================================================================================================
Processing T1_N2_Refraction1m

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

Discovered 35 T1.N2.DPZ stations
['06809', '07600', '08003', '08405', '08808', '09210', '09605', '10000', '10408', '10603', '10814', '11005', '11215', '11400', '11611', '11797', '12018', '12204', '12413', '12638', '12815', '12996', '13216', '13402', '13620', '13782', '14000', '14400', '14800', '15195', '16000', '16400', '16809', '17604', '18405']
T1_N2_Refraction1m chunk 0: 2026-05-18T16:02:18.500000Z to 2026-05-18T16:03:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 1: 2026-05-18T16:03:18.500000Z to 2026-05-18T16:04:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 2: 2026-05-18T16:04:18.500000Z to 2026-05-18T16:05:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 3: 2026-05-18T16:05:18.500000Z to 2026-05-18T16:06:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 4: 2026-05-18T16:06:18.500000Z to 2026-05-18T16:07:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 5: 2026-05-18T16:07:18.500000Z to 2026-05-18T16:08:18.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction1m chunk 6: 2026-05-18T16:08:18.500000Z to 2026-05-18T16:09:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 7: 2026-05-18T16:09:18.500000Z to 2026-05-18T16:10:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 8: 2026-05-18T16:10:18.500000Z to 2026-05-18T16:11:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 9: 2026-05-18T16:11:18.500000Z to 2026-05-18T16:12:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 10: 2026-05-18T16:12:18.500000Z to 2026-05-18T16:13:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 11: 2026-05-18T16:13:18.500000Z to 2026-05-18T16:14:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 12: 2026-05-18T16:14:18.500000Z to 2026-05-18T16:15:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 13: 2026-05-18T16:15:18.500000Z to 2026-05-18T16:16:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 14: 2026-05-18T16:16:18.500000Z to 2026-05-18T16:17:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 15: 2026-05-18T16:17:18.500000Z to 2026-05-18T16:18:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 16: 2026-05-18T16:18:18.500000Z to 2026-05-18T16:19:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 17: 2026-05-18T16:19:18.500000Z to 2026-05-18T16:20:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 18: 2026-05-18T16:20:18.500000Z to 2026-05-18T16:21:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 19: 2026-05-18T16:21:18.500000Z to 2026-05-18T16:22:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 20: 2026-05-18T16:22:18.500000Z to 2026-05-18T16:23:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 21: 2026-05-18T16:23:18.500000Z to 2026-05-18T16:24:18.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction1m chunk 22: 2026-05-18T16:24:18.500000Z to 2026-05-18T16:25:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 23: 2026-05-18T16:25:18.500000Z to 2026-05-18T16:26:18.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction1m chunk 24: 2026-05-18T16:26:18.500000Z to 2026-05-18T16:27:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 25: 2026-05-18T16:27:18.500000Z to 2026-05-18T16:28:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 26: 2026-05-18T16:28:18.500000Z to 2026-05-18T16:29:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 27: 2026-05-18T16:29:18.500000Z to 2026-05-18T16:30:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 28: 2026-05-18T16:30:18.500000Z to 2026-05-18T16:31:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 29: 2026-05-18T16:31:18.500000Z to 2026-05-18T16:32:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 30: 2026-05-18T16:32:18.500000Z to 2026-05-18T16:33:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 31: 2026-05-18T16:33:18.500000Z to 2026-05-18T16:34:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 32: 2026-05-18T16:34:18.500000Z to 2026-05-18T16:35:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 33: 2026-05-18T16:35:18.500000Z to 2026-05-18T16:36:18.500000Z
  read 34 traces, 34 stations
  detections: 12
T1_N2_Refraction1m chunk 34: 2026-05-18T16:36:18.500000Z to 2026-05-18T16:37:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 35: 2026-05-18T16:37:18.500000Z to 2026-05-18T16:38:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 36: 2026-05-18T16:38:18.500000Z to 2026-05-18T16:39:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 37: 2026-05-18T16:39:18.500000Z to 2026-05-18T16:40:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 38: 2026-05-18T16:40:18.500000Z to 2026-05-18T16:41:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 39: 2026-05-18T16:41:18.500000Z to 2026-05-18T16:42:18.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction1m chunk 40: 2026-05-18T16:42:18.500000Z to 2026-05-18T16:43:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 41: 2026-05-18T16:43:18.500000Z to 2026-05-18T16:44:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 42: 2026-05-18T16:44:18.500000Z to 2026-05-18T16:45:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 43: 2026-05-18T16:45:18.500000Z to 2026-05-18T16:46:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 44: 2026-05-18T16:46:18.500000Z to 2026-05-18T16:47:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 45: 2026-05-18T16:47:18.500000Z to 2026-05-18T16:48:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 46: 2026-05-18T16:48:18.500000Z to 2026-05-18T16:49:18.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction1m chunk 47: 2026-05-18T16:49:18.500000Z to 2026-05-18T16:50:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 48: 2026-05-18T16:50:18.500000Z to 2026-05-18T16:51:18.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction1m chunk 49: 2026-05-18T16:51:18.500000Z to 2026-05-18T16:52:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 50: 2026-05-18T16:52:18.500000Z to 2026-05-18T16:53:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 51: 2026-05-18T16:53:18.500000Z to 2026-05-18T16:54:18.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction1m chunk 52: 2026-05-18T16:54:18.500000Z to 2026-05-18T16:55:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 53: 2026-05-18T16:55:18.500000Z to 2026-05-18T16:56:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 54: 2026-05-18T16:56:18.500000Z to 2026-05-18T16:57:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 55: 2026-05-18T16:57:18.500000Z to 2026-05-18T16:58:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 56: 2026-05-18T16:58:18.500000Z to 2026-05-18T16:59:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 57: 2026-05-18T16:59:18.500000Z to 2026-05-18T17:00:18.500000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Refraction1m chunk 58: 2026-05-18T17:00:18.500000Z to 2026-05-18T17:01:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 59: 2026-05-18T17:01:18.500000Z to 2026-05-18T17:02:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 60: 2026-05-18T17:02:18.500000Z to 2026-05-18T17:03:18.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction1m chunk 61: 2026-05-18T17:03:18.500000Z to 2026-05-18T17:04:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 62: 2026-05-18T17:04:18.500000Z to 2026-05-18T17:05:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 63: 2026-05-18T17:05:18.500000Z to 2026-05-18T17:06:18.500000Z
  read 34 traces, 34 stations
  detections: 9
T1_N2_Refraction1m chunk 64: 2026-05-18T17:06:18.500000Z to 2026-05-18T17:07:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 65: 2026-05-18T17:07:18.500000Z to 2026-05-18T17:08:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 66: 2026-05-18T17:08:18.500000Z to 2026-05-18T17:09:18.500000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Refraction1m chunk 67: 2026-05-18T17:09:18.500000Z to 2026-05-18T17:10:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 68: 2026-05-18T17:10:18.500000Z to 2026-05-18T17:11:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 69: 2026-05-18T17:11:18.500000Z to 2026-05-18T17:12:18.500000Z
  read 34 traces, 34 stations
  detections: 10
T1_N2_Refraction1m chunk 70: 2026-05-18T17:12:18.500000Z to 2026-05-18T17:13:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 71: 2026-05-18T17:13:18.500000Z to 2026-05-18T17:14:18.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction1m chunk 72: 2026-05-18T17:14:18.500000Z to 2026-05-18T17:15:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 73: 2026-05-18T17:15:18.500000Z to 2026-05-18T17:16:18.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction1m chunk 74: 2026-05-18T17:16:18.500000Z to 2026-05-18T17:17:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 75: 2026-05-18T17:17:18.500000Z to 2026-05-18T17:18:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 76: 2026-05-18T17:18:18.500000Z to 2026-05-18T17:19:18.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction1m chunk 77: 2026-05-18T17:19:18.500000Z to 2026-05-18T17:20:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 78: 2026-05-18T17:20:18.500000Z to 2026-05-18T17:21:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 79: 2026-05-18T17:21:18.500000Z to 2026-05-18T17:22:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 80: 2026-05-18T17:22:18.500000Z to 2026-05-18T17:23:18.500000Z
  read 34 traces, 34 stations
  detections: 9
T1_N2_Refraction1m chunk 81: 2026-05-18T17:23:18.500000Z to 2026-05-18T17:24:18.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction1m chunk 82: 2026-05-18T17:24:18.500000Z to 2026-05-18T17:25:18.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction1m chunk 83: 2026-05-18T17:25:18.500000Z to 2026-05-18T17:26:18.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction1m chunk 84: 2026-05-18T17:26:18.500000Z to 2026-05-18T17:27:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 85: 2026-05-18T17:27:18.500000Z to 2026-05-18T17:28:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 86: 2026-05-18T17:28:18.500000Z to 2026-05-18T17:29:18.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction1m chunk 87: 2026-05-18T17:29:18.500000Z to 2026-05-18T17:30:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 88: 2026-05-18T17:30:18.500000Z to 2026-05-18T17:31:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 89: 2026-05-18T17:31:18.500000Z to 2026-05-18T17:32:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 90: 2026-05-18T17:32:18.500000Z to 2026-05-18T17:33:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 91: 2026-05-18T17:33:18.500000Z to 2026-05-18T17:34:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 92: 2026-05-18T17:34:18.500000Z to 2026-05-18T17:35:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 93: 2026-05-18T17:35:18.500000Z to 2026-05-18T17:36:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 94: 2026-05-18T17:36:18.500000Z to 2026-05-18T17:37:18.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction1m chunk 95: 2026-05-18T17:37:18.500000Z to 2026-05-18T17:38:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 96: 2026-05-18T17:38:18.500000Z to 2026-05-18T17:39:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 97: 2026-05-18T17:39:18.500000Z to 2026-05-18T17:40:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 98: 2026-05-18T17:40:18.500000Z to 2026-05-18T17:41:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 99: 2026-05-18T17:41:18.500000Z to 2026-05-18T17:42:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 100: 2026-05-18T17:42:18.500000Z to 2026-05-18T17:43:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 101: 2026-05-18T17:43:18.500000Z to 2026-05-18T17:44:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 102: 2026-05-18T17:44:18.500000Z to 2026-05-18T17:45:18.500000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Refraction1m chunk 103: 2026-05-18T17:45:18.500000Z to 2026-05-18T17:46:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 104: 2026-05-18T17:46:18.500000Z to 2026-05-18T17:47:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 105: 2026-05-18T17:47:18.500000Z to 2026-05-18T17:48:18.500000Z
  read 34 traces, 34 stations
  detections: 10
T1_N2_Refraction1m chunk 106: 2026-05-18T17:48:18.500000Z to 2026-05-18T17:49:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 107: 2026-05-18T17:49:18.500000Z to 2026-05-18T17:50:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 108: 2026-05-18T17:50:18.500000Z to 2026-05-18T17:51:18.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction1m chunk 109: 2026-05-18T17:51:18.500000Z to 2026-05-18T17:52:18.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction1m chunk 110: 2026-05-18T17:52:18.500000Z to 2026-05-18T17:53:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 111: 2026-05-18T17:53:18.500000Z to 2026-05-18T17:54:18.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction1m chunk 112: 2026-05-18T17:54:18.500000Z to 2026-05-18T17:55:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 113: 2026-05-18T17:55:18.500000Z to 2026-05-18T17:56:18.500000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Refraction1m chunk 114: 2026-05-18T17:56:18.500000Z to 2026-05-18T17:57:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 115: 2026-05-18T17:57:18.500000Z to 2026-05-18T17:58:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 116: 2026-05-18T17:58:18.500000Z to 2026-05-18T17:59:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 117: 2026-05-18T17:59:18.500000Z to 2026-05-18T18:00:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 118: 2026-05-18T18:00:18.500000Z to 2026-05-18T18:01:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 119: 2026-05-18T18:01:18.500000Z to 2026-05-18T18:02:18.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction1m chunk 120: 2026-05-18T18:02:18.500000Z to 2026-05-18T18:03:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 121: 2026-05-18T18:03:18.500000Z to 2026-05-18T18:04:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 122: 2026-05-18T18:04:18.500000Z to 2026-05-18T18:05:18.500000Z
  read 34 traces, 34 stations
  detections: 11
T1_N2_Refraction1m chunk 123: 2026-05-18T18:05:18.500000Z to 2026-05-18T18:06:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 124: 2026-05-18T18:06:18.500000Z to 2026-05-18T18:07:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 125: 2026-05-18T18:07:18.500000Z to 2026-05-18T18:08:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 126: 2026-05-18T18:08:18.500000Z to 2026-05-18T18:09:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 127: 2026-05-18T18:09:18.500000Z to 2026-05-18T18:10:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 128: 2026-05-18T18:10:18.500000Z to 2026-05-18T18:11:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 129: 2026-05-18T18:11:18.500000Z to 2026-05-18T18:12:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 130: 2026-05-18T18:12:18.500000Z to 2026-05-18T18:13:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 131: 2026-05-18T18:13:18.500000Z to 2026-05-18T18:14:18.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction1m chunk 132: 2026-05-18T18:14:18.500000Z to 2026-05-18T18:15:18.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction1m chunk 133: 2026-05-18T18:15:18.500000Z to 2026-05-18T18:16:18.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction1m chunk 134: 2026-05-18T18:16:18.500000Z to 2026-05-18T18:17:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 135: 2026-05-18T18:17:18.500000Z to 2026-05-18T18:18:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 136: 2026-05-18T18:18:18.500000Z to 2026-05-18T18:19:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 137: 2026-05-18T18:19:18.500000Z to 2026-05-18T18:20:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 138: 2026-05-18T18:20:18.500000Z to 2026-05-18T18:21:18.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction1m chunk 139: 2026-05-18T18:21:18.500000Z to 2026-05-18T18:22:18.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction1m chunk 140: 2026-05-18T18:22:18.500000Z to 2026-05-18T18:23:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 141: 2026-05-18T18:23:18.500000Z to 2026-05-18T18:24:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 142: 2026-05-18T18:24:18.500000Z to 2026-05-18T18:25:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 143: 2026-05-18T18:25:18.500000Z to 2026-05-18T18:26:18.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction1m chunk 144: 2026-05-18T18:26:18.500000Z to 2026-05-18T18:27:18.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction1m chunk 145: 2026-05-18T18:27:18.500000Z to 2026-05-18T18:28:18.500000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Refraction1m chunk 146: 2026-05-18T18:28:18.500000Z to 2026-05-18T18:29:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 147: 2026-05-18T18:29:18.500000Z to 2026-05-18T18:30:18.500000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Refraction1m chunk 148: 2026-05-18T18:30:18.500000Z to 2026-05-18T18:31:18.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction1m chunk 149: 2026-05-18T18:31:18.500000Z to 2026-05-18T18:32:18.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction1m chunk 150: 2026-05-18T18:32:18.500000Z to 2026-05-18T18:33:18.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction1m chunk 151: 2026-05-18T18:33:18.500000Z to 2026-05-18T18:34:18.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction1m chunk 152: 2026-05-18T18:34:18.500000Z to 2026-05-18T18:35:18.500000Z

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00003: on_time=2026-05-18 16:07:44.108000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00004: on_time=2026-05-18 16:07:53.522000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00005: on_time=2026-05-18 16:08:00.098000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00006: on_time=2026-05-18 16:08:06.688000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00007: on_time=2026-05-18 16:08:13.502000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00008: on_time=2026-05-18 16:08:30.794000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00009: on_time=2026-05-18 16:18:11.688000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00010: on_time=2026-05-18 16:18:19.404000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00011: on_time=2026-05-18 16:18:25.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00012: on_time=2026-05-18 16:19:50.426000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00013: on_time=2026-05-18 16:20:02.144000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00014: on_time=2026-05-18 16:20:09.340000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00015: on_time=2026-05-18 16:20:15.816000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00016: on_time=2026-05-18 16:20:22.456000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00017: on_time=2026-05-18 16:20:30.080000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00018: on_time=2026-05-18 16:20:37.502000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00019: on_time=2026-05-18 16:20:45.118000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00020: on_time=2026-05-18 16:20:52.158000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00021: on_time=2026-05-18 16:22:37.038000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00022: on_time=2026-05-18 16:22:46.926000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00023: on_time=2026-05-18 16:22:53.826000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00024: on_time=2026-05-18 16:23:01.182000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00025: on_time=2026-05-18 16:23:25.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00026: on_time=2026-05-18 16:23:26.144000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00027: on_time=2026-05-18 16:23:35.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00028: on_time=2026-05-18 16:23:44.634000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00029: on_time=2026-05-18 16:24:14.792000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00030: on_time=2026-05-18 16:24:21.522000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00031: on_time=2026-05-18 16:24:42.822000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00032: on_time=2026-05-18 16:25:13.068000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00033: on_time=2026-05-18 16:25:21.596000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00034: on_time=2026-05-18 16:25:40.786000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00035: on_time=2026-05-18 16:25:50.812000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00036: on_time=2026-05-18 16:34:40.770000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00037: on_time=2026-05-18 16:34:54.832000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00038: on_time=2026-05-18 16:35:19.380000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00039: on_time=2026-05-18 16:35:28.792000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00040: on_time=2026-05-18 16:35:38.200000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00041: on_time=2026-05-18 16:35:47.534000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00042: on_time=2026-05-18 16:35:57.426000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00043: on_time=2026-05-18 16:36:06.698000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00044: on_time=2026-05-18 16:36:15.134000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00045: on_time=2026-05-18 16:36:25.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00046: on_time=2026-05-18 16:36:33.766000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00047: on_time=2026-05-18 16:39:29.600000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00048: on_time=2026-05-18 16:39:37.690000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00049: on_time=2026-05-18 16:40:26.248000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00050: on_time=2026-05-18 16:40:39.594000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00051: on_time=2026-05-18 16:40:51.552000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00052: on_time=2026-05-18 16:41:02.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00053: on_time=2026-05-18 16:41:11.910000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00054: on_time=2026-05-18 16:41:20.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00055: on_time=2026-05-18 16:41:29.442000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00056: on_time=2026-05-18 16:41:52.840000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00057: on_time=2026-05-18 16:45:07.824000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00058: on_time=2026-05-18 16:45:28.994000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00059: on_time=2026-05-18 16:45:54.844000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00060: on_time=2026-05-18 16:46:22.764000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00061: on_time=2026-05-18 16:46:34.030000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00062: on_time=2026-05-18 16:46:44.482000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00063: on_time=2026-05-18 16:46:54.076000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00064: on_time=2026-05-18 16:47:02.750000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00065: on_time=2026-05-18 16:48:16.526000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00066: on_time=2026-05-18 16:48:41.562000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00067: on_time=2026-05-18 16:49:02.908000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00068: on_time=2026-05-18 16:49:16.524000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00069: on_time=2026-05-18 16:49:28.674000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00070: on_time=2026-05-18 16:49:37.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00071: on_time=2026-05-18 16:49:53.134000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00072: on_time=2026-05-18 16:49:53.522000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00073: on_time=2026-05-18 16:50:07.138000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00074: on_time=2026-05-18 16:50:22.368000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00075: on_time=2026-05-18 16:50:38.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00076: on_time=2026-05-18 16:50:48.394000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00077: on_time=2026-05-18 16:50:59.504000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00078: on_time=2026-05-18 16:51:08.954000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00079: on_time=2026-05-18 16:51:17.084000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00080: on_time=2026-05-18 16:53:21.854000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00081: on_time=2026-05-18 16:53:32.024000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00082: on_time=2026-05-18 16:53:42.574000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00083: on_time=2026-05-18 16:53:52.798000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00084: on_time=2026-05-18 16:54:01.694000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00085: on_time=2026-05-18 16:54:11.036000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00086: on_time=2026-05-18 16:54:20.966000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00087: on_time=2026-05-18 16:54:29.916000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00088: on_time=2026-05-18 16:59:20.910000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00089: on_time=2026-05-18 16:59:28.810000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00090: on_time=2026-05-18 16:59:35.730000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00091: on_time=2026-05-18 16:59:42.724000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00092: on_time=2026-05-18 16:59:52.202000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00093: on_time=2026-05-18 16:59:59.432000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00094: on_time=2026-05-18 17:00:11.350000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00095: on_time=2026-05-18 17:00:18.082000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00096: on_time=2026-05-18 17:00:26.510000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00097: on_time=2026-05-18 17:02:37.592000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00098: on_time=2026-05-18 17:02:47.892000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00099: on_time=2026-05-18 17:02:56.384000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00100: on_time=2026-05-18 17:03:03.198000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00101: on_time=2026-05-18 17:03:09.866000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00102: on_time=2026-05-18 17:03:10.160000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00103: on_time=2026-05-18 17:03:19.530000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00104: on_time=2026-05-18 17:03:29.050000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00105: on_time=2026-05-18 17:03:36.428000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00106: on_time=2026-05-18 17:03:43.634000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00107: on_time=2026-05-18 17:05:14.494000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00108: on_time=2026-05-18 17:05:26.092000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00109: on_time=2026-05-18 17:05:33.284000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00110: on_time=2026-05-18 17:05:40.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00111: on_time=2026-05-18 17:05:46.264000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00112: on_time=2026-05-18 17:05:52.640000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00113: on_time=2026-05-18 17:06:01.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00114: on_time=2026-05-18 17:06:08.996000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00115: on_time=2026-05-18 17:06:15.548000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00116: on_time=2026-05-18 17:06:22.582000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00117: on_time=2026-05-18 17:08:20.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00118: on_time=2026-05-18 17:08:27.068000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00119: on_time=2026-05-18 17:08:36.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00120: on_time=2026-05-18 17:08:43.524000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00121: on_time=2026-05-18 17:08:53.342000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00122: on_time=2026-05-18 17:09:01.428000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00123: on_time=2026-05-18 17:09:08.340000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00124: on_time=2026-05-18 17:09:15.674000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00125: on_time=2026-05-18 17:09:22.988000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00126: on_time=2026-05-18 17:09:30.714000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00127: on_time=2026-05-18 17:09:38.412000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00128: on_time=2026-05-18 17:09:45.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00129: on_time=2026-05-18 17:10:54.610000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00130: on_time=2026-05-18 17:11:08.422000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00131: on_time=2026-05-18 17:11:15.220000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00132: on_time=2026-05-18 17:11:22.292000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00133: on_time=2026-05-18 17:11:27.978000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00134: on_time=2026-05-18 17:11:33.400000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00135: on_time=2026-05-18 17:11:40.414000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00136: on_time=2026-05-18 17:11:47.384000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00137: on_time=2026-05-18 17:11:55.556000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00138: on_time=2026-05-18 17:12:02.654000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00139: on_time=2026-05-18 17:12:10.716000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00140: on_time=2026-05-18 17:12:16.674000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00141: on_time=2026-05-18 17:12:26.144000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00142: on_time=2026-05-18 17:14:05.308000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00143: on_time=2026-05-18 17:14:12.704000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00144: on_time=2026-05-18 17:14:18.480000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00145: on_time=2026-05-18 17:14:25.878000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00146: on_time=2026-05-18 17:14:37.320000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00147: on_time=2026-05-18 17:14:54.656000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00148: on_time=2026-05-18 17:14:56.032000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00149: on_time=2026-05-18 17:15:21.068000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00150: on_time=2026-05-18 17:15:27.920000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00151: on_time=2026-05-18 17:15:35.152000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00152: on_time=2026-05-18 17:15:42.462000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00153: on_time=2026-05-18 17:15:50.420000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00154: on_time=2026-05-18 17:15:58.554000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00155: on_time=2026-05-18 17:18:38.396000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00156: on_time=2026-05-18 17:18:46.268000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00157: on_time=2026-05-18 17:18:54.450000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00158: on_time=2026-05-18 17:19:02.260000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00159: on_time=2026-05-18 17:19:09.740000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00160: on_time=2026-05-18 17:19:17.564000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00161: on_time=2026-05-18 17:19:25.388000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00162: on_time=2026-05-18 17:19:32.864000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00163: on_time=2026-05-18 17:19:40.250000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00164: on_time=2026-05-18 17:19:48.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00165: on_time=2026-05-18 17:21:51.198000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00166: on_time=2026-05-18 17:22:15.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00167: on_time=2026-05-18 17:22:27.342000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00168: on_time=2026-05-18 17:22:37.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00169: on_time=2026-05-18 17:22:44.956000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00170: on_time=2026-05-18 17:22:52.856000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00171: on_time=2026-05-18 17:22:53.158000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00172: on_time=2026-05-18 17:23:00.474000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00173: on_time=2026-05-18 17:23:08.272000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00174: on_time=2026-05-18 17:23:16.108000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00175: on_time=2026-05-18 17:23:16.402000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00176: on_time=2026-05-18 17:23:23.926000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00177: on_time=2026-05-18 17:23:24.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00178: on_time=2026-05-18 17:23:48.902000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00179: on_time=2026-05-18 17:25:02.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00180: on_time=2026-05-18 17:25:09.124000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00181: on_time=2026-05-18 17:25:16.028000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00182: on_time=2026-05-18 17:25:23.196000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00183: on_time=2026-05-18 17:25:30.102000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00184: on_time=2026-05-18 17:25:36.132000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00185: on_time=2026-05-18 17:25:43.334000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00186: on_time=2026-05-18 17:25:50.826000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00187: on_time=2026-05-18 17:25:57.964000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00188: on_time=2026-05-18 17:26:04.778000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00189: on_time=2026-05-18 17:27:25.596000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00190: on_time=2026-05-18 17:27:32.040000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00191: on_time=2026-05-18 17:27:38.574000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00192: on_time=2026-05-18 17:27:48.832000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00193: on_time=2026-05-18 17:28:08.042000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00194: on_time=2026-05-18 17:28:45.736000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00195: on_time=2026-05-18 17:28:54.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00196: on_time=2026-05-18 17:28:54.626000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00197: on_time=2026-05-18 17:29:01.228000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00198: on_time=2026-05-18 17:29:01.634000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00199: on_time=2026-05-18 17:29:07.690000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00200: on_time=2026-05-18 17:29:08.160000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00201: on_time=2026-05-18 17:30:08.230000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00202: on_time=2026-05-18 17:31:19.514000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00203: on_time=2026-05-18 17:31:51.892000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00204: on_time=2026-05-18 17:32:46.098000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00205: on_time=2026-05-18 17:32:52.504000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00206: on_time=2026-05-18 17:32:58.734000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00207: on_time=2026-05-18 17:33:05.042000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00208: on_time=2026-05-18 17:33:16.264000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00209: on_time=2026-05-18 17:33:22.314000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00210: on_time=2026-05-18 17:33:30.300000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00211: on_time=2026-05-18 17:33:36.976000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00212: on_time=2026-05-18 17:33:44.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00213: on_time=2026-05-18 17:36:14.978000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00214: on_time=2026-05-18 17:36:22.386000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00215: on_time=2026-05-18 17:36:32.252000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00216: on_time=2026-05-18 17:36:39.634000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00217: on_time=2026-05-18 17:36:52.002000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00218: on_time=2026-05-18 17:36:58.542000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00219: on_time=2026-05-18 17:37:05.376000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00220: on_time=2026-05-18 17:37:11.908000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00221: on_time=2026-05-18 17:37:19.696000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00222: on_time=2026-05-18 17:40:52.388000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00223: on_time=2026-05-18 17:41:00.424000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00224: on_time=2026-05-18 17:41:08.922000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00225: on_time=2026-05-18 17:41:16.066000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00226: on_time=2026-05-18 17:41:23.756000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00227: on_time=2026-05-18 17:41:32.166000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00228: on_time=2026-05-18 17:41:40.114000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00229: on_time=2026-05-18 17:41:48.368000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00230: on_time=2026-05-18 17:41:55.946000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00231: on_time=2026-05-18 17:43:52.212000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00232: on_time=2026-05-18 17:44:11.444000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00233: on_time=2026-05-18 17:44:18.470000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00234: on_time=2026-05-18 17:44:25.090000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00235: on_time=2026-05-18 17:44:32.270000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00236: on_time=2026-05-18 17:44:38.986000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00237: on_time=2026-05-18 17:44:45.254000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00238: on_time=2026-05-18 17:44:53.220000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00239: on_time=2026-05-18 17:44:59.696000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00240: on_time=2026-05-18 17:45:06.626000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00241: on_time=2026-05-18 17:46:59.914000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00242: on_time=2026-05-18 17:47:10.410000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00243: on_time=2026-05-18 17:47:18.910000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00244: on_time=2026-05-18 17:47:19.202000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00245: on_time=2026-05-18 17:47:28.136000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00246: on_time=2026-05-18 17:47:36.966000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00247: on_time=2026-05-18 17:47:44.830000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00248: on_time=2026-05-18 17:47:45.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00249: on_time=2026-05-18 17:47:53.728000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00250: on_time=2026-05-18 17:48:02.136000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00251: on_time=2026-05-18 17:48:02.500000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00252: on_time=2026-05-18 17:48:13.396000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00253: on_time=2026-05-18 17:48:22.204000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00254: on_time=2026-05-18 17:48:31.958000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00255: on_time=2026-05-18 17:50:36.382000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00256: on_time=2026-05-18 17:50:45.156000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00257: on_time=2026-05-18 17:50:53.384000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00258: on_time=2026-05-18 17:51:01.586000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00259: on_time=2026-05-18 17:51:09.664000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00260: on_time=2026-05-18 17:51:17.140000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00261: on_time=2026-05-18 17:51:24.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00262: on_time=2026-05-18 17:51:32.112000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00263: on_time=2026-05-18 17:51:40.896000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00264: on_time=2026-05-18 17:52:45.380000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00265: on_time=2026-05-18 17:52:57.346000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00266: on_time=2026-05-18 17:53:05.934000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00267: on_time=2026-05-18 17:53:14.526000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00268: on_time=2026-05-18 17:53:14.834000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00269: on_time=2026-05-18 17:53:52.678000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00270: on_time=2026-05-18 17:54:01.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00271: on_time=2026-05-18 17:54:02.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00272: on_time=2026-05-18 17:54:10.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00273: on_time=2026-05-18 17:54:10.488000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00274: on_time=2026-05-18 17:54:17.906000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00275: on_time=2026-05-18 17:54:18.410000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00276: on_time=2026-05-18 17:54:25.116000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00277: on_time=2026-05-18 17:54:25.524000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00278: on_time=2026-05-18 17:55:25.076000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00279: on_time=2026-05-18 17:55:32.738000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00280: on_time=2026-05-18 17:55:39.460000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00281: on_time=2026-05-18 17:55:46.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00282: on_time=2026-05-18 17:55:53.118000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00283: on_time=2026-05-18 17:56:00.002000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00284: on_time=2026-05-18 17:56:06.700000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00285: on_time=2026-05-18 17:56:13.678000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00286: on_time=2026-05-18 17:56:20.822000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00287: on_time=2026-05-18 17:58:41.710000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00288: on_time=2026-05-18 17:58:41.984000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00289: on_time=2026-05-18 17:59:04.618000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00290: on_time=2026-05-18 17:59:10.838000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00291: on_time=2026-05-18 17:59:44.134000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00292: on_time=2026-05-18 18:00:06.988000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00293: on_time=2026-05-18 18:01:06.828000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00294: on_time=2026-05-18 18:01:14.862000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00295: on_time=2026-05-18 18:01:23.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00296: on_time=2026-05-18 18:01:31.122000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00297: on_time=2026-05-18 18:01:39.788000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00298: on_time=2026-05-18 18:01:47.976000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00299: on_time=2026-05-18 18:01:56.176000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00300: on_time=2026-05-18 18:02:05.004000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00301: on_time=2026-05-18 18:02:19.564000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00302: on_time=2026-05-18 18:03:22.490000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00303: on_time=2026-05-18 18:04:03.586000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00304: on_time=2026-05-18 18:04:03.888000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00305: on_time=2026-05-18 18:04:11.862000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00306: on_time=2026-05-18 18:04:19.756000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00307: on_time=2026-05-18 18:04:20.070000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00308: on_time=2026-05-18 18:04:26.502000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00309: on_time=2026-05-18 18:04:33.688000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00310: on_time=2026-05-18 18:04:40.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00311: on_time=2026-05-18 18:04:40.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00312: on_time=2026-05-18 18:04:47.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00313: on_time=2026-05-18 18:04:54.982000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00314: on_time=2026-05-18 18:05:02.610000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00315: on_time=2026-05-18 18:05:10.486000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00316: on_time=2026-05-18 18:06:37.628000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00317: on_time=2026-05-18 18:06:46.116000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00318: on_time=2026-05-18 18:06:55.720000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00319: on_time=2026-05-18 18:07:04.890000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00320: on_time=2026-05-18 18:10:09.830000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00321: on_time=2026-05-18 18:10:16.730000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00322: on_time=2026-05-18 18:10:31.966000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00323: on_time=2026-05-18 18:10:45.642000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00324: on_time=2026-05-18 18:11:08.714000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00325: on_time=2026-05-18 18:11:28.662000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00326: on_time=2026-05-18 18:11:36.950000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00327: on_time=2026-05-18 18:11:45.556000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00328: on_time=2026-05-18 18:11:55.504000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00329: on_time=2026-05-18 18:13:25.358000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00330: on_time=2026-05-18 18:13:33.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00331: on_time=2026-05-18 18:13:42.432000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00332: on_time=2026-05-18 18:13:50.600000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00333: on_time=2026-05-18 18:13:58.594000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00334: on_time=2026-05-18 18:14:06.928000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00335: on_time=2026-05-18 18:14:15.436000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00336: on_time=2026-05-18 18:14:23.396000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00337: on_time=2026-05-18 18:14:36.288000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00338: on_time=2026-05-18 18:15:55.972000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00339: on_time=2026-05-18 18:16:03.908000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00340: on_time=2026-05-18 18:16:12.624000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00341: on_time=2026-05-18 18:16:21.288000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00342: on_time=2026-05-18 18:16:29.336000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00343: on_time=2026-05-18 18:16:43.108000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00344: on_time=2026-05-18 18:16:51.564000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00345: on_time=2026-05-18 18:16:59.456000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00346: on_time=2026-05-18 18:18:26.562000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00347: on_time=2026-05-18 18:18:52.482000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00348: on_time=2026-05-18 18:19:01.348000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00349: on_time=2026-05-18 18:19:09.452000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00350: on_time=2026-05-18 18:19:17.372000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00351: on_time=2026-05-18 18:19:25.826000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00352: on_time=2026-05-18 18:19:37.412000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00353: on_time=2026-05-18 18:19:45.690000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00354: on_time=2026-05-18 18:19:54.128000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00355: on_time=2026-05-18 18:20:47.962000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00356: on_time=2026-05-18 18:20:55.294000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00357: on_time=2026-05-18 18:20:55.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00358: on_time=2026-05-18 18:21:02.910000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00359: on_time=2026-05-18 18:21:10.466000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00360: on_time=2026-05-18 18:21:10.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00361: on_time=2026-05-18 18:21:18.132000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00362: on_time=2026-05-18 18:21:25.844000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00363: on_time=2026-05-18 18:21:32.820000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00364: on_time=2026-05-18 18:21:33.176000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00365: on_time=2026-05-18 18:21:40.800000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00366: on_time=2026-05-18 18:21:48.026000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00367: on_time=2026-05-18 18:23:35.344000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00368: on_time=2026-05-18 18:23:42.264000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00369: on_time=2026-05-18 18:24:00.588000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00370: on_time=2026-05-18 18:24:06.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00371: on_time=2026-05-18 18:24:13.154000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00372: on_time=2026-05-18 18:25:12.210000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00373: on_time=2026-05-18 18:25:19.316000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00374: on_time=2026-05-18 18:25:27.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00375: on_time=2026-05-18 18:25:34.856000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00376: on_time=2026-05-18 18:25:41.592000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00377: on_time=2026-05-18 18:25:48.368000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00378: on_time=2026-05-18 18:25:55.414000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00379: on_time=2026-05-18 18:26:02.204000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00380: on_time=2026-05-18 18:27:12.460000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00381: on_time=2026-05-18 18:27:19.704000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00382: on_time=2026-05-18 18:27:26.840000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00383: on_time=2026-05-18 18:27:33.826000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00384: on_time=2026-05-18 18:27:40.844000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00385: on_time=2026-05-18 18:27:47.884000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00386: on_time=2026-05-18 18:27:55.520000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00387: on_time=2026-05-18 18:28:02.990000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00388: on_time=2026-05-18 18:28:10.706000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00389: on_time=2026-05-18 18:29:51.714000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00390: on_time=2026-05-18 18:29:58.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00391: on_time=2026-05-18 18:30:05.136000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00392: on_time=2026-05-18 18:30:05.424000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00393: on_time=2026-05-18 18:30:11.530000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00394: on_time=2026-05-18 18:30:18.430000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00395: on_time=2026-05-18 18:30:25.590000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00396: on_time=2026-05-18 18:30:32.580000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00397: on_time=2026-05-18 18:30:39.630000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00398: on_time=2026-05-18 18:30:46.450000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00399: on_time=2026-05-18 18:32:24.124000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00400: on_time=2026-05-18 18:32:39.012000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00401: on_time=2026-05-18 18:32:48.174000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00402: on_time=2026-05-18 18:33:13.938000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00403: on_time=2026-05-18 18:33:44.122000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00404: on_time=2026-05-18 18:33:51.562000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00405: on_time=2026-05-18 18:33:59.292000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00406: on_time=2026-05-18 18:34:07.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00407: on_time=2026-05-18 18:34:14.410000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00408: on_time=2026-05-18 18:34:22.070000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00409: on_time=2026-05-18 18:34:30.270000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00410: on_time=2026-05-18 18:34:39.252000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00411: on_time=2026-05-18 18:34:48.372000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00412: on_time=2026-05-18 18:35:56.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00413: on_time=2026-05-18 18:36:06.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00414: on_time=2026-05-18 18:36:12.656000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00415: on_time=2026-05-18 18:36:18.126000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00416: on_time=2026-05-18 18:36:24.110000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00417: on_time=2026-05-18 18:36:31.386000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00418: on_time=2026-05-18 18:36:36.830000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00419: on_time=2026-05-18 18:36:42.758000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00420: on_time=2026-05-18 18:37:23.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00421: on_time=2026-05-18 18:37:23.856000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00422: on_time=2026-05-18 18:37:31.314000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00423: on_time=2026-05-18 18:37:39.006000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00424: on_time=2026-05-18 18:37:45.602000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00425: on_time=2026-05-18 18:37:52.468000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00426: on_time=2026-05-18 18:37:52.738000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00427: on_time=2026-05-18 18:37:59.258000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00428: on_time=2026-05-18 18:38:06.606000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00429: on_time=2026-05-18 18:38:14.064000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00430: on_time=2026-05-18 18:38:14.430000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction1m_T1_N2_E00431: on_time=2026-05-18 18:38:21.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

====================================================================================================
Processing T1_N2_Refraction2m

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

Discovered 35 T1.N2.DPZ stations
['06809', '07600', '08003', '08405', '08808', '09210', '09605', '10000', '10408', '10603', '10814', '11005', '11215', '11400', '11611', '11797', '12018', '12204', '12413', '12638', '12815', '12996', '13216', '13402', '13620', '13782', '14000', '14400', '14800', '15195', '16000', '16400', '16809', '17604', '18405']
T1_N2_Refraction2m chunk 0: 2026-05-18T20:17:02.500000Z to 2026-05-18T20:18:02.500000Z
  read 34 traces, 34 stations
  detections: 9
T1_N2_Refraction2m chunk 1: 2026-05-18T20:18:02.500000Z to 2026-05-18T20:19:02.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction2m chunk 2: 2026-05-18T20:19:02.500000Z to 2026-05-18T20:20:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 3: 2026-05-18T20:20:02.500000Z to 2026-05-18T20:21:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 4: 2026-05-18T20:21:02.500000Z to 2026-05-18T20:22:02.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction2m chunk 5: 2026-05-18T20:22:02.500000Z to 2026-05-18T20:23:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 6: 2026-05-18T20:23:02.500000Z to 2026-05-18T20:24:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 7: 2026-05-18T20:24:02.500000Z to 2026-05-18T20:25:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 8: 2026-05-18T20:25:02.500000Z to 2026-05-18T20:26:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 9: 2026-05-18T20:26:02.500000Z to 2026-05-18T20:27:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 10: 2026-05-18T20:27:02.500000Z to 2026-05-18T20:28:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 11: 2026-05-18T20:28:02.500000Z to 2026-05-18T20:29:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 12: 2026-05-18T20:29:02.500000Z to 2026-05-18T20:30:02.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction2m chunk 13: 2026-05-18T20:30:02.500000Z to 2026-05-18T20:31:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 14: 2026-05-18T20:31:02.500000Z to 2026-05-18T20:32:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 15: 2026-05-18T20:32:02.500000Z to 2026-05-18T20:33:02.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction2m chunk 16: 2026-05-18T20:33:02.500000Z to 2026-05-18T20:34:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 17: 2026-05-18T20:34:02.500000Z to 2026-05-18T20:35:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 18: 2026-05-18T20:35:02.500000Z to 2026-05-18T20:36:02.500000Z
  read 34 traces, 34 stations
  detections: 16
T1_N2_Refraction2m chunk 19: 2026-05-18T20:36:02.500000Z to 2026-05-18T20:37:02.500000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Refraction2m chunk 20: 2026-05-18T20:37:02.500000Z to 2026-05-18T20:38:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 21: 2026-05-18T20:38:02.500000Z to 2026-05-18T20:39:02.500000Z
  read 34 traces, 34 stations
  detections: 12
T1_N2_Refraction2m chunk 22: 2026-05-18T20:39:02.500000Z to 2026-05-18T20:40:02.500000Z
  read 34 traces, 34 stations
  detections: 10
T1_N2_Refraction2m chunk 23: 2026-05-18T20:40:02.500000Z to 2026-05-18T20:41:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 24: 2026-05-18T20:41:02.500000Z to 2026-05-18T20:42:02.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction2m chunk 25: 2026-05-18T20:42:02.500000Z to 2026-05-18T20:43:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 26: 2026-05-18T20:43:02.500000Z to 2026-05-18T20:44:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 27: 2026-05-18T20:44:02.500000Z to 2026-05-18T20:45:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 28: 2026-05-18T20:45:02.500000Z to 2026-05-18T20:46:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 29: 2026-05-18T20:46:02.500000Z to 2026-05-18T20:47:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 30: 2026-05-18T20:47:02.500000Z to 2026-05-18T20:48:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 31: 2026-05-18T20:48:02.500000Z to 2026-05-18T20:49:02.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction2m chunk 32: 2026-05-18T20:49:02.500000Z to 2026-05-18T20:50:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 33: 2026-05-18T20:50:02.500000Z to 2026-05-18T20:51:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 34: 2026-05-18T20:51:02.500000Z to 2026-05-18T20:52:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 35: 2026-05-18T20:52:02.500000Z to 2026-05-18T20:53:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 36: 2026-05-18T20:53:02.500000Z to 2026-05-18T20:54:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 37: 2026-05-18T20:54:02.500000Z to 2026-05-18T20:55:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 38: 2026-05-18T20:55:02.500000Z to 2026-05-18T20:56:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 39: 2026-05-18T20:56:02.500000Z to 2026-05-18T20:57:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 40: 2026-05-18T20:57:02.500000Z to 2026-05-18T20:58:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 41: 2026-05-18T20:58:02.500000Z to 2026-05-18T20:59:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 42: 2026-05-18T20:59:02.500000Z to 2026-05-18T21:00:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 43: 2026-05-18T21:00:02.500000Z to 2026-05-18T21:01:02.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction2m chunk 44: 2026-05-18T21:01:02.500000Z to 2026-05-18T21:02:02.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction2m chunk 45: 2026-05-18T21:02:02.500000Z to 2026-05-18T21:03:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 46: 2026-05-18T21:03:02.500000Z to 2026-05-18T21:04:02.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction2m chunk 47: 2026-05-18T21:04:02.500000Z to 2026-05-18T21:05:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 48: 2026-05-18T21:05:02.500000Z to 2026-05-18T21:06:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 49: 2026-05-18T21:06:02.500000Z to 2026-05-18T21:07:02.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction2m chunk 50: 2026-05-18T21:07:02.500000Z to 2026-05-18T21:08:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 51: 2026-05-18T21:08:02.500000Z to 2026-05-18T21:09:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 52: 2026-05-18T21:09:02.500000Z to 2026-05-18T21:10:02.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction2m chunk 53: 2026-05-18T21:10:02.500000Z to 2026-05-18T21:11:02.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction2m chunk 54: 2026-05-18T21:11:02.500000Z to 2026-05-18T21:12:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 55: 2026-05-18T21:12:02.500000Z to 2026-05-18T21:13:02.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction2m chunk 56: 2026-05-18T21:13:02.500000Z to 2026-05-18T21:14:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 57: 2026-05-18T21:14:02.500000Z to 2026-05-18T21:15:02.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction2m chunk 58: 2026-05-18T21:15:02.500000Z to 2026-05-18T21:16:02.500000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Refraction2m chunk 59: 2026-05-18T21:16:02.500000Z to 2026-05-18T21:17:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 60: 2026-05-18T21:17:02.500000Z to 2026-05-18T21:18:02.500000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Refraction2m chunk 61: 2026-05-18T21:18:02.500000Z to 2026-05-18T21:19:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 62: 2026-05-18T21:19:02.500000Z to 2026-05-18T21:20:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 63: 2026-05-18T21:20:02.500000Z to 2026-05-18T21:21:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 64: 2026-05-18T21:21:02.500000Z to 2026-05-18T21:22:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 65: 2026-05-18T21:22:02.500000Z to 2026-05-18T21:23:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 66: 2026-05-18T21:23:02.500000Z to 2026-05-18T21:24:02.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction2m chunk 67: 2026-05-18T21:24:02.500000Z to 2026-05-18T21:25:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 68: 2026-05-18T21:25:02.500000Z to 2026-05-18T21:26:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 69: 2026-05-18T21:26:02.500000Z to 2026-05-18T21:27:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 70: 2026-05-18T21:27:02.500000Z to 2026-05-18T21:28:02.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction2m chunk 71: 2026-05-18T21:28:02.500000Z to 2026-05-18T21:29:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 72: 2026-05-18T21:29:02.500000Z to 2026-05-18T21:30:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 73: 2026-05-18T21:30:02.500000Z to 2026-05-18T21:31:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 74: 2026-05-18T21:31:02.500000Z to 2026-05-18T21:32:02.500000Z
  read 34 traces, 34 stations
  detections: 9
T1_N2_Refraction2m chunk 75: 2026-05-18T21:32:02.500000Z to 2026-05-18T21:33:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 76: 2026-05-18T21:33:02.500000Z to 2026-05-18T21:34:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 77: 2026-05-18T21:34:02.500000Z to 2026-05-18T21:35:02.500000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Refraction2m chunk 78: 2026-05-18T21:35:02.500000Z to 2026-05-18T21:36:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 79: 2026-05-18T21:36:02.500000Z to 2026-05-18T21:37:02.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction2m chunk 80: 2026-05-18T21:37:02.500000Z to 2026-05-18T21:38:02.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction2m chunk 81: 2026-05-18T21:38:02.500000Z to 2026-05-18T21:39:02.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction2m chunk 82: 2026-05-18T21:39:02.500000Z to 2026-05-18T21:40:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 83: 2026-05-18T21:40:02.500000Z to 2026-05-18T21:41:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 84: 2026-05-18T21:41:02.500000Z to 2026-05-18T21:42:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 85: 2026-05-18T21:42:02.500000Z to 2026-05-18T21:43:02.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction2m chunk 86: 2026-05-18T21:43:02.500000Z to 2026-05-18T21:44:02.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction2m chunk 87: 2026-05-18T21:44:02.500000Z to 2026-05-18T21:45:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 88: 2026-05-18T21:45:02.500000Z to 2026-05-18T21:46:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 89: 2026-05-18T21:46:02.500000Z to 2026-05-18T21:47:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 90: 2026-05-18T21:47:02.500000Z to 2026-05-18T21:48:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 91: 2026-05-18T21:48:02.500000Z to 2026-05-18T21:49:02.500000Z
  read 34 traces, 34 stations
  detections: 4
T1_N2_Refraction2m chunk 92: 2026-05-18T21:49:02.500000Z to 2026-05-18T21:50:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 93: 2026-05-18T21:50:02.500000Z to 2026-05-18T21:51:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 94: 2026-05-18T21:51:02.500000Z to 2026-05-18T21:52:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 95: 2026-05-18T21:52:02.500000Z to 2026-05-18T21:53:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 96: 2026-05-18T21:53:02.500000Z to 2026-05-18T21:54:02.500000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Refraction2m chunk 97: 2026-05-18T21:54:02.500000Z to 2026-05-18T21:55:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 98: 2026-05-18T21:55:02.500000Z to 2026-05-18T21:56:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 99: 2026-05-18T21:56:02.500000Z to 2026-05-18T21:57:02.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction2m chunk 100: 2026-05-18T21:57:02.500000Z to 2026-05-18T21:58:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 101: 2026-05-18T21:58:02.500000Z to 2026-05-18T21:59:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 102: 2026-05-18T21:59:02.500000Z to 2026-05-18T22:00:02.500000Z
  read 34 traces, 34 stations
  detections: 9
T1_N2_Refraction2m chunk 103: 2026-05-18T22:00:02.500000Z to 2026-05-18T22:01:02.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction2m chunk 104: 2026-05-18T22:01:02.500000Z to 2026-05-18T22:02:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 105: 2026-05-18T22:02:02.500000Z to 2026-05-18T22:03:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 106: 2026-05-18T22:03:02.500000Z to 2026-05-18T22:04:02.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction2m chunk 107: 2026-05-18T22:04:02.500000Z to 2026-05-18T22:05:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 108: 2026-05-18T22:05:02.500000Z to 2026-05-18T22:06:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 109: 2026-05-18T22:06:02.500000Z to 2026-05-18T22:07:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 110: 2026-05-18T22:07:02.500000Z to 2026-05-18T22:08:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 111: 2026-05-18T22:08:02.500000Z to 2026-05-18T22:09:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 112: 2026-05-18T22:09:02.500000Z to 2026-05-18T22:10:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 113: 2026-05-18T22:10:02.500000Z to 2026-05-18T22:11:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 114: 2026-05-18T22:11:02.500000Z to 2026-05-18T22:12:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 115: 2026-05-18T22:12:02.500000Z to 2026-05-18T22:13:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 116: 2026-05-18T22:13:02.500000Z to 2026-05-18T22:14:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 117: 2026-05-18T22:14:02.500000Z to 2026-05-18T22:15:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 118: 2026-05-18T22:15:02.500000Z to 2026-05-18T22:16:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 119: 2026-05-18T22:16:02.500000Z to 2026-05-18T22:17:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 120: 2026-05-18T22:17:02.500000Z to 2026-05-18T22:18:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 121: 2026-05-18T22:18:02.500000Z to 2026-05-18T22:19:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 122: 2026-05-18T22:19:02.500000Z to 2026-05-18T22:20:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 123: 2026-05-18T22:20:02.500000Z to 2026-05-18T22:21:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 124: 2026-05-18T22:21:02.500000Z to 2026-05-18T22:22:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 125: 2026-05-18T22:22:02.500000Z to 2026-05-18T22:23:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 126: 2026-05-18T22:23:02.500000Z to 2026-05-18T22:24:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 127: 2026-05-18T22:24:02.500000Z to 2026-05-18T22:25:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 128: 2026-05-18T22:25:02.500000Z to 2026-05-18T22:26:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 129: 2026-05-18T22:26:02.500000Z to 2026-05-18T22:27:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 130: 2026-05-18T22:27:02.500000Z to 2026-05-18T22:28:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 131: 2026-05-18T22:28:02.500000Z to 2026-05-18T22:29:02.500000Z
  read 34 traces, 34 stations
  detections: 1
T1_N2_Refraction2m chunk 132: 2026-05-18T22:29:02.500000Z to 2026-05-18T22:30:02.500000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Refraction2m chunk 133: 2026-05-18T22:30:02.500000Z to 2026-05-18T22:31:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 134: 2026-05-18T22:31:02.500000Z to 2026-05-18T22:32:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 135: 2026-05-18T22:32:02.500000Z to 2026-05-18T22:33:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 136: 2026-05-18T22:33:02.500000Z to 2026-05-18T22:34:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 137: 2026-05-18T22:34:02.500000Z to 2026-05-18T22:35:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 138: 2026-05-18T22:35:02.500000Z to 2026-05-18T22:36:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 139: 2026-05-18T22:36:02.500000Z to 2026-05-18T22:37:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 140: 2026-05-18T22:37:02.500000Z to 2026-05-18T22:38:02.500000Z
  read 34 traces, 34 stations
  detections: 11
T1_N2_Refraction2m chunk 141: 2026-05-18T22:38:02.500000Z to 2026-05-18T22:39:02.500000Z
  read 34 traces, 34 stations
  detections: 27
T1_N2_Refraction2m chunk 142: 2026-05-18T22:39:02.500000Z to 2026-05-18T22:40:02.500000Z
  read 34 traces, 34 stations
  detections: 25
T1_N2_Refraction2m chunk 143: 2026-05-18T22:40:02.500000Z to 2026-05-18T22:41:02.500000Z
  read 34 traces, 34 stations
  detections: 2
T1_N2_Refraction2m chunk 144: 2026-05-18T22:41:02.500000Z to 2026-05-18T22:42:02.500000Z
  read 34 traces, 34 stations
  detections: 9
T1_N2_Refraction2m chunk 145: 2026-05-18T22:42:02.500000Z to 2026-05-18T22:43:02.500000Z
  read 34 traces, 34 stations
  detections: 14
T1_N2_Refraction2m chunk 146: 2026-05-18T22:43:02.500000Z to 2026-05-18T22:44:02.500000Z
  read 34 traces, 34 stations
  detections: 5
T1_N2_Refraction2m chunk 147: 2026-05-18T22:44:02.500000Z to 2026-05-18T22:45:02.500000Z
  read 34 traces, 34 stations
  detections: 10
T1_N2_Refraction2m chunk 148: 2026-05-18T22:45:02.500000Z to 2026-05-18T22:46:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 149: 2026-05-18T22:46:02.500000Z to 2026-05-18T22:47:02.500000Z
  read 34 traces, 34 stations
T1_N2_Refraction2m chunk 150: 2026-05-18T22:47:02.500000Z to 2026-05-18T22:48:02.500000Z
  read 34 traces, 34 stations
  detections: 3
T1_N2_Refraction2m chunk 151: 2026-05-18T22:48:02.500000Z to 2026-05-18T22:49:02.500000Z
  read 34 traces, 34 stations
  detections: 9

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00003: on_time=2026-05-18 20:17:24.996000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00004: on_time=2026-05-18 20:17:34.286000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00005: on_time=2026-05-18 20:17:43.528000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00006: on_time=2026-05-18 20:17:54.022000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00007: on_time=2026-05-18 20:18:03.798000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00008: on_time=2026-05-18 20:18:13.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00009: on_time=2026-05-18 20:18:21.950000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00010: on_time=2026-05-18 20:18:33.518000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00011: on_time=2026-05-18 20:20:20.976000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00012: on_time=2026-05-18 20:20:28.250000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00013: on_time=2026-05-18 20:20:38.606000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00014: on_time=2026-05-18 20:20:46.716000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00015: on_time=2026-05-18 20:20:53.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00016: on_time=2026-05-18 20:21:01.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00017: on_time=2026-05-18 20:21:08.764000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00018: on_time=2026-05-18 20:21:16.060000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00019: on_time=2026-05-18 20:21:23.950000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00020: on_time=2026-05-18 20:21:33.422000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00021: on_time=2026-05-18 20:24:28.120000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00022: on_time=2026-05-18 20:24:53.698000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00023: on_time=2026-05-18 20:25:02.860000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00024: on_time=2026-05-18 20:25:19.648000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00025: on_time=2026-05-18 20:25:28.690000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00026: on_time=2026-05-18 20:25:37.508000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00027: on_time=2026-05-18 20:25:46.198000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00028: on_time=2026-05-18 20:25:55.648000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00029: on_time=2026-05-18 20:26:05.050000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00030: on_time=2026-05-18 20:27:47.118000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00031: on_time=2026-05-18 20:28:31.842000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00032: on_time=2026-05-18 20:28:42.926000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00033: on_time=2026-05-18 20:28:50.826000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00034: on_time=2026-05-18 20:29:05.556000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00035: on_time=2026-05-18 20:29:14.068000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00036: on_time=2026-05-18 20:29:24.192000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00037: on_time=2026-05-18 20:29:32.568000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00038: on_time=2026-05-18 20:29:41.070000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00039: on_time=2026-05-18 20:29:49.886000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00040: on_time=2026-05-18 20:29:59.148000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00041: on_time=2026-05-18 20:30:08.606000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00042: on_time=2026-05-18 20:31:44.534000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00043: on_time=2026-05-18 20:31:53.876000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00044: on_time=2026-05-18 20:32:02.158000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00045: on_time=2026-05-18 20:32:11.112000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00046: on_time=2026-05-18 20:32:22.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00047: on_time=2026-05-18 20:32:32.416000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00048: on_time=2026-05-18 20:32:41.052000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00049: on_time=2026-05-18 20:32:50.128000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00050: on_time=2026-05-18 20:33:00.206000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00051: on_time=2026-05-18 20:33:08.776000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00052: on_time=2026-05-18 20:35:06.322000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00053: on_time=2026-05-18 20:35:14.504000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00054: on_time=2026-05-18 20:35:24.364000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00055: on_time=2026-05-18 20:35:32.680000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00056: on_time=2026-05-18 20:35:41.040000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00057: on_time=2026-05-18 20:35:48.992000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00058: on_time=2026-05-18 20:35:57.040000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00059: on_time=2026-05-18 20:36:05.412000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00060: on_time=2026-05-18 20:36:19.294000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00061: on_time=2026-05-18 20:36:19.506000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00062: on_time=2026-05-18 20:36:28.308000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00063: on_time=2026-05-18 20:38:11.420000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00064: on_time=2026-05-18 20:38:20.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00065: on_time=2026-05-18 20:38:20.222000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00066: on_time=2026-05-18 20:38:28.386000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00067: on_time=2026-05-18 20:38:28.596000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00068: on_time=2026-05-18 20:38:36.294000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00069: on_time=2026-05-18 20:38:36.608000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00070: on_time=2026-05-18 20:38:45.016000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00071: on_time=2026-05-18 20:38:45.226000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00072: on_time=2026-05-18 20:38:53.614000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00073: on_time=2026-05-18 20:38:53.916000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00074: on_time=2026-05-18 20:39:03.660000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00075: on_time=2026-05-18 20:39:03.870000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00076: on_time=2026-05-18 20:39:12.416000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00077: on_time=2026-05-18 20:39:21.290000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00078: on_time=2026-05-18 20:39:21.496000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00079: on_time=2026-05-18 20:39:30.182000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00080: on_time=2026-05-18 20:39:30.460000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00081: on_time=2026-05-18 20:40:59.518000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00082: on_time=2026-05-18 20:41:07.792000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00083: on_time=2026-05-18 20:41:15.564000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00084: on_time=2026-05-18 20:41:23.782000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00085: on_time=2026-05-18 20:41:32.132000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00086: on_time=2026-05-18 20:41:44.932000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00087: on_time=2026-05-18 20:42:04.350000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00088: on_time=2026-05-18 20:45:44.212000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00089: on_time=2026-05-18 20:45:52.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00090: on_time=2026-05-18 20:46:01.554000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00091: on_time=2026-05-18 20:46:27.464000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00092: on_time=2026-05-18 20:46:45.990000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00093: on_time=2026-05-18 20:48:28.156000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00094: on_time=2026-05-18 20:48:35.824000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00095: on_time=2026-05-18 20:48:43.570000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00096: on_time=2026-05-18 20:48:51.434000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00097: on_time=2026-05-18 20:48:59.200000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00098: on_time=2026-05-18 20:49:07.682000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00099: on_time=2026-05-18 20:49:16.284000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00100: on_time=2026-05-18 20:49:24.874000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00101: on_time=2026-05-18 20:51:14.780000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00102: on_time=2026-05-18 20:51:42.516000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00103: on_time=2026-05-18 20:54:04.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00104: on_time=2026-05-18 20:56:02.100000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00105: on_time=2026-05-18 20:57:48.462000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00106: on_time=2026-05-18 20:57:58.748000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00107: on_time=2026-05-18 20:58:09.364000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00108: on_time=2026-05-18 20:58:19.238000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00109: on_time=2026-05-18 20:58:30.014000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00110: on_time=2026-05-18 20:58:30.336000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00111: on_time=2026-05-18 20:58:40.136000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00112: on_time=2026-05-18 20:58:40.462000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00113: on_time=2026-05-18 21:00:07.920000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00114: on_time=2026-05-18 21:00:26.998000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00115: on_time=2026-05-18 21:00:36.122000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00116: on_time=2026-05-18 21:00:45.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00117: on_time=2026-05-18 21:01:06.296000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00118: on_time=2026-05-18 21:01:15.092000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00119: on_time=2026-05-18 21:01:24.622000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00120: on_time=2026-05-18 21:01:33.422000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00121: on_time=2026-05-18 21:01:46.328000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00122: on_time=2026-05-18 21:02:07.904000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00123: on_time=2026-05-18 21:02:19.464000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00124: on_time=2026-05-18 21:03:30.776000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00125: on_time=2026-05-18 21:03:39.406000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00126: on_time=2026-05-18 21:03:47.670000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00127: on_time=2026-05-18 21:03:56.448000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00128: on_time=2026-05-18 21:04:07.392000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00129: on_time=2026-05-18 21:04:13.012000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00130: on_time=2026-05-18 21:04:21.314000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00131: on_time=2026-05-18 21:04:30.092000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00132: on_time=2026-05-18 21:04:38.580000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00133: on_time=2026-05-18 21:04:47.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00134: on_time=2026-05-18 21:05:58.778000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00135: on_time=2026-05-18 21:06:07.682000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00136: on_time=2026-05-18 21:06:17.016000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00137: on_time=2026-05-18 21:06:26.014000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00138: on_time=2026-05-18 21:06:34.552000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00139: on_time=2026-05-18 21:06:43.488000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00140: on_time=2026-05-18 21:06:52.152000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00141: on_time=2026-05-18 21:07:00.978000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00142: on_time=2026-05-18 21:07:09.484000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00143: on_time=2026-05-18 21:07:18.566000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00144: on_time=2026-05-18 21:09:28.704000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00145: on_time=2026-05-18 21:09:36.412000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00146: on_time=2026-05-18 21:09:44.470000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00147: on_time=2026-05-18 21:09:52.102000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00148: on_time=2026-05-18 21:09:59.544000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00149: on_time=2026-05-18 21:10:06.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00150: on_time=2026-05-18 21:10:14.710000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00151: on_time=2026-05-18 21:10:22.284000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00152: on_time=2026-05-18 21:10:30.452000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00153: on_time=2026-05-18 21:10:38.048000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00154: on_time=2026-05-18 21:11:51.160000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00155: on_time=2026-05-18 21:11:59.978000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00156: on_time=2026-05-18 21:12:06.988000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00157: on_time=2026-05-18 21:12:16.178000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00158: on_time=2026-05-18 21:12:25.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00159: on_time=2026-05-18 21:12:34.300000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00160: on_time=2026-05-18 21:12:43.436000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00161: on_time=2026-05-18 21:12:52.620000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00162: on_time=2026-05-18 21:12:59.620000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00163: on_time=2026-05-18 21:13:08.954000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00164: on_time=2026-05-18 21:14:14.206000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00165: on_time=2026-05-18 21:14:36.186000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00166: on_time=2026-05-18 21:14:46.602000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00167: on_time=2026-05-18 21:14:55.542000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00168: on_time=2026-05-18 21:15:03.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00169: on_time=2026-05-18 21:15:11.890000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00170: on_time=2026-05-18 21:15:12.188000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00171: on_time=2026-05-18 21:15:17.768000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00172: on_time=2026-05-18 21:15:26.162000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00173: on_time=2026-05-18 21:15:34.544000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00174: on_time=2026-05-18 21:15:43.046000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00175: on_time=2026-05-18 21:15:52.636000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00176: on_time=2026-05-18 21:16:48.104000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00177: on_time=2026-05-18 21:16:55.960000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00178: on_time=2026-05-18 21:17:03.826000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00179: on_time=2026-05-18 21:17:11.794000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00180: on_time=2026-05-18 21:17:19.310000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00181: on_time=2026-05-18 21:17:28.366000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00182: on_time=2026-05-18 21:17:36.292000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00183: on_time=2026-05-18 21:17:43.328000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00184: on_time=2026-05-18 21:17:51.454000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00185: on_time=2026-05-18 21:17:59.656000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00186: on_time=2026-05-18 21:19:01.890000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00187: on_time=2026-05-18 21:19:10.712000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00188: on_time=2026-05-18 21:19:19.484000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00189: on_time=2026-05-18 21:19:29.178000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00190: on_time=2026-05-18 21:19:38.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00191: on_time=2026-05-18 21:19:47.206000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00192: on_time=2026-05-18 21:19:56.476000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00193: on_time=2026-05-18 21:20:05.638000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00194: on_time=2026-05-18 21:20:15.868000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00195: on_time=2026-05-18 21:20:24.866000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00196: on_time=2026-05-18 21:22:26.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00197: on_time=2026-05-18 21:22:41.742000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00198: on_time=2026-05-18 21:22:57.626000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00199: on_time=2026-05-18 21:23:08.816000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00200: on_time=2026-05-18 21:23:21.180000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00201: on_time=2026-05-18 21:23:41.628000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00202: on_time=2026-05-18 21:23:53.062000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00203: on_time=2026-05-18 21:27:18.016000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00204: on_time=2026-05-18 21:27:27.580000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00205: on_time=2026-05-18 21:27:41.490000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00206: on_time=2026-05-18 21:27:51.458000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00207: on_time=2026-05-18 21:28:01.138000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00208: on_time=2026-05-18 21:28:12.720000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00209: on_time=2026-05-18 21:28:24.254000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00210: on_time=2026-05-18 21:28:24.518000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00211: on_time=2026-05-18 21:28:34.092000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00212: on_time=2026-05-18 21:28:42.634000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00213: on_time=2026-05-18 21:28:52.064000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00214: on_time=2026-05-18 21:29:03.464000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00215: on_time=2026-05-18 21:30:42.582000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00216: on_time=2026-05-18 21:31:02.830000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00217: on_time=2026-05-18 21:31:03.104000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00218: on_time=2026-05-18 21:31:14.706000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00219: on_time=2026-05-18 21:31:23.368000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00220: on_time=2026-05-18 21:31:32.276000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00221: on_time=2026-05-18 21:31:32.552000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00222: on_time=2026-05-18 21:31:42.006000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00223: on_time=2026-05-18 21:31:51.312000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00224: on_time=2026-05-18 21:32:02.100000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00225: on_time=2026-05-18 21:32:11.522000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00226: on_time=2026-05-18 21:32:20.800000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00227: on_time=2026-05-18 21:32:29.396000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00228: on_time=2026-05-18 21:33:28.168000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00229: on_time=2026-05-18 21:33:43.768000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00230: on_time=2026-05-18 21:33:57.514000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00231: on_time=2026-05-18 21:34:07.266000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00232: on_time=2026-05-18 21:34:07.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00233: on_time=2026-05-18 21:34:16.838000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00234: on_time=2026-05-18 21:34:26.532000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00235: on_time=2026-05-18 21:34:39.888000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00236: on_time=2026-05-18 21:34:47.068000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00237: on_time=2026-05-18 21:34:58.116000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00238: on_time=2026-05-18 21:34:58.498000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00239: on_time=2026-05-18 21:35:18.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00240: on_time=2026-05-18 21:35:18.372000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00241: on_time=2026-05-18 21:35:25.974000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00242: on_time=2026-05-18 21:35:35.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00243: on_time=2026-05-18 21:35:45.604000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00244: on_time=2026-05-18 21:35:56.180000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00245: on_time=2026-05-18 21:36:06.546000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00246: on_time=2026-05-18 21:36:19.138000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00247: on_time=2026-05-18 21:36:19.524000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00248: on_time=2026-05-18 21:36:29.870000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00249: on_time=2026-05-18 21:37:19.332000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00250: on_time=2026-05-18 21:37:26.838000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00251: on_time=2026-05-18 21:37:36.616000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00252: on_time=2026-05-18 21:37:46.240000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00253: on_time=2026-05-18 21:37:46.638000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00254: on_time=2026-05-18 21:37:56.828000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00255: on_time=2026-05-18 21:37:57.246000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00256: on_time=2026-05-18 21:38:05.614000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00257: on_time=2026-05-18 21:38:15.676000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00258: on_time=2026-05-18 21:38:26.426000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00259: on_time=2026-05-18 21:38:46.154000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00260: on_time=2026-05-18 21:40:48.844000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00261: on_time=2026-05-18 21:40:58.252000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00262: on_time=2026-05-18 21:41:07.946000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00263: on_time=2026-05-18 21:41:08.364000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00264: on_time=2026-05-18 21:41:17.592000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00265: on_time=2026-05-18 21:41:27.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00266: on_time=2026-05-18 21:41:35.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00267: on_time=2026-05-18 21:41:45.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00268: on_time=2026-05-18 21:42:39.762000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00269: on_time=2026-05-18 21:42:49.530000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00270: on_time=2026-05-18 21:42:49.908000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00271: on_time=2026-05-18 21:42:59.762000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00272: on_time=2026-05-18 21:43:11.610000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00273: on_time=2026-05-18 21:43:20.008000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00274: on_time=2026-05-18 21:43:30.320000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00275: on_time=2026-05-18 21:43:39.928000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00276: on_time=2026-05-18 21:44:43.188000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00277: on_time=2026-05-18 21:44:52.918000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00278: on_time=2026-05-18 21:45:04.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00279: on_time=2026-05-18 21:45:10.142000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00280: on_time=2026-05-18 21:45:21.954000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00281: on_time=2026-05-18 21:46:13.558000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00282: on_time=2026-05-18 21:46:13.842000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00283: on_time=2026-05-18 21:46:29.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00284: on_time=2026-05-18 21:46:41.390000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00285: on_time=2026-05-18 21:47:13.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00286: on_time=2026-05-18 21:47:23.740000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00287: on_time=2026-05-18 21:47:24.036000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00288: on_time=2026-05-18 21:47:34.166000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00289: on_time=2026-05-18 21:47:44.722000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00290: on_time=2026-05-18 21:47:55.324000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00291: on_time=2026-05-18 21:48:06.052000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00292: on_time=2026-05-18 21:48:15.964000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00293: on_time=2026-05-18 21:48:26.648000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00294: on_time=2026-05-18 21:48:26.916000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00295: on_time=2026-05-18 21:49:46.224000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00296: on_time=2026-05-18 21:49:56.634000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00297: on_time=2026-05-18 21:50:06.064000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00298: on_time=2026-05-18 21:50:15.712000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00299: on_time=2026-05-18 21:50:23.492000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00300: on_time=2026-05-18 21:50:33.846000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00301: on_time=2026-05-18 21:50:45.422000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00302: on_time=2026-05-18 21:50:55.870000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00303: on_time=2026-05-18 21:51:03.768000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00304: on_time=2026-05-18 21:51:15.600000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00305: on_time=2026-05-18 21:51:26.742000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00306: on_time=2026-05-18 21:52:19.928000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00307: on_time=2026-05-18 21:52:53.770000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00308: on_time=2026-05-18 21:53:01.328000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00309: on_time=2026-05-18 21:53:10.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00310: on_time=2026-05-18 21:53:19.374000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00311: on_time=2026-05-18 21:53:27.104000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00312: on_time=2026-05-18 21:53:34.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00313: on_time=2026-05-18 21:53:42.638000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00314: on_time=2026-05-18 21:53:54.368000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00315: on_time=2026-05-18 21:54:03.532000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00316: on_time=2026-05-18 21:55:16.648000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00317: on_time=2026-05-18 21:55:24.810000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00318: on_time=2026-05-18 21:55:32.582000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00319: on_time=2026-05-18 21:55:40.528000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00320: on_time=2026-05-18 21:55:48.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00321: on_time=2026-05-18 21:55:57.158000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00322: on_time=2026-05-18 21:56:04.946000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00323: on_time=2026-05-18 21:56:12.614000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00324: on_time=2026-05-18 21:56:37.184000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00325: on_time=2026-05-18 21:56:45.406000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00326: on_time=2026-05-18 21:56:53.066000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00327: on_time=2026-05-18 21:57:52.370000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00328: on_time=2026-05-18 21:58:02.740000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00329: on_time=2026-05-18 21:58:12.228000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00330: on_time=2026-05-18 21:59:06.014000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00331: on_time=2026-05-18 21:59:15.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00332: on_time=2026-05-18 21:59:25.072000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00333: on_time=2026-05-18 21:59:25.368000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00334: on_time=2026-05-18 21:59:34.024000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00335: on_time=2026-05-18 21:59:43.388000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00336: on_time=2026-05-18 21:59:54.230000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00337: on_time=2026-05-18 22:00:04.328000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00338: on_time=2026-05-18 22:00:04.528000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00339: on_time=2026-05-18 22:00:14.246000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00340: on_time=2026-05-18 22:00:23.778000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00341: on_time=2026-05-18 22:00:34.064000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00342: on_time=2026-05-18 22:03:14.112000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00343: on_time=2026-05-18 22:03:14.394000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00344: on_time=2026-05-18 22:04:00.670000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00345: on_time=2026-05-18 22:04:01.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00346: on_time=2026-05-18 22:10:10.476000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00347: on_time=2026-05-18 22:24:43.960000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00348: on_time=2026-05-18 22:26:41.828000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00349: on_time=2026-05-18 22:28:46.128000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00350: on_time=2026-05-18 22:29:07.982000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00351: on_time=2026-05-18 22:29:18.674000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00352: on_time=2026-05-18 22:29:25.394000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00353: on_time=2026-05-18 22:29:43.224000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00354: on_time=2026-05-18 22:29:51.936000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00355: on_time=2026-05-18 22:37:50.194000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00356: on_time=2026-05-18 22:38:01.090000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00357: on_time=2026-05-18 22:38:12.062000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00358: on_time=2026-05-18 22:38:23.126000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00359: on_time=2026-05-18 22:38:33.732000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00360: on_time=2026-05-18 22:38:33.944000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00361: on_time=2026-05-18 22:38:47.680000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00362: on_time=2026-05-18 22:38:58.490000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00363: on_time=2026-05-18 22:39:09.282000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00364: on_time=2026-05-18 22:39:22.894000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00365: on_time=2026-05-18 22:39:23.170000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00366: on_time=2026-05-18 22:39:36.046000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00367: on_time=2026-05-18 22:39:43.230000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00368: on_time=2026-05-18 22:39:51.412000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00369: on_time=2026-05-18 22:39:51.726000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00370: on_time=2026-05-18 22:40:21.122000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00371: on_time=2026-05-18 22:41:04.608000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00372: on_time=2026-05-18 22:41:10.948000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00373: on_time=2026-05-18 22:41:17.860000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00374: on_time=2026-05-18 22:41:50.530000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00375: on_time=2026-05-18 22:42:18.066000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00376: on_time=2026-05-18 22:42:30.048000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00377: on_time=2026-05-18 22:42:40.982000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00378: on_time=2026-05-18 22:42:48.298000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00379: on_time=2026-05-18 22:42:56.332000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00380: on_time=2026-05-18 22:43:18.182000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00381: on_time=2026-05-18 22:43:29.824000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00382: on_time=2026-05-18 22:44:07.982000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00383: on_time=2026-05-18 22:44:19.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00384: on_time=2026-05-18 22:44:30.130000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00385: on_time=2026-05-18 22:44:39.092000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00386: on_time=2026-05-18 22:47:59.136000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00387: on_time=2026-05-18 22:48:09.756000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00388: on_time=2026-05-18 22:48:20.400000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00389: on_time=2026-05-18 22:48:30.788000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00390: on_time=2026-05-18 22:49:48.974000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00391: on_time=2026-05-18 22:50:04.764000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00392: on_time=2026-05-18 22:50:16.034000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00393: on_time=2026-05-18 22:50:28.176000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00394: on_time=2026-05-18 22:50:40.080000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00395: on_time=2026-05-18 22:50:50.912000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00396: on_time=2026-05-18 22:51:02.308000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00397: on_time=2026-05-18 22:51:26.478000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00398: on_time=2026-05-18 22:51:38.510000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00399: on_time=2026-05-18 22:51:47.940000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00400: on_time=2026-05-18 22:53:36.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00401: on_time=2026-05-18 22:53:47.860000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00402: on_time=2026-05-18 22:54:12.696000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00403: on_time=2026-05-18 22:54:25.324000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00404: on_time=2026-05-18 22:54:36.404000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00405: on_time=2026-05-18 22:54:48.206000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00406: on_time=2026-05-18 22:55:01.324000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00407: on_time=2026-05-18 22:56:08.894000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00408: on_time=2026-05-18 22:56:20.400000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00409: on_time=2026-05-18 22:56:32.296000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00410: on_time=2026-05-18 22:56:44.244000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00411: on_time=2026-05-18 22:56:55.562000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00412: on_time=2026-05-18 22:57:07.528000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00413: on_time=2026-05-18 22:57:19.860000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00414: on_time=2026-05-18 22:57:27.612000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00415: on_time=2026-05-18 22:57:38.256000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00416: on_time=2026-05-18 22:57:50.184000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00417: on_time=2026-05-18 22:58:02.398000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00418: on_time=2026-05-18 22:58:14.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00419: on_time=2026-05-18 22:58:26.398000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00420: on_time=2026-05-18 23:00:19.796000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00421: on_time=2026-05-18 23:01:02.640000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00422: on_time=2026-05-18 23:01:03.792000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00423: on_time=2026-05-18 23:01:04.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00424: on_time=2026-05-18 23:01:05.054000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00425: on_time=2026-05-18 23:01:05.624000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00426: on_time=2026-05-18 23:01:10.004000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00427: on_time=2026-05-18 23:01:11.820000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00428: on_time=2026-05-18 23:01:12.386000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00429: on_time=2026-05-18 23:01:14.716000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00430: on_time=2026-05-18 23:01:16.576000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00431: on_time=2026-05-18 23:01:17.794000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00432: on_time=2026-05-18 23:01:18.446000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00433: on_time=2026-05-18 23:01:22.090000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00434: on_time=2026-05-18 23:01:23.294000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00435: on_time=2026-05-18 23:01:24.462000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00436: on_time=2026-05-18 23:01:25.004000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00437: on_time=2026-05-18 23:01:27.634000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00438: on_time=2026-05-18 23:01:28.252000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00439: on_time=2026-05-18 23:01:28.862000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00440: on_time=2026-05-18 23:01:29.448000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00441: on_time=2026-05-18 23:01:30.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00442: on_time=2026-05-18 23:01:30.644000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00443: on_time=2026-05-18 23:01:36.080000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00444: on_time=2026-05-18 23:01:36.632000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00445: on_time=2026-05-18 23:01:42.002000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00446: on_time=2026-05-18 23:01:43.660000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00447: on_time=2026-05-18 23:09:43.228000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00448: on_time=2026-05-18 23:09:59.278000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00449: on_time=2026-05-18 23:12:41.934000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Refraction2m_T1_N2_E00450: on_time=2026-05-18 23:13:08.346000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

====================================================================================================
Processing T1_N2_Nodal2

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

Discovered 35 T1.N2.DPZ stations
['06809', '07600', '08003', '08405', '08808', '09210', '09605', '10000', '10408', '10603', '10814', '11005', '11215', '11400', '11611', '11797', '12018', '12204', '12413', '12638', '12815', '12996', '13216', '13402', '13620', '13782', '14000', '14400', '14800', '15195', '16000', '16400', '16809', '17604', '18405']
T1_N2_Nodal2 chunk 0: 2026-05-19T12:59:00.000000Z to 2026-05-19T13:00:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 1: 2026-05-19T13:00:00.000000Z to 2026-05-19T13:01:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 2: 2026-05-19T13:01:00.000000Z to 2026-05-19T13:02:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 3: 2026-05-19T13:02:00.000000Z to 2026-05-19T13:03:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 4: 2026-05-19T13:03:00.000000Z to 2026-05-19T13:04:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 5: 2026-05-19T13:04:00.000000Z to 2026-05-19T13:05:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 6: 2026-05-19T13:05:00.000000Z to 2026-05-19T13:06:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 7: 2026-05-19T13:06:00.000000Z to 2026-05-19T13:07:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 8: 2026-05-19T13:07:00.000000Z to 2026-05-19T13:08:00.000000Z
  read 34 traces, 34 stations
  detections: 8
T1_N2_Nodal2 chunk 9: 2026-05-19T13:08:00.000000Z to 2026-05-19T13:09:00.000000Z
  read 34 traces, 34 stations
  detections: 6
T1_N2_Nodal2 chunk 10: 2026-05-19T13:09:00.000000Z to 2026-05-19T13:10:00.000000Z
  read 34 traces, 34 stations
  detections: 7
T1_N2_Nodal2 chunk 11: 2026-05-19T13:10:00.000000Z to 2026-05-19T13:11:00.000000Z
  read 34 traces, 34 stations
  detections: 20
T1_N2_Nodal2 chunk 12: 2026-05-19T13:11:00.000000Z to 2026-05-19T13:12:00.000000Z
  read 34 traces, 34 stations
  detections: 13
T1_N2_Nodal2 chunk 13: 2026-05-19T13:12:00.000000Z to 2026-05-19T13:13:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 14: 2026-05-19T13:13:00.000000Z to 2026-05-19T13:14:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 15: 2026-05-19T13:14:00.000000Z to 2026-05-19T13:15:00.000000Z
  read 34 traces, 34 stations
  detections: 20
T1_N2_Nodal2 chunk 16: 2026-05-19T13:15:00.000000Z to 2026-05-19T13:16:00.000000Z
  read 34 traces, 34 stations
  detections: 10
T1_N2_Nodal2 chunk 17: 2026-05-19T13:16:00.000000Z to 2026-05-19T13:17:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 18: 2026-05-19T13:17:00.000000Z to 2026-05-19T13:18:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 19: 2026-05-19T13:18:00.000000Z to 2026-05-19T13:19:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 20: 2026-05-19T13:19:00.000000Z to 2026-05-19T13:20:00.000000Z
  read 34 traces, 34 stations
T1_N2_Nodal2 chunk 21: 2026-05-19T13:20:00.000000Z to 2026-05-19T13:21:00.000000Z
  read 34 traces, 34 stations
Raw detections: 84; merged detections: 81

T1_N2_Nodal2_T1_N2_E00001: on_time=2026-05-19 13:07:40.072000
  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00002: on_time=2026-05-19 13:07:42.760000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00003: on_time=2026-05-19 13:07:45.484000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00004: on_time=2026-05-19 13:07:48.160000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00005: on_time=2026-05-19 13:07:50.770000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00006: on_time=2026-05-19 13:07:53.308000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00007: on_time=2026-05-19 13:07:55.852000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00008: on_time=2026-05-19 13:07:58.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00009: on_time=2026-05-19 13:08:00.878000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00010: on_time=2026-05-19 13:08:03.528000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00011: on_time=2026-05-19 13:08:53.632000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00012: on_time=2026-05-19 13:08:55.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00013: on_time=2026-05-19 13:08:58.314000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00014: on_time=2026-05-19 13:09:00.976000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00015: on_time=2026-05-19 13:09:03.540000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00016: on_time=2026-05-19 13:09:06.124000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00017: on_time=2026-05-19 13:09:08.768000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00018: on_time=2026-05-19 13:09:11.614000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00019: on_time=2026-05-19 13:09:14.540000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00020: on_time=2026-05-19 13:09:17.680000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00021: on_time=2026-05-19 13:10:08.302000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00022: on_time=2026-05-19 13:10:10.950000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00023: on_time=2026-05-19 13:10:13.256000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00024: on_time=2026-05-19 13:10:15.620000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00025: on_time=2026-05-19 13:10:17.968000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00026: on_time=2026-05-19 13:10:20.416000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00027: on_time=2026-05-19 13:10:22.842000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00028: on_time=2026-05-19 13:10:25.228000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00029: on_time=2026-05-19 13:10:27.360000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00030: on_time=2026-05-19 13:10:29.618000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00031: on_time=2026-05-19 13:10:36.904000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00032: on_time=2026-05-19 13:10:39.104000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00033: on_time=2026-05-19 13:10:41.286000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00034: on_time=2026-05-19 13:10:43.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00035: on_time=2026-05-19 13:10:45.400000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00036: on_time=2026-05-19 13:10:47.476000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00037: on_time=2026-05-19 13:10:49.470000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00038: on_time=2026-05-19 13:10:51.434000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00039: on_time=2026-05-19 13:10:53.382000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00040: on_time=2026-05-19 13:10:55.360000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00041: on_time=2026-05-19 13:11:24.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00042: on_time=2026-05-19 13:11:24.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00043: on_time=2026-05-19 13:11:26.564000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00044: on_time=2026-05-19 13:11:33.562000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00045: on_time=2026-05-19 13:11:36.190000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00046: on_time=2026-05-19 13:11:38.632000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00047: on_time=2026-05-19 13:11:41.306000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00048: on_time=2026-05-19 13:11:44.118000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00049: on_time=2026-05-19 13:11:46.756000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00050: on_time=2026-05-19 13:11:49.432000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00051: on_time=2026-05-19 13:11:52.058000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00052: on_time=2026-05-19 13:14:03.064000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00053: on_time=2026-05-19 13:14:05.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00054: on_time=2026-05-19 13:14:07.632000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00055: on_time=2026-05-19 13:14:09.796000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00056: on_time=2026-05-19 13:14:12.078000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00057: on_time=2026-05-19 13:14:14.322000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00058: on_time=2026-05-19 13:14:16.462000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00059: on_time=2026-05-19 13:14:18.752000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00060: on_time=2026-05-19 13:14:20.986000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00061: on_time=2026-05-19 13:14:23.256000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00062: on_time=2026-05-19 13:14:30.774000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00063: on_time=2026-05-19 13:14:32.890000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00064: on_time=2026-05-19 13:14:34.960000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00065: on_time=2026-05-19 13:14:36.994000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00066: on_time=2026-05-19 13:14:39.022000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00067: on_time=2026-05-19 13:14:41.088000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00068: on_time=2026-05-19 13:14:42.982000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00069: on_time=2026-05-19 13:14:44.964000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00070: on_time=2026-05-19 13:14:46.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00071: on_time=2026-05-19 13:14:48.848000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00072: on_time=2026-05-19 13:15:06.424000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00073: on_time=2026-05-19 13:15:08.712000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00074: on_time=2026-05-19 13:15:10.790000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00075: on_time=2026-05-19 13:15:13.258000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00076: on_time=2026-05-19 13:15:15.524000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00077: on_time=2026-05-19 13:15:17.730000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00078: on_time=2026-05-19 13:15:20.208000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00079: on_time=2026-05-19 13:15:22.506000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00080: on_time=2026-05-19 13:15:24.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N2_Nodal2_T1_N2_E00081: on_time=2026-05-19 13:15:26.874000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

====================================================================================================
Processing T1_N3_Nodal3

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

Discovered 35 T1.N3.DPZ stations
['02800', '03600', '04400', '05207', '06004', '06809', '07600', '08003', '08405', '08808', '09210', '09605', '10000', '10398', '10800', '11202', '11600', '12005', '12402', '12801', '13202', '13605', '14000', '14400', '14800', '15195', '16000', '16400', '16809', '17604', '18405', '19200', '20000', '20800', '21600']
T1_N3_Nodal3 chunk 0: 2026-05-19T13:59:00.000000Z to 2026-05-19T14:00:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 1: 2026-05-19T14:00:00.000000Z to 2026-05-19T14:01:00.000000Z
  read 34 traces, 34 stations
  detections: 15
T1_N3_Nodal3 chunk 2: 2026-05-19T14:01:00.000000Z to 2026-05-19T14:02:00.000000Z
  read 34 traces, 34 stations
  detections: 39
T1_N3_Nodal3 chunk 3: 2026-05-19T14:02:00.000000Z to 2026-05-19T14:03:00.000000Z
  read 34 traces, 34 stations
  detections: 7
T1_N3_Nodal3 chunk 4: 2026-05-19T14:03:00.000000Z to 2026-05-19T14:04:00.000000Z
  read 34 traces, 34 stations
  detections: 7
T1_N3_Nodal3 chunk 5: 2026-05-19T14:04:00.000000Z to 2026-05-19T14:05:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 6: 2026-05-19T14:05:00.000000Z to 2026-05-19T14:06:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 7: 2026-05-19T14:06:00.000000Z to 2026-05-19T14:07:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 8: 2026-05-19T14:07:00.000000Z to 2026-05-19T14:08:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 9: 2026-05-19T14:08:00.000000Z to 2026-05-19T14:09:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 10: 2026-05-19T14:09:00.000000Z to 2026-05-19T14:10:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 11: 2026-05-19T14:10:00.000000Z to 2026-05-19T14:11:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 12: 2026-05-19T14:11:00.000000Z to 2026-05-19T14:12:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 13: 2026-05-19T14:12:00.000000Z to 2026-05-19T14:13:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 14: 2026-05-19T14:13:00.000000Z to 2026-05-19T14:14:00.000000Z
  read 34 traces, 34 stations
T1_N3_Nodal3 chunk 15: 2026-05-19T14:14:00.000000Z to 2026-05-19T14:15:00.000000Z
  read 34 traces, 34 stations
Raw detections: 68; merged detections: 43

T1_N3_Nodal3_T1_N3_E00001: on_time=2026-05-19 14:00:18.624000
  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00002: on_time=2026-05-19 14:00:21.196000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00003: on_time=2026-05-19 14:00:23.698000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00004: on_time=2026-05-19 14:00:26.138000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00005: on_time=2026-05-19 14:00:28.480000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00006: on_time=2026-05-19 14:00:30.706000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00007: on_time=2026-05-19 14:00:35.408000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00008: on_time=2026-05-19 14:00:37.698000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00009: on_time=2026-05-19 14:00:48.640000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00010: on_time=2026-05-19 14:00:50.796000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00011: on_time=2026-05-19 14:00:52.896000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00012: on_time=2026-05-19 14:00:54.984000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00013: on_time=2026-05-19 14:00:57.054000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00014: on_time=2026-05-19 14:00:59.138000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00015: on_time=2026-05-19 14:01:01.250000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00016: on_time=2026-05-19 14:01:03.324000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00017: on_time=2026-05-19 14:01:05.302000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00018: on_time=2026-05-19 14:01:17.504000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00019: on_time=2026-05-19 14:01:19.782000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00020: on_time=2026-05-19 14:01:22.134000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00021: on_time=2026-05-19 14:01:24.588000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00022: on_time=2026-05-19 14:01:27.046000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00023: on_time=2026-05-19 14:01:29.398000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00024: on_time=2026-05-19 14:01:31.812000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00025: on_time=2026-05-19 14:01:34.156000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00026: on_time=2026-05-19 14:01:36.532000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00027: on_time=2026-05-19 14:01:38.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00028: on_time=2026-05-19 14:01:46.832000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00029: on_time=2026-05-19 14:01:49.246000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00030: on_time=2026-05-19 14:01:51.520000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00031: on_time=2026-05-19 14:01:53.892000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00032: on_time=2026-05-19 14:01:56.214000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00033: on_time=2026-05-19 14:01:58.448000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00034: on_time=2026-05-19 14:02:00.878000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00035: on_time=2026-05-19 14:02:19.806000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00036: on_time=2026-05-19 14:02:21.914000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00037: on_time=2026-05-19 14:02:55.502000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00038: on_time=2026-05-19 14:02:57.880000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00039: on_time=2026-05-19 14:03:00.534000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00040: on_time=2026-05-19 14:03:05.726000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00041: on_time=2026-05-19 14:03:08.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00042: on_time=2026-05-19 14:03:10.758000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

T1_N3_Nodal3_T1_N3_E00043: on_time=2026-05-19 14:03:18.740000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 102 traces, 34 receivers

====================================================================================================
Processing T3_N4_Refraction1am
Discovered 35 T3.N4.DPZ stations
['00050', '00250', '00450', '00650', '00850', '01046', '01250', '01446', '01646', '01850', '02050', '02250', '02458', '02636', '02850', '03050', '03241', '03450', '03644', '03835', '04050', '04246', '04450', '04644', '04842', '05050', '05253', '05447', '05665', '05843', '06050', '06241', '06450', '06650', '06850']
T3_N4_Refraction1am chunk 0: 2026-05-19T16:02:00.000000Z to 2026-05-19T16:03:00.000000Z

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 1: 2026-05-19T16:03:00.000000Z to 2026-05-19T16:04:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 2: 2026-05-19T16:04:00.000000Z to 2026-05-19T16:05:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 3: 2026-05-19T16:05:00.000000Z to 2026-05-19T16:06:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 4: 2026-05-19T16:06:00.000000Z to 2026-05-19T16:07:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 5: 2026-05-19T16:07:00.000000Z to 2026-05-19T16:08:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 6: 2026-05-19T16:08:00.000000Z to 2026-05-19T16:09:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 7: 2026-05-19T16:09:00.000000Z to 2026-05-19T16:10:00.000000Z
  read 35 traces, 35 stations
  detections: 9
T3_N4_Refraction1am chunk 8: 2026-05-19T16:10:00.000000Z to 2026-05-19T16:11:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 9: 2026-05-19T16:11:00.000000Z to 2026-05-19T16:12:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 10: 2026-05-19T16:12:00.000000Z to 2026-05-19T16:13:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 11: 2026-05-19T16:13:00.000000Z to 2026-05-19T16:14:00.000000Z
  read 35 traces, 35 stations
  detections: 8
T3_N4_Refraction1am chunk 12: 2026-05-19T16:14:00.000000Z to 2026-05-19T16:15:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 13: 2026-05-19T16:15:00.000000Z to 2026-05-19T16:16:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 14: 2026-05-19T16:16:00.000000Z to 2026-05-19T16:17:00.000000Z
  read 35 traces, 35 stations
  detections: 13
T3_N4_Refraction1am chunk 15: 2026-05-19T16:17:00.000000Z to 2026-05-19T16:18:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 16: 2026-05-19T16:18:00.000000Z to 2026-05-19T16:19:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 17: 2026-05-19T16:19:00.000000Z to 2026-05-19T16:20:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T3_N4_Refraction1am chunk 18: 2026-05-19T16:20:00.000000Z to 2026-05-19T16:21:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 19: 2026-05-19T16:21:00.000000Z to 2026-05-19T16:22:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T3_N4_Refraction1am chunk 20: 2026-05-19T16:22:00.000000Z to 2026-05-19T16:23:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 21: 2026-05-19T16:23:00.000000Z to 2026-05-19T16:24:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 22: 2026-05-19T16:24:00.000000Z to 2026-05-19T16:25:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 23: 2026-05-19T16:25:00.000000Z to 2026-05-19T16:26:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 24: 2026-05-19T16:26:00.000000Z to 2026-05-19T16:27:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 25: 2026-05-19T16:27:00.000000Z to 2026-05-19T16:28:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 26: 2026-05-19T16:28:00.000000Z to 2026-05-19T16:29:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 27: 2026-05-19T16:29:00.000000Z to 2026-05-19T16:30:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 28: 2026-05-19T16:30:00.000000Z to 2026-05-19T16:31:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T3_N4_Refraction1am chunk 29: 2026-05-19T16:31:00.000000Z to 2026-05-19T16:32:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 30: 2026-05-19T16:32:00.000000Z to 2026-05-19T16:33:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 31: 2026-05-19T16:33:00.000000Z to 2026-05-19T16:34:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 32: 2026-05-19T16:34:00.000000Z to 2026-05-19T16:35:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 33: 2026-05-19T16:35:00.000000Z to 2026-05-19T16:36:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 34: 2026-05-19T16:36:00.000000Z to 2026-05-19T16:37:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 35: 2026-05-19T16:37:00.000000Z to 2026-05-19T16:38:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 36: 2026-05-19T16:38:00.000000Z to 2026-05-19T16:39:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 37: 2026-05-19T16:39:00.000000Z to 2026-05-19T16:40:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T3_N4_Refraction1am chunk 38: 2026-05-19T16:40:00.000000Z to 2026-05-19T16:41:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 39: 2026-05-19T16:41:00.000000Z to 2026-05-19T16:42:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 40: 2026-05-19T16:42:00.000000Z to 2026-05-19T16:43:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 41: 2026-05-19T16:43:00.000000Z to 2026-05-19T16:44:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 42: 2026-05-19T16:44:00.000000Z to 2026-05-19T16:45:00.000000Z
  read 35 traces, 35 stations
  detections: 14
T3_N4_Refraction1am chunk 43: 2026-05-19T16:45:00.000000Z to 2026-05-19T16:46:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 44: 2026-05-19T16:46:00.000000Z to 2026-05-19T16:47:00.000000Z
  read 35 traces, 35 stations
  detections: 11
T3_N4_Refraction1am chunk 45: 2026-05-19T16:47:00.000000Z to 2026-05-19T16:48:00.000000Z
  read 35 traces, 35 stations
  detections: 10
T3_N4_Refraction1am chunk 46: 2026-05-19T16:48:00.000000Z to 2026-05-19T16:49:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 47: 2026-05-19T16:49:00.000000Z to 2026-05-19T16:50:00.000000Z
  read 35 traces, 35 stations
  detections: 16
T3_N4_Refraction1am chunk 48: 2026-05-19T16:50:00.000000Z to 2026-05-19T16:51:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T3_N4_Refraction1am chunk 49: 2026-05-19T16:51:00.000000Z to 2026-05-19T16:52:00.000000Z
  read 35 traces, 35 stations
  detections: 13
T3_N4_Refraction1am chunk 50: 2026-05-19T16:52:00.000000Z to 2026-05-19T16:53:00.000000Z
  read 35 traces, 35 stations
  detections: 10
T3_N4_Refraction1am chunk 51: 2026-05-19T16:53:00.000000Z to 2026-05-19T16:54:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 52: 2026-05-19T16:54:00.000000Z to 2026-05-19T16:55:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 53: 2026-05-19T16:55:00.000000Z to 2026-05-19T16:56:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 54: 2026-05-19T16:56:00.000000Z to 2026-05-19T16:57:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 55: 2026-05-19T16:57:00.000000Z to 2026-05-19T16:58:00.000000Z
  read 35 traces, 35 stations
  detections: 8
T3_N4_Refraction1am chunk 56: 2026-05-19T16:58:00.000000Z to 2026-05-19T16:59:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 57: 2026-05-19T16:59:00.000000Z to 2026-05-19T17:00:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 58: 2026-05-19T17:00:00.000000Z to 2026-05-19T17:01:00.000000Z
  read 35 traces, 35 stations
  detections: 8
T3_N4_Refraction1am chunk 59: 2026-05-19T17:01:00.000000Z to 2026-05-19T17:02:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 60: 2026-05-19T17:02:00.000000Z to 2026-05-19T17:03:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 61: 2026-05-19T17:03:00.000000Z to 2026-05-19T17:04:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 62: 2026-05-19T17:04:00.000000Z to 2026-05-19T17:05:00.000000Z
  read 35 traces, 35 stations
  detections: 11
T3_N4_Refraction1am chunk 63: 2026-05-19T17:05:00.000000Z to 2026-05-19T17:06:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 64: 2026-05-19T17:06:00.000000Z to 2026-05-19T17:07:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 65: 2026-05-19T17:07:00.000000Z to 2026-05-19T17:08:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 66: 2026-05-19T17:08:00.000000Z to 2026-05-19T17:09:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 67: 2026-05-19T17:09:00.000000Z to 2026-05-19T17:10:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 68: 2026-05-19T17:10:00.000000Z to 2026-05-19T17:11:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 69: 2026-05-19T17:11:00.000000Z to 2026-05-19T17:12:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 70: 2026-05-19T17:12:00.000000Z to 2026-05-19T17:13:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 71: 2026-05-19T17:13:00.000000Z to 2026-05-19T17:14:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 72: 2026-05-19T17:14:00.000000Z to 2026-05-19T17:15:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T3_N4_Refraction1am chunk 73: 2026-05-19T17:15:00.000000Z to 2026-05-19T17:16:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 74: 2026-05-19T17:16:00.000000Z to 2026-05-19T17:17:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 75: 2026-05-19T17:17:00.000000Z to 2026-05-19T17:18:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 76: 2026-05-19T17:18:00.000000Z to 2026-05-19T17:19:00.000000Z
  read 35 traces, 35 stations
  detections: 11
T3_N4_Refraction1am chunk 77: 2026-05-19T17:19:00.000000Z to 2026-05-19T17:20:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 78: 2026-05-19T17:20:00.000000Z to 2026-05-19T17:21:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 79: 2026-05-19T17:21:00.000000Z to 2026-05-19T17:22:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 80: 2026-05-19T17:22:00.000000Z to 2026-05-19T17:23:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 81: 2026-05-19T17:23:00.000000Z to 2026-05-19T17:24:00.000000Z
  read 35 traces, 35 stations
  detections: 12
T3_N4_Refraction1am chunk 82: 2026-05-19T17:24:00.000000Z to 2026-05-19T17:25:00.000000Z
  read 35 traces, 35 stations
  detections: 8
T3_N4_Refraction1am chunk 83: 2026-05-19T17:25:00.000000Z to 2026-05-19T17:26:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 84: 2026-05-19T17:26:00.000000Z to 2026-05-19T17:27:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 85: 2026-05-19T17:27:00.000000Z to 2026-05-19T17:28:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 86: 2026-05-19T17:28:00.000000Z to 2026-05-19T17:29:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 87: 2026-05-19T17:29:00.000000Z to 2026-05-19T17:30:00.000000Z
  read 35 traces, 35 stations
  detections: 11
T3_N4_Refraction1am chunk 88: 2026-05-19T17:30:00.000000Z to 2026-05-19T17:31:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 89: 2026-05-19T17:31:00.000000Z to 2026-05-19T17:32:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 90: 2026-05-19T17:32:00.000000Z to 2026-05-19T17:33:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 91: 2026-05-19T17:33:00.000000Z to 2026-05-19T17:34:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 92: 2026-05-19T17:34:00.000000Z to 2026-05-19T17:35:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 93: 2026-05-19T17:35:00.000000Z to 2026-05-19T17:36:00.000000Z
  read 35 traces, 35 stations
  detections: 12
T3_N4_Refraction1am chunk 94: 2026-05-19T17:36:00.000000Z to 2026-05-19T17:37:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 95: 2026-05-19T17:37:00.000000Z to 2026-05-19T17:38:00.000000Z
  read 35 traces, 35 stations
  detections: 10
T3_N4_Refraction1am chunk 96: 2026-05-19T17:38:00.000000Z to 2026-05-19T17:39:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 97: 2026-05-19T17:39:00.000000Z to 2026-05-19T17:40:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 98: 2026-05-19T17:40:00.000000Z to 2026-05-19T17:41:00.000000Z
  read 35 traces, 35 stations
  detections: 7
T3_N4_Refraction1am chunk 99: 2026-05-19T17:41:00.000000Z to 2026-05-19T17:42:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 100: 2026-05-19T17:42:00.000000Z to 2026-05-19T17:43:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 101: 2026-05-19T17:43:00.000000Z to 2026-05-19T17:44:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 102: 2026-05-19T17:44:00.000000Z to 2026-05-19T17:45:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 103: 2026-05-19T17:45:00.000000Z to 2026-05-19T17:46:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 104: 2026-05-19T17:46:00.000000Z to 2026-05-19T17:47:00.000000Z
  read 35 traces, 35 stations
  detections: 6
T3_N4_Refraction1am chunk 105: 2026-05-19T17:47:00.000000Z to 2026-05-19T17:48:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 106: 2026-05-19T17:48:00.000000Z to 2026-05-19T17:49:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 107: 2026-05-19T17:49:00.000000Z to 2026-05-19T17:50:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 108: 2026-05-19T17:50:00.000000Z to 2026-05-19T17:51:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 109: 2026-05-19T17:51:00.000000Z to 2026-05-19T17:52:00.000000Z
  read 35 traces, 35 stations
  detections: 15
T3_N4_Refraction1am chunk 110: 2026-05-19T17:52:00.000000Z to 2026-05-19T17:53:00.000000Z
  read 35 traces, 35 stations
  detections: 4
T3_N4_Refraction1am chunk 111: 2026-05-19T17:53:00.000000Z to 2026-05-19T17:54:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 112: 2026-05-19T17:54:00.000000Z to 2026-05-19T17:55:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 113: 2026-05-19T17:55:00.000000Z to 2026-05-19T17:56:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 114: 2026-05-19T17:56:00.000000Z to 2026-05-19T17:57:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 115: 2026-05-19T17:57:00.000000Z to 2026-05-19T17:58:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 116: 2026-05-19T17:58:00.000000Z to 2026-05-19T17:59:00.000000Z
  read 35 traces, 35 stations
  detections: 5
T3_N4_Refraction1am chunk 117: 2026-05-19T17:59:00.000000Z to 2026-05-19T18:00:00.000000Z
  read 35 traces, 35 stations
  detections: 18
T3_N4_Refraction1am chunk 118: 2026-05-19T18:00:00.000000Z to 2026-05-19T18:01:00.000000Z
  read 35 traces, 35 stations
  detections: 8
T3_N4_Refraction1am chunk 119: 2026-05-19T18:01:00.000000Z to 2026-05-19T18:02:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 120: 2026-05-19T18:02:00.000000Z to 2026-05-19T18:03:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 121: 2026-05-19T18:03:00.000000Z to 2026-05-19T18:04:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 122: 2026-05-19T18:04:00.000000Z to 2026-05-19T18:05:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 123: 2026-05-19T18:05:00.000000Z to 2026-05-19T18:06:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 124: 2026-05-19T18:06:00.000000Z to 2026-05-19T18:07:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 125: 2026-05-19T18:07:00.000000Z to 2026-05-19T18:08:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 126: 2026-05-19T18:08:00.000000Z to 2026-05-19T18:09:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 127: 2026-05-19T18:09:00.000000Z to 2026-05-19T18:10:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 128: 2026-05-19T18:10:00.000000Z to 2026-05-19T18:11:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 129: 2026-05-19T18:11:00.000000Z to 2026-05-19T18:12:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 130: 2026-05-19T18:12:00.000000Z to 2026-05-19T18:13:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 131: 2026-05-19T18:13:00.000000Z to 2026-05-19T18:14:00.000000Z
  read 35 traces, 35 stations
  detections: 3
T3_N4_Refraction1am chunk 132: 2026-05-19T18:14:00.000000Z to 2026-05-19T18:15:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 133: 2026-05-19T18:15:00.000000Z to 2026-05-19T18:16:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 134: 2026-05-19T18:16:00.000000Z to 2026-05-19T18:17:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 135: 2026-05-19T18:17:00.000000Z to 2026-05-19T18:18:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 136: 2026-05-19T18:18:00.000000Z to 2026-05-19T18:19:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 137: 2026-05-19T18:19:00.000000Z to 2026-05-19T18:20:00.000000Z
  read 35 traces, 35 stations
  detections: 2
T3_N4_Refraction1am chunk 138: 2026-05-19T18:20:00.000000Z to 2026-05-19T18:21:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 139: 2026-05-19T18:21:00.000000Z to 2026-05-19T18:22:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 140: 2026-05-19T18:22:00.000000Z to 2026-05-19T18:23:00.000000Z
  read 35 traces, 35 stations
  detections: 1
T3_N4_Refraction1am chunk 141: 2026-05-19T18:23:00.000000Z to 2026-05-19T18:24:00.000000Z
  read 35 traces, 35 stations
T3_N4_Refraction1am chunk 142: 2026-05-19T18:24:00.000000Z to 2026-05-19T18:25:00.000000Z
  read 35 traces, 35 stations
Raw detections: 611; merged detections: 523

T3_N4_Refraction1am_T3_N4_E00001: on_time=2026-05-19 16:02:33.030000
  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00002: on_time=2026-05-19 16:02:43.822157

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00003: on_time=2026-05-19 16:02:45.564148

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00004: on_time=2026-05-19 16:02:52.692159

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00005: on_time=2026-05-19 16:03:02.040000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00006: on_time=2026-05-19 16:03:05.060000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00007: on_time=2026-05-19 16:03:19.344000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00008: on_time=2026-05-19 16:03:40.748121

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00009: on_time=2026-05-19 16:03:54.934000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00010: on_time=2026-05-19 16:04:06.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00011: on_time=2026-05-19 16:04:22.786000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00012: on_time=2026-05-19 16:04:23.090154

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00013: on_time=2026-05-19 16:04:35.124000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00014: on_time=2026-05-19 16:04:35.384152

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00015: on_time=2026-05-19 16:04:45.866000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00016: on_time=2026-05-19 16:05:10.286000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00017: on_time=2026-05-19 16:05:10.490157

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00018: on_time=2026-05-19 16:06:05.522000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00019: on_time=2026-05-19 16:07:07.866000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00020: on_time=2026-05-19 16:07:22.454177

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00021: on_time=2026-05-19 16:07:23.830176

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00022: on_time=2026-05-19 16:08:04.278000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00023: on_time=2026-05-19 16:08:58.300000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00024: on_time=2026-05-19 16:09:08.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00025: on_time=2026-05-19 16:09:17.156000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00026: on_time=2026-05-19 16:09:26.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00027: on_time=2026-05-19 16:09:35.128142

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00028: on_time=2026-05-19 16:09:44.224000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00029: on_time=2026-05-19 16:09:53.328143

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00030: on_time=2026-05-19 16:09:53.548000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00031: on_time=2026-05-19 16:10:33.854000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00032: on_time=2026-05-19 16:12:28.890000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00033: on_time=2026-05-19 16:12:35.248195

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00034: on_time=2026-05-19 16:12:45.028000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00035: on_time=2026-05-19 16:12:45.288168

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00036: on_time=2026-05-19 16:12:57.212000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00037: on_time=2026-05-19 16:13:04.534000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00038: on_time=2026-05-19 16:13:04.826185

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00039: on_time=2026-05-19 16:13:14.970000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00040: on_time=2026-05-19 16:13:24.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00041: on_time=2026-05-19 16:13:24.868157

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00042: on_time=2026-05-19 16:13:34.360000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00043: on_time=2026-05-19 16:14:32.058161

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00044: on_time=2026-05-19 16:15:37.562000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00045: on_time=2026-05-19 16:16:09.094167

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00046: on_time=2026-05-19 16:16:17.340167

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00047: on_time=2026-05-19 16:16:25.310204

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00048: on_time=2026-05-19 16:16:25.552200

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00049: on_time=2026-05-19 16:16:33.232168

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00050: on_time=2026-05-19 16:16:33.656198

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00051: on_time=2026-05-19 16:16:41.250169

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00052: on_time=2026-05-19 16:16:41.600000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00053: on_time=2026-05-19 16:16:49.040169

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00054: on_time=2026-05-19 16:16:57.536170

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00055: on_time=2026-05-19 16:16:57.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00056: on_time=2026-05-19 16:17:14.052171

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00057: on_time=2026-05-19 16:18:56.572177

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00058: on_time=2026-05-19 16:19:06.476178

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00059: on_time=2026-05-19 16:19:15.956178

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00060: on_time=2026-05-19 16:19:16.340201

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00061: on_time=2026-05-19 16:19:25.052179

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00062: on_time=2026-05-19 16:19:32.980179

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00063: on_time=2026-05-19 16:19:42.296180

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00064: on_time=2026-05-19 16:19:52.732180

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00065: on_time=2026-05-19 16:21:28.218223

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00066: on_time=2026-05-19 16:21:28.520214

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00067: on_time=2026-05-19 16:21:37.586228

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00068: on_time=2026-05-19 16:21:46.896000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00069: on_time=2026-05-19 16:21:56.300000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00070: on_time=2026-05-19 16:22:05.612000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00071: on_time=2026-05-19 16:22:14.916189

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00072: on_time=2026-05-19 16:22:26.718000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00073: on_time=2026-05-19 16:22:44.344000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00074: on_time=2026-05-19 16:22:47.036229

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00075: on_time=2026-05-19 16:22:57.574230

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00076: on_time=2026-05-19 16:24:31.046235

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00077: on_time=2026-05-19 16:24:39.448236

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00078: on_time=2026-05-19 16:24:58.276000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00079: on_time=2026-05-19 16:25:10.162238

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00080: on_time=2026-05-19 16:25:55.394241

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00081: on_time=2026-05-19 16:26:04.302241

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00082: on_time=2026-05-19 16:26:12.758241

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00083: on_time=2026-05-19 16:26:21.418242

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00084: on_time=2026-05-19 16:26:29.750242

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00085: on_time=2026-05-19 16:26:47.154000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00086: on_time=2026-05-19 16:26:47.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00087: on_time=2026-05-19 16:28:24.860000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00088: on_time=2026-05-19 16:28:34.138000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00089: on_time=2026-05-19 16:28:42.664000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00090: on_time=2026-05-19 16:28:51.290000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00091: on_time=2026-05-19 16:28:59.512252

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00092: on_time=2026-05-19 16:29:08.156000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00093: on_time=2026-05-19 16:29:15.758252

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00094: on_time=2026-05-19 16:29:28.630255

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00095: on_time=2026-05-19 16:29:42.678000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00096: on_time=2026-05-19 16:30:22.100000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00097: on_time=2026-05-19 16:30:22.562262

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00098: on_time=2026-05-19 16:30:31.502256

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00099: on_time=2026-05-19 16:30:40.520000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00100: on_time=2026-05-19 16:30:49.868000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00101: on_time=2026-05-19 16:30:59.148000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00102: on_time=2026-05-19 16:31:08.624000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00103: on_time=2026-05-19 16:31:08.832243

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00104: on_time=2026-05-19 16:31:17.918000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00105: on_time=2026-05-19 16:32:27.906266

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00106: on_time=2026-05-19 16:32:37.862000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00107: on_time=2026-05-19 16:32:45.884000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00108: on_time=2026-05-19 16:32:53.730267

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00109: on_time=2026-05-19 16:33:01.700268

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00110: on_time=2026-05-19 16:33:09.562000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00111: on_time=2026-05-19 16:33:17.736000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00112: on_time=2026-05-19 16:34:33.944275

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00113: on_time=2026-05-19 16:34:43.220276

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00114: on_time=2026-05-19 16:34:52.106276

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00115: on_time=2026-05-19 16:35:01.022277

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00116: on_time=2026-05-19 16:35:09.840278

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00117: on_time=2026-05-19 16:35:18.750273

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00118: on_time=2026-05-19 16:35:27.734000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00119: on_time=2026-05-19 16:35:59.228000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00120: on_time=2026-05-19 16:36:10.918282

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00121: on_time=2026-05-19 16:36:38.194284

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00122: on_time=2026-05-19 16:36:46.962286

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00123: on_time=2026-05-19 16:36:55.418287

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00124: on_time=2026-05-19 16:37:03.512284

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00125: on_time=2026-05-19 16:37:11.702286

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00126: on_time=2026-05-19 16:37:19.808286

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00127: on_time=2026-05-19 16:37:28.078287

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00128: on_time=2026-05-19 16:38:13.570000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00129: on_time=2026-05-19 16:38:21.476291

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00130: on_time=2026-05-19 16:38:22.958000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00131: on_time=2026-05-19 16:38:23.940291

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00132: on_time=2026-05-19 16:38:55.378292

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00133: on_time=2026-05-19 16:39:04.888000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00134: on_time=2026-05-19 16:39:13.024000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00135: on_time=2026-05-19 16:39:21.170000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00136: on_time=2026-05-19 16:39:30.080295

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00137: on_time=2026-05-19 16:39:38.310000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00138: on_time=2026-05-19 16:39:46.682296

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00139: on_time=2026-05-19 16:40:10.004000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00140: on_time=2026-05-19 16:40:18.642000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00141: on_time=2026-05-19 16:40:23.712000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00142: on_time=2026-05-19 16:40:48.558300

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00143: on_time=2026-05-19 16:41:22.038000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00144: on_time=2026-05-19 16:41:30.438000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00145: on_time=2026-05-19 16:41:39.094000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00146: on_time=2026-05-19 16:41:47.444303

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00147: on_time=2026-05-19 16:41:55.946000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00148: on_time=2026-05-19 16:42:04.376304

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00149: on_time=2026-05-19 16:42:12.808000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00150: on_time=2026-05-19 16:42:25.440000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00151: on_time=2026-05-19 16:43:20.218000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00152: on_time=2026-05-19 16:43:28.394294

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00153: on_time=2026-05-19 16:43:36.536297

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00154: on_time=2026-05-19 16:43:44.548000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00155: on_time=2026-05-19 16:43:52.906000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00156: on_time=2026-05-19 16:44:00.892000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00157: on_time=2026-05-19 16:44:08.992313

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00158: on_time=2026-05-19 16:44:09.270299

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00159: on_time=2026-05-19 16:44:17.042301

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00160: on_time=2026-05-19 16:44:17.484290

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00161: on_time=2026-05-19 16:44:39.246317

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00162: on_time=2026-05-19 16:44:45.732000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00163: on_time=2026-05-19 16:44:50.730314

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00164: on_time=2026-05-19 16:44:51.390317

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00165: on_time=2026-05-19 16:44:52.010317

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00166: on_time=2026-05-19 16:44:52.758000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00167: on_time=2026-05-19 16:44:53.536317

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00168: on_time=2026-05-19 16:44:55.988000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00169: on_time=2026-05-19 16:45:51.524321

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00170: on_time=2026-05-19 16:46:03.406000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00171: on_time=2026-05-19 16:46:15.672322

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00172: on_time=2026-05-19 16:46:25.820299

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00173: on_time=2026-05-19 16:46:35.728000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00174: on_time=2026-05-19 16:46:44.956000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00175: on_time=2026-05-19 16:46:55.114324

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00176: on_time=2026-05-19 16:47:09.668324

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00177: on_time=2026-05-19 16:47:12.274326

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00178: on_time=2026-05-19 16:47:19.716000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00179: on_time=2026-05-19 16:47:23.360000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00180: on_time=2026-05-19 16:47:25.674327

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00181: on_time=2026-05-19 16:47:26.480000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00182: on_time=2026-05-19 16:47:27.322000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00183: on_time=2026-05-19 16:47:32.892000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00184: on_time=2026-05-19 16:47:34.236000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00185: on_time=2026-05-19 16:47:56.806329

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00186: on_time=2026-05-19 16:48:11.302330

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00187: on_time=2026-05-19 16:48:19.846000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00188: on_time=2026-05-19 16:48:28.064000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00189: on_time=2026-05-19 16:48:36.340000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00190: on_time=2026-05-19 16:48:44.620000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00191: on_time=2026-05-19 16:48:52.594000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00192: on_time=2026-05-19 16:49:00.876000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00193: on_time=2026-05-19 16:49:18.384333

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00194: on_time=2026-05-19 16:49:21.030000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00195: on_time=2026-05-19 16:49:23.556000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00196: on_time=2026-05-19 16:49:24.274000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00197: on_time=2026-05-19 16:49:24.916000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00198: on_time=2026-05-19 16:49:25.482000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00199: on_time=2026-05-19 16:49:26.026000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00200: on_time=2026-05-19 16:49:26.610000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00201: on_time=2026-05-19 16:49:28.088000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00202: on_time=2026-05-19 16:49:28.862000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00203: on_time=2026-05-19 16:49:29.886332

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00204: on_time=2026-05-19 16:49:32.086000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00205: on_time=2026-05-19 16:50:01.474000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00206: on_time=2026-05-19 16:50:10.560000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00207: on_time=2026-05-19 16:50:20.220000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00208: on_time=2026-05-19 16:50:29.286000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00209: on_time=2026-05-19 16:50:38.334000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00210: on_time=2026-05-19 16:50:47.922000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00211: on_time=2026-05-19 16:50:57.806000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00212: on_time=2026-05-19 16:51:12.362000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00213: on_time=2026-05-19 16:51:16.472000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00214: on_time=2026-05-19 16:51:18.134000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00215: on_time=2026-05-19 16:51:18.868000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00216: on_time=2026-05-19 16:51:19.672000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00217: on_time=2026-05-19 16:51:20.456000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00218: on_time=2026-05-19 16:51:21.134000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00219: on_time=2026-05-19 16:51:21.838000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00220: on_time=2026-05-19 16:51:22.630000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00221: on_time=2026-05-19 16:51:23.648000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00222: on_time=2026-05-19 16:51:28.658000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00223: on_time=2026-05-19 16:51:37.896000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00224: on_time=2026-05-19 16:51:39.224329

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00225: on_time=2026-05-19 16:52:02.584000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00226: on_time=2026-05-19 16:52:02.788000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00227: on_time=2026-05-19 16:52:10.892298

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00228: on_time=2026-05-19 16:52:19.690331

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00229: on_time=2026-05-19 16:52:28.032333

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00230: on_time=2026-05-19 16:52:36.342000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00231: on_time=2026-05-19 16:52:44.552000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00232: on_time=2026-05-19 16:52:53.496334

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00233: on_time=2026-05-19 16:53:18.654000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00234: on_time=2026-05-19 16:54:18.468339

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00235: on_time=2026-05-19 16:54:20.832339

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00236: on_time=2026-05-19 16:54:21.522340

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00237: on_time=2026-05-19 16:54:22.750340

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00238: on_time=2026-05-19 16:54:29.382340

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00239: on_time=2026-05-19 16:55:03.560342

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00240: on_time=2026-05-19 16:55:20.526343

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00241: on_time=2026-05-19 16:55:30.780343

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00242: on_time=2026-05-19 16:55:41.284345

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00243: on_time=2026-05-19 16:55:51.440344

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00244: on_time=2026-05-19 16:56:01.460343

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00245: on_time=2026-05-19 16:56:12.854346

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00246: on_time=2026-05-19 16:56:58.728349

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00247: on_time=2026-05-19 16:57:23.892342

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00248: on_time=2026-05-19 16:57:35.874350

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00249: on_time=2026-05-19 16:57:45.050000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00250: on_time=2026-05-19 16:57:53.822352

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00251: on_time=2026-05-19 16:58:03.076353

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00252: on_time=2026-05-19 16:58:12.814353

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00253: on_time=2026-05-19 16:58:21.958354

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00254: on_time=2026-05-19 16:58:48.150000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00255: on_time=2026-05-19 16:58:51.682000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00256: on_time=2026-05-19 16:59:30.972357

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00257: on_time=2026-05-19 16:59:31.180325

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00258: on_time=2026-05-19 16:59:39.836358

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00259: on_time=2026-05-19 16:59:48.452000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00260: on_time=2026-05-19 16:59:57.564359

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00261: on_time=2026-05-19 17:00:06.186360

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00262: on_time=2026-05-19 17:00:15.920000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00263: on_time=2026-05-19 17:00:25.132329

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00264: on_time=2026-05-19 17:00:50.282361

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00265: on_time=2026-05-19 17:00:54.134000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00266: on_time=2026-05-19 17:01:26.516000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00267: on_time=2026-05-19 17:01:49.310000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00268: on_time=2026-05-19 17:02:34.516380

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00269: on_time=2026-05-19 17:02:41.314000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00270: on_time=2026-05-19 17:03:39.430374

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00271: on_time=2026-05-19 17:04:15.650000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00272: on_time=2026-05-19 17:04:23.786374

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00273: on_time=2026-05-19 17:04:30.762000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00274: on_time=2026-05-19 17:04:32.108380

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00275: on_time=2026-05-19 17:04:34.778389

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00276: on_time=2026-05-19 17:04:39.496000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00277: on_time=2026-05-19 17:04:40.212000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00278: on_time=2026-05-19 17:04:43.132387

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00279: on_time=2026-05-19 17:04:48.872375

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00280: on_time=2026-05-19 17:04:52.372000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00281: on_time=2026-05-19 17:04:57.256376

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00282: on_time=2026-05-19 17:05:06.008000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00283: on_time=2026-05-19 17:06:20.382381

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00284: on_time=2026-05-19 17:06:29.262382

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00285: on_time=2026-05-19 17:06:37.624382

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00286: on_time=2026-05-19 17:06:45.958383

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00287: on_time=2026-05-19 17:06:54.366384

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00288: on_time=2026-05-19 17:07:02.288383

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00289: on_time=2026-05-19 17:07:11.400384

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00290: on_time=2026-05-19 17:07:24.824387

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00291: on_time=2026-05-19 17:07:29.374000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00292: on_time=2026-05-19 17:08:16.246000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00293: on_time=2026-05-19 17:08:26.040396

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00294: on_time=2026-05-19 17:08:36.028000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00295: on_time=2026-05-19 17:08:46.494390

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00296: on_time=2026-05-19 17:08:57.234391

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00297: on_time=2026-05-19 17:09:06.976392

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00298: on_time=2026-05-19 17:09:17.186392

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00299: on_time=2026-05-19 17:09:54.784000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00300: on_time=2026-05-19 17:09:58.214394

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00301: on_time=2026-05-19 17:10:54.676000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00302: on_time=2026-05-19 17:10:58.062000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00303: on_time=2026-05-19 17:11:09.924000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00304: on_time=2026-05-19 17:11:19.162392

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00305: on_time=2026-05-19 17:11:28.662399

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00306: on_time=2026-05-19 17:11:38.132400

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00307: on_time=2026-05-19 17:11:47.602400

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00308: on_time=2026-05-19 17:11:57.532000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00309: on_time=2026-05-19 17:12:17.608000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00310: on_time=2026-05-19 17:12:42.888374

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00311: on_time=2026-05-19 17:12:48.532404

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00312: on_time=2026-05-19 17:13:42.480410

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00313: on_time=2026-05-19 17:13:52.926406

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00314: on_time=2026-05-19 17:14:02.352407

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00315: on_time=2026-05-19 17:14:12.158408

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00316: on_time=2026-05-19 17:14:21.320409

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00317: on_time=2026-05-19 17:14:30.180000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00318: on_time=2026-05-19 17:14:41.324410

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00319: on_time=2026-05-19 17:14:54.898410

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00320: on_time=2026-05-19 17:16:10.666417

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00321: on_time=2026-05-19 17:16:37.160415

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00322: on_time=2026-05-19 17:16:47.350416

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00323: on_time=2026-05-19 17:16:57.650418

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00324: on_time=2026-05-19 17:17:08.068418

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00325: on_time=2026-05-19 17:17:18.170418

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00326: on_time=2026-05-19 17:17:28.662419

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00327: on_time=2026-05-19 17:17:38.642419

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00328: on_time=2026-05-19 17:18:00.838000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00329: on_time=2026-05-19 17:18:02.666000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00330: on_time=2026-05-19 17:18:14.450000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00331: on_time=2026-05-19 17:18:15.280000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00332: on_time=2026-05-19 17:18:16.206000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00333: on_time=2026-05-19 17:18:22.976425

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00334: on_time=2026-05-19 17:18:23.638000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00335: on_time=2026-05-19 17:18:25.828000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00336: on_time=2026-05-19 17:18:34.994422

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00337: on_time=2026-05-19 17:18:46.988426

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00338: on_time=2026-05-19 17:19:00.086420

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00339: on_time=2026-05-19 17:19:10.548430

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00340: on_time=2026-05-19 17:19:23.782426

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00341: on_time=2026-05-19 17:19:34.358426

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00342: on_time=2026-05-19 17:19:45.272432

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00343: on_time=2026-05-19 17:19:57.044428

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00344: on_time=2026-05-19 17:20:08.204429

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00345: on_time=2026-05-19 17:21:22.120000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00346: on_time=2026-05-19 17:21:33.880427

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00347: on_time=2026-05-19 17:21:45.610430

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00348: on_time=2026-05-19 17:21:57.204000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00349: on_time=2026-05-19 17:22:09.388000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00350: on_time=2026-05-19 17:22:20.770436

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00351: on_time=2026-05-19 17:22:33.338000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00352: on_time=2026-05-19 17:23:14.806000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00353: on_time=2026-05-19 17:23:17.584436

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00354: on_time=2026-05-19 17:23:19.464436

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00355: on_time=2026-05-19 17:23:20.262436

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00356: on_time=2026-05-19 17:23:21.128436

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00357: on_time=2026-05-19 17:23:28.358437

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00358: on_time=2026-05-19 17:23:42.188444

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00359: on_time=2026-05-19 17:24:11.328437

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00360: on_time=2026-05-19 17:24:25.812438

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00361: on_time=2026-05-19 17:24:35.068438

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00362: on_time=2026-05-19 17:24:35.594000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00363: on_time=2026-05-19 17:24:45.574000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00364: on_time=2026-05-19 17:24:46.088418

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00365: on_time=2026-05-19 17:24:50.588448

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00366: on_time=2026-05-19 17:24:56.126440

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00367: on_time=2026-05-19 17:25:06.074440

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00368: on_time=2026-05-19 17:25:16.398443

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00369: on_time=2026-05-19 17:25:52.598443

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00370: on_time=2026-05-19 17:26:00.720443

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00371: on_time=2026-05-19 17:26:03.988443

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00372: on_time=2026-05-19 17:26:04.850442

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00373: on_time=2026-05-19 17:26:05.738444

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00374: on_time=2026-05-19 17:27:35.732000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00375: on_time=2026-05-19 17:27:59.868451

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00376: on_time=2026-05-19 17:28:18.634430

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00377: on_time=2026-05-19 17:28:30.512452

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00378: on_time=2026-05-19 17:28:42.702460

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00379: on_time=2026-05-19 17:28:57.206455

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00380: on_time=2026-05-19 17:29:08.612465

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00381: on_time=2026-05-19 17:29:19.966000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00382: on_time=2026-05-19 17:29:34.832000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00383: on_time=2026-05-19 17:29:37.434000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00384: on_time=2026-05-19 17:29:39.188000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00385: on_time=2026-05-19 17:29:39.938000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00386: on_time=2026-05-19 17:29:43.204456

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00387: on_time=2026-05-19 17:30:33.838459

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00388: on_time=2026-05-19 17:30:46.332460

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00389: on_time=2026-05-19 17:31:13.012473

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00390: on_time=2026-05-19 17:31:21.118000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00391: on_time=2026-05-19 17:31:58.666465

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00392: on_time=2026-05-19 17:32:26.010000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00393: on_time=2026-05-19 17:33:40.942000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00394: on_time=2026-05-19 17:33:42.024496

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00395: on_time=2026-05-19 17:33:43.074000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00396: on_time=2026-05-19 17:34:15.202469

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00397: on_time=2026-05-19 17:34:26.104000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00398: on_time=2026-05-19 17:34:38.294470

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00399: on_time=2026-05-19 17:34:49.366468

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00400: on_time=2026-05-19 17:35:22.714473

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00401: on_time=2026-05-19 17:35:24.496473

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00402: on_time=2026-05-19 17:35:34.838000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00403: on_time=2026-05-19 17:35:35.484473

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00404: on_time=2026-05-19 17:35:37.606473

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00405: on_time=2026-05-19 17:35:39.946000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00406: on_time=2026-05-19 17:35:44.130000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00407: on_time=2026-05-19 17:35:46.776000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00408: on_time=2026-05-19 17:36:12.754000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00409: on_time=2026-05-19 17:36:24.450000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00410: on_time=2026-05-19 17:36:30.382489

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00411: on_time=2026-05-19 17:36:34.464474

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00412: on_time=2026-05-19 17:36:44.550495

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00413: on_time=2026-05-19 17:36:54.744000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00414: on_time=2026-05-19 17:37:04.404478

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00415: on_time=2026-05-19 17:37:15.086484

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00416: on_time=2026-05-19 17:37:24.900000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00417: on_time=2026-05-19 17:37:49.514486

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00418: on_time=2026-05-19 17:37:50.884481

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00419: on_time=2026-05-19 17:37:53.344482

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00420: on_time=2026-05-19 17:37:54.514482

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00421: on_time=2026-05-19 17:37:55.314482

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00422: on_time=2026-05-19 17:37:57.138482

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00423: on_time=2026-05-19 17:37:58.274483

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00424: on_time=2026-05-19 17:38:01.948482

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00425: on_time=2026-05-19 17:38:05.818482

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00426: on_time=2026-05-19 17:38:55.590484

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00427: on_time=2026-05-19 17:39:05.724490

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00428: on_time=2026-05-19 17:39:15.816487

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00429: on_time=2026-05-19 17:39:25.142488

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00430: on_time=2026-05-19 17:39:34.800488

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00431: on_time=2026-05-19 17:39:45.236489

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00432: on_time=2026-05-19 17:39:55.370490

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00433: on_time=2026-05-19 17:40:05.884490

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00434: on_time=2026-05-19 17:40:29.564491

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00435: on_time=2026-05-19 17:40:32.602491

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00436: on_time=2026-05-19 17:40:33.754489

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00437: on_time=2026-05-19 17:40:40.668490

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00438: on_time=2026-05-19 17:40:43.164492

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00439: on_time=2026-05-19 17:40:47.114492

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00440: on_time=2026-05-19 17:41:16.162491

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00441: on_time=2026-05-19 17:41:26.032479

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00442: on_time=2026-05-19 17:41:35.832495

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00443: on_time=2026-05-19 17:41:45.884495

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00444: on_time=2026-05-19 17:41:55.560496

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00445: on_time=2026-05-19 17:42:05.160497

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00446: on_time=2026-05-19 17:42:24.810524

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00447: on_time=2026-05-19 17:42:34.242499

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00448: on_time=2026-05-19 17:43:03.800500

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00449: on_time=2026-05-19 17:43:17.276516

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00450: on_time=2026-05-19 17:43:31.436508

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00451: on_time=2026-05-19 17:44:11.752502

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00452: on_time=2026-05-19 17:44:14.894502

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00453: on_time=2026-05-19 17:44:22.204505

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00454: on_time=2026-05-19 17:44:58.904505

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00455: on_time=2026-05-19 17:45:11.128506

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00456: on_time=2026-05-19 17:45:24.116000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00457: on_time=2026-05-19 17:45:36.156507

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00458: on_time=2026-05-19 17:45:47.444508

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00459: on_time=2026-05-19 17:45:59.804509

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00460: on_time=2026-05-19 17:46:11.460513

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00461: on_time=2026-05-19 17:46:24.686511

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00462: on_time=2026-05-19 17:46:31.758511

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00463: on_time=2026-05-19 17:46:49.142512

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00464: on_time=2026-05-19 17:46:53.408513

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00465: on_time=2026-05-19 17:46:56.378513

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00466: on_time=2026-05-19 17:48:30.320518

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00467: on_time=2026-05-19 17:48:43.292519

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00468: on_time=2026-05-19 17:48:55.706520

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00469: on_time=2026-05-19 17:49:06.362521

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00470: on_time=2026-05-19 17:49:18.636521

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00471: on_time=2026-05-19 17:49:29.268522

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00472: on_time=2026-05-19 17:49:40.130523

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00473: on_time=2026-05-19 17:50:17.214524

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00474: on_time=2026-05-19 17:50:20.372525

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00475: on_time=2026-05-19 17:50:23.226525

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00476: on_time=2026-05-19 17:50:30.110525

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00477: on_time=2026-05-19 17:51:14.386536

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00478: on_time=2026-05-19 17:51:14.678557

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00479: on_time=2026-05-19 17:51:25.760537

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00480: on_time=2026-05-19 17:51:36.362529

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00481: on_time=2026-05-19 17:51:48.194530

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00482: on_time=2026-05-19 17:51:48.654558

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00483: on_time=2026-05-19 17:51:58.678531

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00484: on_time=2026-05-19 17:51:59.070000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00485: on_time=2026-05-19 17:52:11.284534

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00486: on_time=2026-05-19 17:52:11.604562

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00487: on_time=2026-05-19 17:52:23.434533

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00488: on_time=2026-05-19 17:52:23.742000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00489: on_time=2026-05-19 17:55:23.968574

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00490: on_time=2026-05-19 17:55:50.638575

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00491: on_time=2026-05-19 17:56:54.172556

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00492: on_time=2026-05-19 17:57:15.492550

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00493: on_time=2026-05-19 17:58:07.966000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00494: on_time=2026-05-19 17:58:24.664555

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00495: on_time=2026-05-19 17:58:30.934573

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00496: on_time=2026-05-19 17:59:11.240565

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00497: on_time=2026-05-19 17:59:28.326558

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00498: on_time=2026-05-19 17:59:44.966588

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00499: on_time=2026-05-19 17:59:47.260000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00500: on_time=2026-05-19 18:00:05.240560

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00501: on_time=2026-05-19 18:00:16.152000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00502: on_time=2026-05-19 18:00:16.590561

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00503: on_time=2026-05-19 18:00:28.028562

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00504: on_time=2026-05-19 18:02:17.764586

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00505: on_time=2026-05-19 18:06:04.406000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00506: on_time=2026-05-19 18:07:10.422616

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00507: on_time=2026-05-19 18:07:12.578000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00508: on_time=2026-05-19 18:09:38.816613

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00509: on_time=2026-05-19 18:10:12.578613

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00510: on_time=2026-05-19 18:10:50.576000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00511: on_time=2026-05-19 18:11:00.050618

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00512: on_time=2026-05-19 18:11:26.604631

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00513: on_time=2026-05-19 18:12:14.620628

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00514: on_time=2026-05-19 18:13:05.390627

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00515: on_time=2026-05-19 18:13:42.412627

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00516: on_time=2026-05-19 18:14:06.264632

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00517: on_time=2026-05-19 18:16:57.586640

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00518: on_time=2026-05-19 18:17:29.348643

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00519: on_time=2026-05-19 18:17:55.996652

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00520: on_time=2026-05-19 18:19:03.464000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00521: on_time=2026-05-19 18:19:20.266661

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00522: on_time=2026-05-19 18:20:46.824656

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers

T3_N4_Refraction1am_T3_N4_E00523: on_time=2026-05-19 18:22:04.542000

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

  extracted 105 traces, 35 receivers
Done. Catalog: /Volumes/tachyon/LBSSP_DATA/catalog/lbssp_shot_catalog.sqlite

/opt/anaconda3/envs/flovopy_plus/lib/python3.12/site-packages/obspy/io/mseed/core.py:824: UserWarning: File will be written with more than one different encodings.
This might have a negative influence on the compatibility with other programs.
  warnings.warn(msg % 'encodings')

## 9. Catalog inspection

Use SQL queries to inspect what was produced.

In [9]:
def q(sql: str, params=None):
    return pd.read_sql(sql, conn, params=params or {})

print("processing_runs")
display(q("SELECT run_id, notebook_name, run_time_utc, input_sds_root, output_root FROM processing_runs ORDER BY run_time_utc DESC LIMIT 5"))

print("shot_events summary")
display(q("""
SELECT timewindow_label, status, COUNT(*) AS n_events,
       AVG(n_receivers_extracted) AS avg_receivers,
       MIN(n_receivers_extracted) AS min_receivers,
       MAX(n_receivers_extracted) AS max_receivers
FROM shot_events
WHERE run_id = :run_id
GROUP BY timewindow_label, status
ORDER BY timewindow_label, status
""", {"run_id": RUN_ID}))

print("files summary")
display(q("""
SELECT timewindow_label, file_type, component, COUNT(*) AS n_files
FROM shot_gather_files
WHERE run_id = :run_id
GROUP BY timewindow_label, file_type, component
ORDER BY timewindow_label, file_type, component
""", {"run_id": RUN_ID}))

print("pick summary")
display(q("""
SELECT timewindow_label, picker, pick_quality, COUNT(*) AS n
FROM picks p
JOIN shot_events e USING(event_id)
WHERE p.run_id = :run_id
GROUP BY timewindow_label, picker, pick_quality
ORDER BY timewindow_label, picker, pick_quality
""", {"run_id": RUN_ID}))

processing_runs

,run_id,notebook_name,run_time_utc,input_sds_root,output_root
0,20260617T230552Z_da97ed5d,90_nodal_fullnode_detection_pick_and_shotgathe...,2026-06-17T23:05:52.363740+00:00,/Volumes/tachyon/LBSSP_DATA/nodal_sds_position...,/Volumes/tachyon/LBSSP_DATA/nodal_fullnode_sho...

shot_events summary

,timewindow_label,status,n_events,avg_receivers,min_receivers,max_receivers
0,T1_N1_Streamer,ok,532,30.308271,15,35
1,T1_N2_Nodal1,ok,1376,32.166424,26,35
2,T1_N2_Nodal2,ok,81,34.000000,34,34
3,T1_N2_Refraction1m,ok,431,34.000000,34,34
4,T1_N2_Refraction2m,ok,450,34.000000,34,34
5,T1_N3_Nodal3,ok,43,34.000000,34,34
6,T3_N4_Refraction1am,ok,523,35.000000,35,35

files summary

      timewindow_label file_type component  n_files
0       T1_N1_Streamer     mseed        3C      532
1         T1_N2_Nodal1     mseed        3C     1376
2         T1_N2_Nodal2     mseed        3C       81
3   T1_N2_Refraction1m     mseed        3C      431
4   T1_N2_Refraction2m     mseed        3C      450
5         T1_N3_Nodal3     mseed        3C       43
6  T3_N4_Refraction1am     mseed        3C      523

pick summary

       timewindow_label     picker pick_quality       n
0        T1_N1_Streamer        aic    candidate   48372
1        T1_N1_Streamer       baer    candidate   48372
2        T1_N1_Streamer  consensus    consensus   12755
3        T1_N1_Streamer  consensus       failed    3369
4          T1_N2_Nodal1        aic    candidate  132783
5          T1_N2_Nodal1       baer    candidate  132783
6          T1_N2_Nodal1  consensus    consensus   28727
7          T1_N2_Nodal1  consensus       failed   15534
8          T1_N2_Nodal2        aic    candidate    8262
9          T1_N2_Nodal2       baer    candidate    8262
10         T1_N2_Nodal2  consensus    consensus    1493
11         T1_N2_Nodal2  consensus       failed    1261
12   T1_N2_Refraction1m        aic    candidate   43962
13   T1_N2_Refraction1m       baer    candidate   43962
14   T1_N2_Refraction1m  consensus    consensus   11733
15   T1_N2_Refraction1m  consensus       failed    2921
16   T1_N2_Refraction2m        aic    candidate   45900
17   T1_N2_Refraction2m       baer    candidate   45900
18   T1_N2_Refraction2m  consensus    consensus   11459
19   T1_N2_Refraction2m  consensus       failed    3841
20         T1_N3_Nodal3        aic    candidate    4386
21         T1_N3_Nodal3       baer    candidate    4386
22         T1_N3_Nodal3  consensus    consensus     763
23         T1_N3_Nodal3  consensus       failed     699
24  T3_N4_Refraction1am        aic    candidate   54915
25  T3_N4_Refraction1am       baer    candidate   54915
26  T3_N4_Refraction1am  consensus    consensus   14248
27  T3_N4_Refraction1am  consensus       failed    4057

## 10. Optional CSV exports

SQLite is the source of truth, but these CSV snapshots are convenient for inspection, sharing, and debugging.

In [10]:
if EXPORT_CSV_SNAPSHOTS:
    tables = [
        "processing_runs",
        "receiver_geometry",
        "shot_events",
        "shot_gather_files",
        "trace_index",
        "picks",
        "processing_errors",
    ]
    for table in tables:
        df = pd.read_sql(f"SELECT * FROM {table} WHERE run_id = ?" if table != "processing_runs" else "SELECT * FROM processing_runs WHERE run_id = ?", conn, params=(RUN_ID,))
        out = CSV_EXPORT_DIR / f"{RUN_ID}_{table}.csv"
        df.to_csv(out, index=False)
        print(table, len(df), "->", out)

processing_runs 1 -> /Volumes/tachyon/LBSSP_DATA/nodal_fullnode_shotgathers_v4/catalog_exports/20260617T230552Z_da97ed5d_processing_runs.csv
receiver_geometry 245 -> /Volumes/tachyon/LBSSP_DATA/nodal_fullnode_shotgathers_v4/catalog_exports/20260617T230552Z_da97ed5d_receiver_geometry.csv
shot_events 3436 -> /Volumes/tachyon/LBSSP_DATA/nodal_fullnode_shotgathers_v4/catalog_exports/20260617T230552Z_da97ed5d_shot_events.csv
shot_gather_files 3436 -> /Volumes/tachyon/LBSSP_DATA/nodal_fullnode_shotgathers_v4/catalog_exports/20260617T230552Z_da97ed5d_shot_gather_files.csv
trace_index 338580 -> /Volumes/tachyon/LBSSP_DATA/nodal_fullnode_shotgathers_v4/catalog_exports/20260617T230552Z_da97ed5d_trace_index.csv
picks 790020 -> /Volumes/tachyon/LBSSP_DATA/nodal_fullnode_shotgathers_v4/catalog_exports/20260617T230552Z_da97ed5d_picks.csv
processing_errors 0 -> /Volumes/tachyon/LBSSP_DATA/nodal_fullnode_shotgathers_v4/catalog_exports/20260617T230552Z_da97ed5d_processing_errors.csv

## 11. Next notebooks

Recommended follow-ons:

- `91_stack_nodal_repeated_shots_by_metadata.ipynb`
- `92_extract_source_waveforms_and_spectra_from_catalog.ipynb`
- `93_compare_geode_streamer_nodal_common_shots.ipynb`
- `94_build_combined_supergathers.ipynb`

These should query `lbssp_shot_catalog.sqlite`, not reconstruct filenames manually.

# Testing
What remains are some suggestions by ChatGPT to check what we now have in the database

In [13]:
shot_events = pd.read_sql("SELECT * FROM shot_events LIMIT 5", conn)

print(shot_events.columns.tolist())

['event_id', 'instrument_system', 'line', 'transect', 'survey', 'survey_type', 'shot_no', 'file_no', 'source_x_m', 'source_type', 'n_blows', 'n_shots', 'operator', 'plate_type', 'shot_time_local', 'shot_time_utc', 'receiver_first_m', 'receiver_last_m', 'receiver_spacing_m', 'nominal_shot_spacing_m', 'geode_read_ok', 'geode_read_format', 'geode_n_traces', 'geode_sampling_rate_hz', 'geode_duration_s_first_trace', 'geode_file_path', 'geode_folder', 'geode_match_status', 'geode_match_note', 'source_page', 'confidence', 'review_status', 'comment', 'metadata_source_sheet', 'extra_json', 'run_id', 'network', 'location', 'timewindow_label', 'geometry_id', 'detection_time_utc', 'on_time_utc', 'off_time_utc', 'duration_s', 'matched_metadata_event_id', 'metadata_match_status', 'metadata_match_time_error_s', 'detection_n_seed_ids', 'detection_n_stations', 'detection_seed_ids', 'detection_stations', 'snr_rms', 'n_receivers_extracted', 'n_traces_extracted', 'status', 'notes']

In [14]:
import pandas as pd

shot_events = pd.read_sql(
    """
    SELECT
        timewindow_label,
        detection_time_utc,
        shot_time_utc,
        source_x_m,
        file_no,
        metadata_match_status
    FROM shot_events
    """,
    conn,
)

shot_events["detection_time_utc"] = pd.to_datetime(
    shot_events["detection_time_utc"],
    errors="coerce",
    utc=True,
)

shot_events["shot_time_utc"] = pd.to_datetime(
    shot_events["shot_time_utc"],
    errors="coerce",
    utc=True,
)

summary = (
    shot_events
    .groupby("timewindow_label")
    .agg(
        n_events=("detection_time_utc", "count"),
        first_detection=("detection_time_utc", "min"),
        last_detection=("detection_time_utc", "max"),
        n_geode_matches=("shot_time_utc", lambda x: x.notna().sum()),
    )
    .reset_index()
)

display(summary)

,timewindow_label,n_events,first_detection,last_detection,n_geode_matches
0,T1_N1_Streamer,532,2026-05-16 17:13:01.890000+00:00,2026-05-16 21:44:03.302000+00:00,0
1,T1_N2_Nodal1,1376,2026-05-17 16:19:34.132000+00:00,2026-05-17 18:59:59.388000+00:00,0
2,T1_N2_Nodal2,81,2026-05-19 13:07:40.072000+00:00,2026-05-19 13:15:26.874000+00:00,0
3,T1_N2_Refraction1m,431,2026-05-18 16:07:22.442000+00:00,2026-05-18 18:38:21.774000+00:00,0
4,T1_N2_Refraction2m,450,2026-05-18 20:17:03.646000+00:00,2026-05-18 23:13:08.346000+00:00,0
5,T1_N3_Nodal3,43,2026-05-19 14:00:18.624000+00:00,2026-05-19 14:03:18.740000+00:00,0
6,T3_N4_Refraction1am,523,2026-05-19 16:02:33.030000+00:00,2026-05-19 18:22:04.542000+00:00,0

In [17]:
pd.read_sql(
    """
    SELECT name
    FROM sqlite_master
    WHERE type='table'
    ORDER BY name
    """,
    conn,
)

                name
0              picks
1  processing_errors
2    processing_runs
3  receiver_geometry
4        shot_events
5  shot_gather_files
6        trace_index